# Flashcards de Acto Jurídico: lote 8 (tema 21 Ratificación y tema 22 Efectos de la nulidad).
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # T22.1 Ratificación o confirmación
 ('T22.1', 'Concepto', 'basica', '¿Qué es confirmar un acto nulo relativamente y qué es, en el fondo, esa confirmación?',
  'Es que quien tiene derecho a pedir la nulidad declare su voluntad de <b>no ejercer ese derecho</b>: con esa sola declaración, el vicio que afectaba al acto desaparece. En el fondo, confirmar es <b>renunciar al derecho a pedir la nulidad</b>: no se vuelve a celebrar el acto viciado, solo deja de poder atacarse.',
  'IV.B.3.6.1'),
 ('T22.1', 'Regla', 'intermedia', '¿Por qué puede confirmarse el acto nulo relativamente y no el que adolece de nulidad absoluta?',
  'Porque la nulidad relativa protege solo a <b>personas determinadas</b>: es un derecho que mira a su interés particular y cae en la regla general que permite renunciar a los derechos que solo miran al interés de quien renuncia, si la renuncia no está prohibida (' + A(12) + '). Por eso la confirmación es un <b>acto unilateral</b> y solo cabe cuando la nulidad es relativa.',
  'IV.B.3.6.1'),
 ('T22.1', 'Distinción', 'basica', '¿Qué clases de ratificación reconoce el Código para sanear la nulidad relativa?',
  'Puede ser <b>expresa o tácita</b> (' + A(1693) + '). Es <b>expresa</b> cuando quien tiene derecho a pedir la rescisión declara, en términos explícitos y directos, que quiere validar el acto. Es <b>tácita</b> "la ejecución voluntaria de la obligación contratada" (' + A(1695) + ').',
  'IV.B.3.6.2'),
 ('T22.1', 'Regla', 'avanzada', 'Ratificación tácita: ¿qué se entiende por "ejecución voluntaria", basta otro comportamiento y hay que ejecutar el acto entero?',
  '(i) <b>Ejecución voluntaria</b>: para unos basta ejecutar libre y espontáneamente, sin vicios; otros exigen además que el confirmante <b>conozca el motivo de anulabilidad</b>, lectura que convence más. (ii) <b>Otro comportamiento</b>: la mayoría dice que no basta; pedir un plazo para pagar no equivale a confirmar. (iii) <b>Ejecución total</b>: el Código no la exige; aunque queden obligaciones pendientes, la ratificación tácita ya se produjo (' + A(1695) + ').',
  'IV.B.3.6.2'),
 ('T22.1', 'Enumeración', 'intermedia', '¿Cuáles son las características de la ratificación?',
  '(i) <b>Unilateral</b>: basta la voluntad de quien confirma; (ii) <b>accesoria y dependiente</b>: sin el acto que convalida no tiene dónde sostenerse; (iii) <b>irrevocable</b>: quien confirmó no puede pedir después la rescisión; y (iv) <b>retroactiva</b>: la ley finge que el acto confirmado fue válido desde siempre, como si el vicio nunca hubiera existido.',
  'IV.B.3.6.3'),
 ('T22.1', 'Enumeración', 'intermedia', '¿Cuáles son los requisitos de la ratificación?',
  '(i) Que el vicio esté sancionado con <b>nulidad relativa</b>; (ii) que emane de <b>quien tiene derecho a alegar la nulidad</b> (' + A(1696) + '); (iii) que quien ratifica sea <b>capaz de contratar</b> (' + A(1697) + '), salvo que actúe debidamente representado o autorizado; (iv) que se haga <b>antes de que se declare la nulidad</b>; (v) que la causa de invalidez <b>haya cesado</b>, con conocimiento del vicio y del derecho a pedir la nulidad; y (vi) si es expresa, que cumpla las <b>solemnidades</b> del acto que se ratifica (' + A(1694) + ').',
  'IV.B.3.6.4'),
 ('T22.1', 'Regla', 'intermedia', '¿Debe la ratificación de un acto solemne cumplir la misma solemnidad que ese acto?',
  'Solo si es <b>expresa</b>: "deberá hacerse con las solemnidades a que por la ley está sujeto el acto o contrato que se ratifica" (' + A(1694) + '). Esa exigencia no rige para la vía tácita: nada impide que un acto solemne se confirme en forma <b>tácita</b>, por la ejecución voluntaria de la obligación.',
  'IV.B.3.6.4'),
 # T23.1 Efectos de la nulidad entre las partes
 ('T23.1', 'Regla', 'basica', '¿Producen efectos distintos la nulidad absoluta y la relativa? ¿Desde cuándo los producen?',
  '<b>No</b>: en sus efectos son exactamente iguales, y las mismas normas rigen para ambas (' + AS('1687 y 1689') + '). Esos efectos dependen siempre de una <b>sentencia judicial firme</b>: mientras no exista, el acto sigue produciendo sus efectos normales.',
  'IV.B.4.1'),
 ('T23.1', 'Regla', 'basica', '¿Qué efecto produce entre las partes la nulidad declarada y cómo se calcula lo que cada una debe devolver?',
  'Da a las partes derecho a ser <b>restituidas al mismo estado</b> en que se hallarían si no hubiese existido el acto o contrato nulo (' + A(1687) + '). Se explica por el <b>efecto retroactivo</b>: se considera que el acto jamás existió, y por eso la nulidad es un modo de extinguir las obligaciones (' + A('1567 Nº 8') + '). Para las restituciones mutuas se aplican las reglas de las <b>prestaciones mutuas</b> de la reivindicación (' + AS('904 a 915') + '), atendiendo a la buena o mala fe de las partes.',
  'IV.B.4.2'),
 ('T23.1', 'Distinción', 'avanzada', '¿Qué criterio clásico distingue los efectos de la nulidad entre las partes y qué objeción le hace VIAL?',
  'Si el contrato <b>no fue cumplido</b> por ninguna de las partes, basta la declaración de nulidad para extinguir las obligaciones (' + A('1567 Nº 8') + '), sin nada que restituir; si fue cumplido por una o ambas, rige el ' + A(1687) + '. <b>VIAL</b> cuestiona que sea tan nítido: en los <b>contratos reales</b>, que generan precisamente la obligación de restituir, llevaría al absurdo de que esa obligación se extinga sola si la nulidad se declara antes de restituir la cosa.',
  'IV.B.4.2'),
 ('T23.1', 'Enumeración', 'intermedia', '¿Cuáles son las excepciones a la regla de las restituciones mutuas entre las partes?',
  '(i) El <b>poseedor de buena fe</b> no devuelve los frutos percibidos mientras estuvo en ese estado (' + A(907) + '); (ii) quien pagó o entregó algo sabiendo que el <b>objeto o la causa eran ilícitos</b> no puede pedirlo de vuelta (' + A(1468) + '); (iii) a quien contrató con un <b>incapaz</b> solo se le restituye lo pagado si prueba que el incapaz se hizo más rico (' + AS('1687 inc. 2° y 1688') + '); y (iv) la tradición nula o anulada sirve de título posesorio para <b>adquirir por prescripción extraordinaria</b>.',
  'IV.B.4.2'),
 ('T23.1', 'Regla', 'intermedia', 'Anulado un contrato por la incapacidad de una parte, ¿puede la otra exigirle al incapaz que le devuelva lo que le pagó?',
  'Solo si prueba que el incapaz <b>se hizo más rico</b> con ello (' + AS('1687 inc. 2° y 1688') + '): porque lo gastado le era necesario o porque, sin serlo, aún conserva esas cosas y quiere quedarse con ellas. Si se enriqueció, restituye según la regla general, para evitar un enriquecimiento sin causa. Esta protección es <b>exclusiva de la incapacidad</b>: no se extiende a otras causales de nulidad.',
  'IV.B.4.2'),
 # T23.2 Efectos respecto de terceros y acciones que nacen de la nulidad
 ('T23.2', 'Regla', 'basica', '¿Qué efecto produce la nulidad declarada respecto de terceros y en qué se diferencia de la resolución?',
  'El dueño original recupera <b>acción reivindicatoria</b> contra quien posea la cosa, aunque sea un tercero (' + A(1689) + '): por el efecto retroactivo, el dominio nunca salió de su patrimonio y nadie pudo transmitir más derechos de los que tenía. La nulidad alcanza a los terceros <b>de buena o mala fe</b>; la resolución, solo a los de mala fe (' + AS('1490 y 1491') + '). Si el poseedor gravó la cosa con hipoteca, servidumbre u otro derecho real, el dueño puede pedir que esos <b>gravámenes caduquen</b>.',
  'IV.B.4.3'),
 ('T23.2', 'Enumeración', 'intermedia', '¿En qué casos, pese a declararse la nulidad, no procede la acción reivindicatoria contra terceros?',
  '(i) La <b>rescisión por lesión enorme</b>: los gravámenes no caducan, el comprador debe purificar la cosa antes de restituirla (' + A(1895) + '), y si ya la enajenó se pierde la acción rescisoria (' + A(1893) + '); (ii) el tercero que <b>adquirió por prescripción</b>, porque los defectos del título de sus antecesores no se le transmiten (' + AS('682, 683 y 717') + ') y la reivindicación se extingue por la prescripción adquisitiva del mismo derecho (' + A(2517) + '); y (iii) el <b>heredero indigno</b> que enajenó bienes de la herencia: solo se persiguen en manos de terceros de mala fe (' + A(974) + ').',
  'IV.B.4.3'),
 ('T23.2', 'Enumeración', 'intermedia', '¿Qué acciones nacen de un acto nulo, contra quién se dirige cada una y pueden demandarse juntas?',
  '(i) La <b>acción de nulidad</b>, personal: la entabla un contratante contra el otro, y si la entabla un tercero (nulidad absoluta), contra todos los que celebraron el acto; (ii) la <b>acción reivindicatoria</b>, real: contra quien hoy posea la cosa, sea contratante o tercero (' + A(1689) + '); y, para un sector de la doctrina, (iii) la <b>de indemnización de perjuicios</b>. Las dos primeras pueden deducirse <b>juntas en el mismo juicio</b>, sujetando la reivindicatoria a que se acoja la de nulidad (' + AS('17 y 18 C.P.C.') + ').',
  'IV.B.4.4'),
 ('T23.2', 'Regla', 'avanzada', 'La acción rescisoria es una prescripción de corto tiempo. ¿Se suspende? ¿Puede extenderse la suspensión a otros incapaces?',
  'Las prescripciones de corto tiempo corren por regla general contra toda persona, salvo que la ley diga lo contrario (' + A(2524) + '), y la rescisoria es una de esas excepciones: es la <b>única hipótesis de suspensión</b> en la materia, a favor de los <b>herederos menores</b> de quien podía pedir la rescisión (' + A(1692) + '). Por ser excepcional, <b>no se extiende por analogía</b> a otros incapaces que no sean menores, y tiene un tope de diez años desde la celebración del acto (' + A('2520 inc. 2°') + ').',
  'IV.B.4.4'),
 ('T23.2', 'Enumeración', 'avanzada', '¿Qué normas del Código contemplan una indemnización de perjuicios ligada a un acto nulo o anulable?',
  'No hay norma general, solo disposiciones sueltas. La mencionan de paso los ' + AS('1353 y 1813') + ', y la desarrollan tres casos: (i) quien de buena fe contrató por <b>error en la persona</b> (' + A(1455) + '); (ii) el vendedor que sabía que la cosa <b>no existía</b>, del todo o en parte, debe resarcir al comprador de buena fe (' + A(1814) + '); y (iii) el <b>dolo incidental</b>, que no vicia el consentimiento pero da acción de perjuicios (' + A('1458 inc. 2°') + ').',
  'IV.B.4.4'),
 ('T23.2', 'Distinción', 'avanzada', 'Error sustancial o esencial: ¿procede indemnizar a quien lo sufrió? ¿Qué sostienen RODRÍGUEZ y BARAONA?',
  'La doctrina se divide. <b>RODRÍGUEZ</b> la niega: en estas clases de error normalmente lo padecen ambas partes, así que las culpas se compensan. <b>BARAONA</b> la admite cuando solo una incurrió en el error, si quien se equivocó no fue inducido dolosamente y su error se explica por una negligencia inadmisible, y si quien pide la indemnización está de buena fe.',
  'IV.B.4.4'),
 ('T23.2', 'Regla', 'intermedia', '¿Es compatible pedir indemnización de perjuicios con demandar la nulidad? ¿Qué se exige?',
  '<b>Sí</b>, sea la nulidad absoluta o relativa, con dos mínimos: que quien la pide esté de <b>buena fe</b> respecto del vicio, y que a la contraparte se le pueda atribuir <b>culpa</b> (inducción dolosa, reticencia o simple negligencia). También funciona al revés: quien debe soportar la nulidad puede <b>reconvenir</b> pidiendo indemnización, según la causal invocada y las circunstancias del contrato.',
  'IV.B.4.4'),
 ('T23.2', 'Distinción', 'avanzada', '¿Qué naturaleza tiene la responsabilidad por los perjuicios de un acto declarado nulo?',
  'La doctrina mayoritaria <b>descarta la contractual</b>: lo reprochado ocurrió antes del contrato y la sentencia de nulidad borra ese contrato. <b>RODRÍGUEZ</b> sostiene que es una <b>responsabilidad legal</b>: nace de la ley, aunque supone culpa o dolo, y las normas extracontractuales no se aplican íntegramente. La mayoría, <b>BARAONA</b> incluido, sostiene que es <b>extracontractual</b>, apreciando la culpa de cada parte según haya actuado de buena o mala fe.',
  'IV.B.4.4'),
 # T23.3 La conversión del acto nulo
 ('T23.3', 'Concepto', 'intermedia', '¿Qué es la conversión del acto nulo y qué principio la inspira?',
  'Según <b>ALESSANDRI</b>, es una "transformación producida por el imperio de la ley, en virtud de la cual un acto jurídico ineficaz, tal como los agentes lo han operado, es sustituido por otro acto jurídico de distinta naturaleza, y con lo cual se cumplen las miras económicas que tuvieron en vista los agentes al realizar el primero". La inspira el <b>principio de conservación del negocio jurídico</b>: mantener, hasta donde sea posible, lo que las partes quisieron, para que alcancen el resultado práctico que buscaban.',
  'IV.B.4.5'),
 ('T23.3', 'Distinción', 'avanzada', '¿Qué clases de conversión distingue la doctrina?',
  '(i) <b>Formal</b>: no cambia el negocio, solo su documentación; las partes usan una forma más exigente que falla, pero se cumple la más simple que bastaba (la promesa en escritura nula que vale porque solo se exige que conste por escrito, ' + A('1554 N° 1') + '; el instrumento público nulo que vale como privado, ' + A(1701) + '). (ii) <b>Material</b>: el acto nulo vale como el negocio distinto cuyos requisitos sí cumple (la letra de cambio mal extendida que vale como reconocimiento de deuda). (iii) <b>Legal</b>: por mandato expreso de la ley, el acto nulo tiene los efectos de otro negocio (la donación irrevocable entre cónyuges, que vale como revocable, ' + AS('1137 y 1138') + ').',
  'IV.B.4.5'),
 ('T23.3', 'Enumeración', 'avanzada', '¿Qué requisitos exige la conversión material según COVIELLO y en qué discrepa STOLFI?',
  'Según <b>COVIELLO</b>, un elemento <b>objetivo</b>: que el negocio nulo reúna todos los elementos de un negocio de distinta naturaleza; y uno <b>subjetivo</b>: que ese negocio pueda reputarse querido por las partes según su <b>voluntad hipotética</b> (la que habrían tenido de saber que el acto era nulo), por lo que la conversión supone que las partes <b>ignoran</b> el vicio. <b>STOLFI</b> exige lo contrario: que las partes <b>conozcan</b> la ineficacia del acto.',
  'IV.B.4.5'),
 ('T23.3', 'Regla', 'intermedia', '¿Qué límites tiene la conversión del acto nulo?',
  'Dos. (i) Si las <b>propias partes la prohíben</b>, no puede presumirse que su voluntad hipotética habría aceptado el nuevo negocio. (ii) Si la ley exige el <b>instrumento público como solemnidad</b> del acto, no hay instrumento privado que valga (' + A(1701) + '): la compraventa de un inmueble sin escritura pública no vale ni como compraventa ni como promesa. La Corte Suprema ha dicho que "las hipótesis de conversión del acto nulo son de aplicación estricta".',
  'IV.B.4.5'),
 ('T23.3', 'Distinción', 'avanzada', '¿Puede operar la conversión material sin una norma legal expresa que la autorice?',
  'Hay dos posturas. <b>ALESSANDRI</b>, de acuerdo con <b>VIAL</b>: <b>no</b>, porque el Código no tiene una disposición que permita la conversión en términos generales, así que se restringe a los casos en que la ley la permite expresamente. Otro sector: <b>sí</b>, sería una institución de aplicación general que opera siempre que se cumplan sus requisitos, por el principio de conservación del negocio jurídico.',
  'IV.B.4.5'),
]
