# Flashcards de Acto Jurídico: lote 3 (temas 12 Capacidad y 13 Objeto).
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # Tema 12: Capacidad
 ('T13.1', 'Concepto', 'basica', '¿Qué es la capacidad y qué dos clases de capacidad se distinguen?',
  'La doctrina la define como "la aptitud para adquirir derechos y ejercitarlos". De ahí salen dos clases: la <b>capacidad de goce</b> (o jurídica), que mira a la adquisición de los derechos, y la <b>capacidad de ejercicio</b> (o de obrar), que mira a su ejercicio.',
  'II.B.1'),
 ('T13.1', 'Regla', 'intermedia', '¿Puede un ser humano carecer completamente de capacidad de goce?',
  'No. La capacidad de goce es la aptitud para ser sujeto de derechos y todo ser humano la tiene desde que nace: equivale a la <b>personalidad</b>, y negarla del todo sería negar la calidad de persona. Solo existen <b>incapacidades de goce especiales</b>, que impiden adquirir uno o más derechos determinados, nunca todos.',
  'II.B.2.1'),
 ('T13.1', 'Regla', 'basica', '¿Cómo define el Código la capacidad de ejercicio y cuál es la regla general?',
  'El Código la llama capacidad legal: "consiste en poderse obligar por sí misma, y sin el ministerio o la autorización de otra" (' + A('1445 inc. final') + '). La regla general es la <b>capacidad</b>: "Toda persona es legalmente capaz, excepto aquellas que la ley declara incapaces" (' + A(1446) + '), norma que se aplica a todos los actos jurídicos.',
  'II.B.2.2'),
 ('T13.2', 'Enumeración', 'basica', '¿Quiénes son absolutamente incapaces?',
  'Los <b>dementes</b>, los <b>impúberes</b> (el varón que no ha cumplido 14 años y la mujer que no ha cumplido 12, ' + A(26) + ') y los <b>sordos o sordomudos que no pueden darse a entender claramente</b> (' + A('1447 inc. 1°') + ').',
  'II.B.3.1 (ii)'),
 ('T13.2', 'Concepto', 'intermedia', '¿En qué sentido usa el Código la palabra "demente"?',
  'No en su sentido médico, sino en un sentido <b>amplio</b>, como sinónimo de <b>enfermedad mental</b>. Los tribunales se apoyan en la parte final del ' + A(21) + ': las palabras técnicas se toman en el sentido de la ciencia respectiva, "a menos que aparezca claramente que se han tomado en sentido diverso".',
  'II.B.3.1 (ii) a)'),
 ('T13.2', 'Regla', 'intermedia', '¿Qué hace incapaz al sordo o sordomudo y qué cambió la Ley Nº 19.904?',
  'No la sordera, sino <b>no poder darse a entender claramente</b>: quien se comunica por escrito, con lengua de señas o de otro modo, es capaz. Antes de la Ley Nº 19.904 (2003) eran incapaces los que no podían darse a entender <b>por escrito</b>, lo que dejaba como incapaz absoluto al que se comunicaba perfectamente por señas pero no sabía leer ni escribir.',
  'II.B.3.1 (ii) c)'),
 ('T13.2', 'Regla', 'intermedia', '¿Cómo actúan los absolutamente incapaces y qué sanción tienen sus actos?',
  'Solo pueden actuar <b>representados</b> por su representante legal (' + A(43) + '). Sus actos no producen ni aun <b>obligaciones naturales</b> y no admiten caución (' + A('1447 inc. 2°') + '); el Código los sanciona con <b>nulidad absoluta</b> (' + A('1682 inc. 2°') + '), aunque en estricto rigor serían inexistentes, porque el absolutamente incapaz no tiene voluntad.',
  'II.B.3.1 (iii) y (iv)'),
 ('T13.3', 'Enumeración', 'basica', '¿Quiénes son relativamente incapaces hoy y quién lo fue hasta 1989?',
  'Los <b>menores adultos</b> (el varón mayor de 14 años y la mujer mayor de 12 que no cumplen 18, ' + A(26) + ') y los <b>disipadores bajo interdicción</b> de administrar lo suyo (' + A('1447 inc. 3°') + '). Hasta 1989 lo fue también la <b>mujer casada en sociedad conyugal</b>; la Ley Nº 18.802 eliminó esa incapacidad.',
  'II.B.3.2 (ii)'),
 ('T13.3', 'Regla', 'intermedia', '¿En qué casos valen los actos del menor adulto?',
  'Cuando los celebra con <b>autorización de su representante legal</b>, y cuando se refieren a su <b>peculio profesional o industrial</b> (lo que gana con su trabajo), respecto del cual la ley lo mira como mayor de edad (' + A(251) + '). Límite: los bienes raíces del peculio no pueden enajenarse ni gravarse sin <b>autorización del juez</b> con conocimiento de causa (' + A(254) + ').',
  'II.B.3.2 (ii) a)'),
 ('T13.3', 'Regla', 'intermedia', '¿Cómo actúan los relativamente incapaces y qué sanción tienen sus actos si se omiten las formalidades?',
  'Actúan <b>representados</b> o <b>autorizados</b>, según lo que disponga la ley. Los requisitos que deben cumplir son <b>formalidades habilitantes</b>: si se omiten, el acto es nulo de <b>nulidad relativa</b> (' + A(1682) + '). A diferencia de los absolutamente incapaces, sus actos sí generan <b>obligaciones naturales</b> (' + A('1470 Nº 1') + '), cuestión discutida para el disipador.',
  'II.B.3.2 (iii) y (iv)'),
 ('T13.4', 'Concepto', 'intermedia', '¿Qué son las incapacidades particulares y en qué se diferencian de la incapacidad absoluta y relativa?',
  'Son <b>prohibiciones</b> que la ley impone a ciertas personas para ejecutar ciertos actos (' + A('1447 inc. final') + '), como la compraventa entre cónyuges no separados judicialmente (' + A(1796) + ') o la compra por el empleado público de los bienes que se venden por su ministerio (' + A(1798) + '). La absoluta y la relativa son <b>generales</b>; las particulares se reducen a <b>ciertos actos</b>.',
  'II.B.3.3'),
 ('T13.4', 'Distinción', 'avanzada', '¿Qué sanción tienen los actos celebrados contra una incapacidad particular?',
  'Depende de la forma de la incapacidad. <b>Nulidad absoluta</b>, si es una prohibición absoluta (compraventa entre cónyuges no separados judicialmente). <b>Nulidad relativa</b>, si el acto solo puede celebrarse con autorización de otro (' + A('412 inc. 1°') + '; ' + AS('1754 y 1757') + '). <b>Otra sanción</b>, si la ley lo dispone: el arriendo de bienes raíces de la mujer más allá del plazo legal sin su autorización vale solo por ese plazo y el exceso le es inoponible (' + AS('1749, 1756 y 1757') + ').',
  'II.B.3.3 (i) a (iii)'),
 # Tema 13: Objeto
 ('T14.1', 'Regla', 'basica', '¿Qué dice el Código sobre el objeto de la declaración de voluntad?',
  'No lo define, pero dice en qué consiste: "Toda declaración de voluntad debe tener por objeto una o más cosas que se trata de <b>dar, hacer o no hacer</b>. El mero uso de la cosa o su tenencia puede ser objeto de la declaración" (' + A(1460) + ').',
  'II.C.1'),
 ('T14.1', 'Enumeración', 'intermedia', '¿Qué respuestas da la doctrina a la pregunta de qué es el objeto, y cuál se sigue en Chile?',
  'Tres: (i) los <b>derechos y obligaciones</b> que el acto genera; (ii) la <b>prestación</b>, es decir, la cosa que hay que dar o el hecho que hay que ejecutar o no ejecutar; y (iii) la <b>materia</b>, utilidades o relaciones que las partes someten a su voluntad (doctrina más moderna). En Chile se sigue en general la <b>segunda</b>, por la letra del ' + A(1460) + '.',
  'II.C.1 (i) a (iii)'),
 ('T14.1', 'Distinción', 'avanzada', '¿Qué cuatro objetos distintos confunde el Código bajo la palabra "objeto"?',
  'El objeto del <b>acto jurídico</b> (los efectos jurídicos que produce); el del <b>contrato</b> (los derechos y obligaciones que nacen de él); el de la <b>obligación</b> (la prestación que el deudor debe cumplir); y el de la <b>prestación</b> (la cosa que hay que dar o el hecho o abstención). Como todo acto se traduce en cosas que dar o hechos que ejecutar, la confusión tiene poca importancia práctica.',
  'II.C.1'),
 ('T14.2', 'Enumeración', 'basica', '¿Qué requisitos debe reunir el objeto que recae sobre una cosa?',
  'Sea material o inmaterial, la cosa debe ser <b>real</b>, <b>comerciable</b> y <b>determinada</b> (' + A(1461) + ').',
  'II.C.2'),
 ('T14.2', 'Regla', 'intermedia', '¿Qué pasa con la venta de una cosa que se supone existente y no existe al perfeccionarse el contrato?',
  '"No produce efecto alguno" (' + A(1814) + '): el acto se queda sin objeto. Según la doctrina que se siga, es <b>inexistente</b> o, a lo menos, <b>nulo de nulidad absoluta</b>.',
  'II.C.2.1'),
 ('T14.2', 'Distinción', 'intermedia', '¿Qué diferencia hay entre vender una cosa futura y vender la suerte?',
  'Si se vende la <b>cosa futura</b> misma, la venta se entiende hecha bajo la <b>condición suspensiva</b> de que llegue a existir; si no existe, se mira como no hecha (salvo pacto en contrario). Si se vende la <b>suerte</b> (la posibilidad de que la cosa exista), la venta es <b>pura y simple</b> y <b>aleatoria</b>: se paga igual aunque la cosa no llegue a existir (' + A(1813) + ').',
  'II.C.2.1'),
 ('T14.3', 'Concepto', 'basica', '¿Cuándo es comerciable una cosa y qué cosas no lo son?',
  'Es comerciable la cosa que puede ser objeto de <b>propiedad o posesión privada</b>. No lo son las que no se pueden apropiar por su <b>naturaleza</b>, como las cosas comunes a todos los hombres (alta mar, aire, ' + A(585) + '), ni las que no se pueden apropiar por su <b>destino</b>, como los bienes nacionales de uso público (calles, plazas, playas, ' + A(589) + '), mientras conserven ese destino.',
  'II.C.2.2'),
 ('T14.4', 'Regla', 'intermedia', '¿Cómo debe estar determinada la cosa objeto del acto?',
  'Por lo menos en cuanto a su <b>género</b> (' + A('1461 inc. 1°') + '): puede determinarse en <b>especie</b> (un individuo concreto) o en <b>género</b> (cualquier individuo de un género determinado). El género debe ser <b>limitado</b> ("un animal" no basta). La <b>cantidad</b> puede ser incierta si el acto fija reglas o datos para determinarla (' + A('1461 inc. 2°') + ').',
  'II.C.2.3'),
 ('T14.4', 'Regla', 'basica', 'En una obligación de género, si nada se dijo sobre la calidad, ¿qué debe entregar el deudor?',
  'Cualquier individuo del género, "con tal que sea de una calidad a lo menos <b>mediana</b>" (' + A(1509) + '). El acreedor no puede exigir un individuo determinado.',
  'II.C.2.3'),
 ('T14.5', 'Enumeración', 'basica', '¿Qué requisitos debe reunir el objeto cuando recae sobre un hecho?',
  'El hecho, positivo (hacer) o negativo (abstenerse), debe ser <b>determinado</b>, <b>físicamente posible</b> y <b>moralmente posible</b> (' + A('1461 inc. 3°') + ').',
  'II.C.3'),
 ('T14.5', 'Distinción', 'intermedia', '¿Qué imposibilidad física impide que nazca la obligación: la absoluta o la relativa?',
  'Solo la <b>absoluta</b>: el hecho debe ser irrealizable para <b>cualquier persona</b> (contrario a la naturaleza, ' + A('1461 inc. 3°') + '); entonces no nace obligación alguna. Si solo el deudor no puede hacerlo, la imposibilidad es <b>relativa</b> y la obligación vale; si no cumple, debe indemnizar. Lo imposible cambia con el tiempo y el lugar.',
  'II.C.3.2'),
 ('T14.5', 'Concepto', 'intermedia', '¿Cuándo es moralmente imposible un hecho y qué consecuencia tiene?',
  'Cuando está <b>prohibido por las leyes</b>, o es <b>contrario a las buenas costumbres o al orden público</b> (' + A('1461 inc. 3°') + '). Se lee junto al ' + A(10) + ': los actos que la ley prohíbe son nulos y de ningún valor, salvo que la ley les asigne otro efecto. El acto tiene <b>objeto ilícito</b> y es nulo absolutamente (' + A(1682) + ').',
  'II.C.3.3'),
]
