# Flashcards de Acto Jurídico: lote 7 (tema 20 Nulidad: concepto, clases, causales, titulares y saneamiento).
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # T21.01 Reglas, concepto general y especies de nulidad
 ('T21.01', 'Enumeración', 'intermedia', '¿Dónde regula el Código Civil la nulidad y qué tres rasgos tienen esas reglas?',
  'En el Título XX del Libro IV (' + AS('1681 a 1697') + '). Sus reglas son: (i) de <b>alcance general</b>: rigen para cualquier acto jurídico, unilateral o bilateral, salvo que una disposición expresa consulte otra sanción; (ii) de <b>orden público</b>: de aplicación estricta, las partes no pueden derogarlas; y (iii) de <b>derecho privado</b>: se aplican en las demás ramas del derecho privado si no hay norma especial, pero no se extienden al derecho público.',
  'IV.B.1.1'),
 ('T21.01', 'Concepto', 'basica', '¿Cómo define la doctrina la nulidad y de qué norma se desprende esa definición?',
  'Es "la sanción legal establecida por la omisión de los requisitos y formalidades que se prescriben para el valor de un acto según su especie y la calidad o estado de las partes". Se desprende del ' + A('1681 inc. 1°') + ': "es nulo todo acto o contrato a que falta alguno de los requisitos que la ley prescribe para el valor del mismo acto o contrato, según su especie y la calidad o estado de las partes".',
  'IV.B.1.2'),
 ('T21.01', 'Distinción', 'intermedia', '¿Por qué una nulidad se llama absoluta y la otra relativa?',
  'Por <b>dónde está el vicio</b>. En la <b>absoluta</b>, el requisito omitido se exige en consideración a la naturaleza o especie del acto: el acto está mal formado en sí mismo, su nulidad es objetiva y alcanza a todos (erga omnes). En la <b>relativa</b>, el requisito se exige en atención a la calidad o estado de las partes: falla una exigencia pensada para proteger a cierta persona, el vicio es subjetivo y la nulidad solo opera respecto de esas personas (' + A('1681 inc. 2°') + ').',
  'IV.B.1.3'),
 ('T21.01', 'Regla', 'intermedia', '¿Es la nulidad absoluta un grado más grave de invalidez que la relativa?',
  '<b>No.</b> La distinción no mide cuán grave es la ineficacia: declaradas judicialmente, las dos producen <b>exactamente los mismos efectos</b>, volver a las partes al estado anterior a la celebración del acto nulo. Las diferencias están en las <b>causales</b>, en <b>quién puede pedir</b> cada una y en el <b>plazo</b> en que se sanean.',
  'IV.B.1.3'),
 # T21.02 Terminología y nulidad como regla general
 ('T21.02', 'Regla', 'avanzada', '¿Son sinónimos "nulidad relativa" y "rescisión"? ¿Qué razones da el sector de la doctrina que lo niega?',
  'Para ese sector, <b>no</b>: la rescisión no es sinónimo de la nulidad relativa, sino su <b>efecto</b>, el derecho a pedir que el acto quede sin efecto, cualquiera sea la causa. Razones: (i) el ' + A('1682 inc. final') + ' no las iguala, dice que una "da derecho" a la otra; (ii) rescindir es "dejar sin efecto", efecto que produce cualquiera de las dos nulidades; y (iii) la sinonimia lleva a un absurdo: "la nulidad relativa da derecho a pedir la nulidad relativa".',
  'IV.B.1.4'),
 ('T21.02', 'Regla', 'basica', '¿Qué especie de nulidad es la regla general y por qué?',
  'La <b>nulidad relativa</b>. El ' + A('1682 inc. final') + ' cierra la enumeración de las causales de nulidad absoluta con una cláusula residual: "cualquiera otra especie de vicio produce nulidad relativa". Todo vicio que la ley no sancione expresamente de otro modo cae ahí.',
  'IV.B.1.5'),
 # T21.03 Diferencias entre nulidad absoluta y relativa
 ('T21.03', 'Distinción', 'basica', 'Nulidad absoluta y relativa: ¿cuál es el fundamento de cada una y quién puede pedirlas?',
  '<b>Absoluta</b>: se funda en el interés de la moral y de la ley; puede pedirla todo el que tenga interés en ello y el ministerio público en el interés de la moral o de la ley (' + A(1683) + '). <b>Relativa</b>: se funda en el interés de ciertas y determinadas personas; solo pueden pedirla aquellos en cuyo beneficio la han establecido las leyes, o sus herederos o cesionarios, y no el ministerio público en el solo interés de la ley (' + A(1684) + ').',
  'IV.B.1.6'),
 ('T21.03', 'Distinción', 'basica', 'Nulidad absoluta y relativa: ¿puede declararlas el juez de oficio y cómo se sanea cada una?',
  '<b>Absoluta</b>: puede y debe declararla el juez, aun sin petición de parte, cuando aparece de manifiesto en el acto o contrato; no se sanea por ratificación, y se sanea por el tiempo a los <b>diez años</b> desde la celebración. <b>Relativa</b>: solo a petición de parte; se sanea por ratificación o confirmación, y por el tiempo a los <b>cuatro años</b>, desde la celebración en caso de error o dolo, y desde que cesa la fuerza o la incapacidad (' + AS('1683 y 1684') + ').',
  'IV.B.1.6'),
 # T21.04 Principios comunes a ambas nulidades
 ('T21.04', 'Enumeración', 'intermedia', '¿Cuáles son los seis principios comunes a la nulidad absoluta y a la relativa?',
  '(i) Es de <b>derecho estricto</b>; (ii) <b>no puede renunciarse anticipadamente</b>; (iii) el vicio debe existir <b>al celebrarse el acto</b>; (iv) solo <b>aprovecha a quien la obtiene</b>; (v) se hace valer como <b>acción o como excepción</b>; y (vi) requiere <b>sentencia judicial</b>.',
  'IV.B.1.7'),
 ('T21.04', 'Regla', 'intermedia', '¿En qué dos casos un acto es nulo, considerando que la nulidad es de derecho estricto?',
  'Las sanciones no se presumen ni se aplican por analogía, así que solo es nulo el acto que la ley declara nulo de una de dos formas: (i) cuando la ley dice <b>expresamente</b> que un acto determinado es nulo; o (ii) cuando la ley <b>prohíbe</b> un acto y no fija una sanción distinta de la nulidad para quien lo contraviene (' + A(10) + ').',
  'IV.B.1.7'),
 ('T21.04', 'Regla', 'intermedia', '¿Puede renunciarse por anticipado la acción de nulidad en el mismo contrato?',
  '<b>No.</b> "Los actos o contratos que la ley declara inválidos, no dejarán de serlo por las cláusulas que en ellos se introduzcan y en que se renuncie la acción de nulidad" (' + A(1469) + '). Si se pudiera, bastaría una cláusula para vaciar la protección que la nulidad busca dar; ni las partes de común acuerdo pueden validar por su sola voluntad un acto que la ley declaró nulo.',
  'IV.B.1.7'),
 ('T21.04', 'Regla', 'intermedia', 'Un acto nació válido y después ocurre un hecho que, de haber existido al celebrarlo, lo habría viciado. ¿Es nulo?',
  '<b>No.</b> El vicio tiene que estar presente al momento mismo en que el acto se celebra: <b>no hay nulidad por causa sobreviniente</b>. Si el acto nació válido, ningún hecho posterior puede volverlo nulo.',
  'IV.B.1.7'),
 ('T21.04', 'Regla', 'avanzada', '¿Produce efectos el acto nulo mientras no se declara la nulidad? ¿Qué sostiene la doctrina que discrepa respecto de la absoluta?',
  'Sí. Ninguna nulidad opera por sí sola: requiere <b>sentencia judicial firme</b>. Hasta entonces el acto produce todos sus efectos, amparado en una <b>presunción de validez</b>; declarada, la nulidad opera hacia atrás. Quienes discrepan sostienen que la nulidad absoluta, por su gravedad, opera de <b>pleno derecho</b>, y que lo que el ' + A(1683) + ' llama "saneamiento" a los diez años sería la caducidad de la acción para impugnar el acto.',
  'IV.B.1.7'),
 # T21.05 Nulidad total y parcial; consecuencial y refleja
 ('T21.05', 'Distinción', 'intermedia', '¿Qué es la nulidad parcial y qué criterio se usa para saber si el vicio de una cláusula arrastra a todo el acto?',
  'Es la que afecta solo una parte o cláusula del acto (o un elemento de ella), y el resto subsiste con plena validez; la <b>total</b> afecta todas sus partes y cláusulas. Es un ejercicio de ponderación: si lo viciado toca la <b>esencia</b> del acto, o si es un accidente tan secundario que, aun sabiendo que era nulo, las partes lo habrían celebrado igual. Ejemplo legal: la disposición testamentaria en favor del escribano que autoriza el testamento no vale (' + A(1061) + '), pero el resto del testamento sí.',
  'IV.B.1.8'),
 ('T21.05', 'Distinción', 'avanzada', '¿Qué es la nulidad consecuencial y cómo se aplica a los actos accesorios? ¿Y la nulidad refleja?',
  '<b>Consecuencial</b>: un acto es nulo porque depende de otro que es nulo; si la cláusula nula contiene la estipulación principal, o el acto no subsiste sin ella, cae todo el acto. En los accesorios, lo accesorio sigue la suerte de lo principal, no a la inversa: "la nulidad de la obligación principal acarrea la de la cláusula penal, pero la nulidad de ésta no acarrea la de la obligación principal" (' + A(1536) + '). <b>Refleja</b>: en un acto solemne, la escritura que es su forma es nula, y por eso es nulo el acto contenido en ella.',
  'IV.B.1.9'),
 # T21.06 Nulidad absoluta: concepto, causales y fundamento
 ('T21.06', 'Enumeración', 'basica', '¿Cuáles son las causales de nulidad absoluta según el ' + A(1682) + '?',
  'Cuatro: (i) el <b>objeto ilícito</b>; (ii) la <b>causa ilícita</b>; (iii) la <b>incapacidad absoluta</b>; y (iv) la omisión de requisitos o formalidades que las leyes prescriben para el valor de ciertos actos o contratos <b>en consideración a la naturaleza de ellos</b>.',
  'IV.B.2.2'),
 ('T21.06', 'Enumeración', 'intermedia', '¿Qué causales de nulidad absoluta agregan quienes rechazan la teoría de la inexistencia?',
  'Cinco más: (v) la <b>falta de voluntad</b>; (vi) la <b>falta de objeto</b>; (vii) la <b>falta de causa</b>; (viii) el <b>error esencial</b> (aunque algunos lo sancionan con nulidad relativa); y (ix) la omisión de requisitos o formalidades que las leyes prescriben para la <b>existencia</b> de ciertos actos o contratos, en consideración a su naturaleza.',
  'IV.B.2.2'),
 ('T21.06', 'Concepto', 'basica', '¿Qué es la nulidad absoluta y cuál es su fundamento?',
  'Es la sanción a todo acto o contrato al que falte alguno de los requisitos que la ley exige para su valor, <b>según la especie</b> del acto o contrato (' + A(1681) + '). No protege a nadie en particular: su fundamento es el <b>interés de la moral y de la ley</b>, amparar la primera y hacer respetar la segunda. De ahí salen sus características propias: quién la declara, quién la pide y cómo se sanea.',
  'IV.B.2.1 y 2.3'),
 # T21.07 Nulidad absoluta: quién la declara o pide
 ('T21.07', 'Enumeración', 'basica', '¿Por qué tres caminos puede llegar a declararse la nulidad absoluta?',
  'Según el ' + A(1683) + ': (i) <b>de oficio por el juez</b>, cuando aparece de manifiesto en el acto o contrato; (ii) a petición de <b>todo el que tenga interés</b> en ello, excepto el que ejecutó el acto o celebró el contrato sabiendo o debiendo saber el vicio; y (iii) a petición del <b>ministerio público</b>, en el interés de la moral o de la ley.',
  'IV.B.2.4'),
 ('T21.07', 'Regla', 'intermedia', '¿Cuándo debe el juez declarar de oficio la nulidad absoluta? ¿Qué significa que el vicio "aparezca de manifiesto"?',
  'La nulidad absoluta "puede y debe ser declarada por el juez, aun sin petición de parte, cuando aparece de manifiesto en el acto o contrato" (' + A(1683) + '). Es manifiesto lo que no exige más prueba que <b>leer el propio instrumento</b> donde consta el acto, sin acudir a otro antecedente del proceso. Y esa obligación supone que exista un <b>juicio</b> donde se invoque el acto o contrato.',
  'IV.B.2.4'),
 ('T21.07', 'Regla', 'intermedia', '¿Qué interés debe acreditar quien alega la nulidad absoluta? ¿Puede ser un tercero?',
  '"Todo el que tenga interés" habilita a las <b>partes y a terceros</b>, porque el vicio está en el acto mismo. Pero hay que acreditar un <b>interés real</b> (la posibilidad de reparar los perjuicios que causó el acto viciado), prueba que corresponde a quien lo invoca, y de carácter <b>pecuniario</b>; el interés puramente moral queda reservado al ministerio público (' + A(1683) + ').',
  'IV.B.2.4'),
 ('T21.07', 'Regla', 'avanzada', '¿Quién no puede alegar la nulidad absoluta? ¿Qué conocimiento del vicio se exige y por qué?',
  'El que ejecutó el acto o celebró el contrato <b>sabiendo o debiendo saber</b> el vicio que lo invalidaba (' + A(1683) + '). Se exige un conocimiento <b>real y efectivo</b>, nunca el presunto o ficto del ' + A('8°') + ': si fuera el presunto, nadie que celebró el acto podría alegar jamás la nulidad absoluta. "Debiendo saber" es el conocimiento que la situación le exigía tener, porque las circunstancias no permitían razonablemente ignorarlo. El fundamento es que nadie puede ser oído cuando alega su propia torpeza (nemo auditur).',
  'IV.B.2.4'),
 ('T21.07', 'Distinción', 'avanzada', 'Si el representante celebró el acto sabiendo el vicio, ¿puede el representado alegar la nulidad absoluta? ¿Y los herederos de quien contrató a sabiendas?',
  '<b>Representado</b>: se impone hoy la tesis de que <b>sí puede</b>; la prohibición alcanza a quien intervino directamente, salvo que se acredite de modo inequívoco que su propia voluntad concurrió en el vicio (el dolo es personalísimo; la tesis contraria invoca el ' + A(1448) + '). <b>Herederos</b>: la cuestión es discutida; unos dicen que pueden, porque la inhabilidad es de interpretación restrictiva; otros, que no, porque no heredan un derecho que su causante no tenía, y porque si con el incapaz doloso la ley excluye también a sus herederos (' + A(1685) + '), con mayor razón respecto de los capaces.',
  'IV.B.2.4'),
 ('T21.07', 'Regla', 'intermedia', '¿Qué ministerio público puede pedir la nulidad absoluta y con qué fundamento?',
  'El organismo auxiliar de la administración de justicia que regula el ' + A('350 COT') + ', integrado por el fiscal de la Corte Suprema y los fiscales de las Cortes de Apelaciones; <b>no</b> el que participa en el proceso penal. Puede pedirla "en el interés de la moral o de la ley" (' + A(1683) + ').',
  'IV.B.2.4'),
 # T21.08 Nulidad absoluta: saneamiento y no opera de pleno derecho
 ('T21.08', 'Regla', 'basica', '¿Puede sanearse la nulidad absoluta por ratificación de las partes? ¿Por qué?',
  '<b>No</b>, lo descarta expresamente la parte final del ' + A(1683) + '. Ratificar supone renunciar a pedir la nulidad del acto viciado, y esa renuncia es lo que la nulidad absoluta no tolera: protege el <b>interés general</b>, no uno disponible por la sola voluntad de las partes.',
  'IV.B.2.5'),
 ('T21.08', 'Regla', 'basica', '¿En qué plazo se sanea la nulidad absoluta por el tiempo y desde cuándo se cuenta?',
  'En <b>diez años</b> (' + A(1683) + '), contados desde la <b>celebración</b> del acto nulo, momento desde el cual ya era posible ejercer la acción. Superado ese plazo, ni la acción ni la excepción de nulidad proceden, porque en algún momento hay que consolidar los derechos adquiridos.',
  'IV.B.2.6'),
 ('T21.08', 'Regla', 'avanzada', 'Según BARAONA, ¿es un verdadero saneamiento el que produce el paso de diez años en la nulidad absoluta? ¿Qué efecto tiene?',
  'No: el paso del tiempo no puede volver válido lo que nunca lo fue. Para <b>BARAONA</b> es una <b>caducidad de derechos</b> de quienes podían impugnar el acto (juez, partes, terceros interesados y ministerio público). Su efecto es consolidar los desplazamientos patrimoniales: el acto pasa de título injusto a <b>título justo</b> y permite la prescripción adquisitiva. Por eso el ' + A(705) + ' habla de validar el título "por otro medio legal".',
  'IV.B.2.6'),
 ('T21.08', 'Regla', 'intermedia', '¿Opera de pleno derecho la nulidad absoluta según la doctrina tradicional? ¿En qué normas se apoya?',
  '<b>No</b>: necesita ser declarada por el juez, y mientras no haya sentencia el acto sigue produciendo todos sus efectos. Lo deduce de las normas que hablan de la nulidad judicialmente declarada o pronunciada (' + AS('1683, 1687 y 1689') + ' y art. 37 de la Ley de Matrimonio Civil).',
  'IV.B.2.7'),
 # T21.09 Nulidad relativa: definición, fundamento, causales y características
 ('T21.09', 'Concepto', 'basica', '¿Qué es la nulidad relativa y cuál es su fundamento?',
  'Es la sanción legal que recae sobre los actos a los que falta un requisito exigido <b>en consideración a la calidad o estado de las partes</b> (' + A(1681) + '). No mira al interés general: busca amparar a <b>personas determinadas</b>, en cuyo beneficio el legislador la estableció.',
  'IV.B.3.1'),
 ('T21.09', 'Enumeración', 'basica', '¿En qué casos hay nulidad relativa?',
  '(i) Actos de los <b>relativamente incapaces</b>; (ii) <b>error sustancial</b>; (iii) error en la <b>calidad accidental</b>, si fue el principal motivo de una parte y la otra lo conocía; (iv) <b>error en la persona</b>, cuando es relevante; (v) <b>fuerza</b> grave, injusta y determinante; (vi) <b>dolo determinante</b> (en los actos bilaterales, obra de una de las partes); (vii) omisión de formalidades exigidas en consideración al <b>estado o calidad de las personas</b>; y (viii) la <b>lesión</b>, en los casos en que la ley la sanciona con rescisión.',
  'IV.B.3.2'),
 ('T21.09', 'Enumeración', 'basica', '¿Qué tres características tiene la nulidad relativa y de dónde provienen?',
  '(i) Solo pueden alegarla aquellos en cuyo beneficio la han establecido las leyes; (ii) puede sanearse por el <b>transcurso del tiempo</b>; y (iii) puede sanearse por la <b>ratificación</b> de las partes. Todas provienen de lo mismo: protege a <b>personas determinadas</b>, no a la colectividad.',
  'IV.B.3.3'),
 # T21.10 Nulidad relativa: quiénes pueden alegarla
 ('T21.10', 'Enumeración', 'basica', '¿Quiénes pueden alegar la nulidad relativa?',
  'Según el ' + A(1684) + ': (i) <b>el beneficiado</b>, quien sufrió el vicio (la parte que padeció el error, la fuerza o el dolo, o el incapaz, nunca su contraparte); (ii) sus <b>herederos</b>, que le suceden en el derecho a pedir la rescisión; y (iii) sus <b>cesionarios</b>, cuando el beneficiado cede por acto entre vivos los derechos que emanan del acto nulo. No puede declararla el juez de oficio ni pedirla el ministerio público en el solo interés de la ley.',
  'IV.B.3.4.1'),
 ('T21.10', 'Distinción', 'intermedia', 'El incapaz relativo que contrata, ¿pierde el derecho a alegar la nulidad por haber dicho que era mayor de edad? ¿Y si usó dolo?',
  'Hay que distinguir (' + A(1685) + '). La <b>simple aserción</b> de mayor edad, o de no existir interdicción u otra incapacidad, <b>no</b> lo inhabilita: fue negligente el otro contratante, que se conformó con su palabra. Si hubo <b>dolo</b> del incapaz para inducir el acto, <b>ni él ni sus herederos o cesionarios</b> pueden alegar la nulidad, porque ya no hay negligencia que reprochar al otro, que no está obligado a presumir la mala fe ajena.',
  'IV.B.3.4.2'),
 ('T21.10', 'Regla', 'intermedia', 'En un contrato celebrado con error, ¿puede pedir la rescisión la parte que no sufrió el vicio?',
  '<b>No.</b> La nulidad relativa solo puede alegarse por aquellos en cuyo beneficio la han establecido las leyes, o por sus herederos o cesionarios (' + A(1684) + '): si hubo error, fuerza o dolo, solo la <b>parte afectada</b>; si contrató un incapaz, el derecho es del <b>incapaz</b>, no de su contraparte.',
  'IV.B.3.4.1'),
 # T21.11 Nulidad relativa: saneamiento por el transcurso del tiempo
 ('T21.11', 'Regla', 'basica', '¿En qué plazo se sanea por el tiempo la nulidad relativa y desde cuándo se cuenta en cada caso?',
  'En <b>cuatro años</b> (' + A(1691) + '). Se cuentan: en caso de <b>fuerza</b>, desde el día en que cesó; en caso de <b>error o dolo</b>, desde la celebración del acto o contrato; si la nulidad proviene de una <b>incapacidad legal</b>, desde que cesó la incapacidad. Todo ello salvo que leyes especiales fijen otro plazo.',
  'IV.B.3.5'),
 ('T21.11', 'Regla', 'intermedia', '¿Qué efecto tiene que transcurra el cuadrienio sin que se alegue la nulidad relativa?',
  'El vicio se extingue y el acto <b>queda sano</b>, como si nunca hubiera adolecido de un defecto (' + AS('1684 y 1691') + ').',
  'IV.B.3.5'),
 ('T21.11', 'Regla', 'avanzada', 'Si muere quien podía pedir la rescisión, ¿cómo corre el plazo para sus herederos?',
  'Distingue el ' + A(1692) + ' según su edad. Herederos <b>mayores</b>: el plazo no se suspende; gozan del cuadrienio entero si no había empezado a correr, o del residuo. Herederos <b>menores</b>: el cuadrienio o su residuo corre desde que llegan a la <b>mayoría de edad</b>, con un tope de <b>diez años</b> desde la celebración del acto o contrato.',
  'IV.B.3.5'),
 ('T21.11', 'Distinción', 'basica', 'Compara los plazos para alegar la nulidad absoluta y la relativa.',
  '<b>Absoluta</b>: diez años desde la celebración (' + A(1683) + '). <b>Relativa</b>: cuatro años, desde la celebración si hubo error o dolo, y desde que cesa la fuerza o la incapacidad (' + A(1691) + '). <b>Herederos menores</b> del que podía pedir la rescisión: desde su mayoría de edad, con tope de diez años desde la celebración (' + A(1692) + ').',
  'IV.B.3.5'),
]
