# Flashcards de Acto Jurídico: lote 2 (2026-10-07).
# (subtema, tipo, dificultad, pregunta, respuesta, respaldo en el manual)
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'

NO_CONFUNDIR = [
 ('T01.3', 'No confundir', 'intermedia', '¿Se distingue en Chile el negocio jurídico del acto jurídico?',
  'No. Parte de la doctrina comparada (sobre todo la alemana y la italiana) los separa: en el <b>negocio jurídico</b> los efectos son exactamente los queridos por su autor; en el <b>acto jurídico en sentido estricto</b> los efectos no siempre coinciden con lo querido (quien construye, sin saberlo, en terreno ajeno). En Chile esa distinción no existe: ambos términos se usan como <b>sinónimos</b>.',
  'I.3, No confundir 1'),
 ('T05.01', 'No confundir', 'intermedia', '¿En qué se diferencia la clasificación del acto en unilateral o bilateral de la clasificación del contrato en unilateral o bilateral?',
  'La del acto mira <b>cuántas partes se necesitan para que el acto exista</b>. La del contrato (' + A(1439) + ') mira <b>cuántas partes de un contrato ya bilateral quedan obligadas</b>: solo una (unilateral) o ambas recíprocamente (bilateral). Número de partes versus número de obligados.',
  'I.8.1, No confundir 2'),
 ('T06.3', 'No confundir', 'basica', '¿Vale en derecho la regla de que "el que calla otorga"?',
  'No. El silencio, por sí solo, no significa nada: ni acepta ni rechaza, y no se puede dar por aceptada una propuesta porque el destinatario no respondió. Solo vale como manifestación de voluntad en tres excepciones: cuando se lo atribuye <b>la ley</b> (' + AS('2125 y 1233') + '), <b>las partes</b> de común acuerdo, o <b>el juez</b> (silencio circunstanciado).',
  'II.A.2.2 (iii), No confundir 3 y letras a) a c)'),
 ('T07.2', 'No confundir', 'intermedia', '¿Obliga igual la oferta a persona indeterminada que la oferta contenida en anuncios impresos?',
  'No. La oferta a persona indeterminada, por regla general, <b>obliga</b>: quien la acepta puede exigir el cumplimiento (el comercio que exhibe productos con precio). La contenida en <b>anuncios impresos</b> (circulares, catálogos, prospectos) <b>no obliga</b> a quien la hace (' + A('105 inc. 1° C. de Comercio') + '), salvo en los actos regidos por la Ley del Consumidor (' + A('12 Ley Nº 19.496') + '), según quienes la entienden derogada en ese ámbito.',
  'II.A.3.2 (i) c.4), No confundir 4'),
 ('T07.2', 'No confundir', 'intermedia', 'Si el oferente se retracta tempestivamente, ¿queda libre de toda consecuencia?',
  'No. La retractación tempestiva impide que se forme el contrato, pero el oferente debe <b>indemnizar los gastos y los daños y perjuicios</b> del destinatario (' + A('100 C. de Comercio') + '), salvo que opte por <b>cumplir el contrato propuesto</b>.',
  'II.A.3.2 (ii) d.3), No confundir 5'),
 ('T07.6', 'No confundir', 'intermedia', '¿Qué diferencia al llamado a licitación de la oferta a persona indeterminada?',
  'Ambos se dirigen al público, pero la oferta a persona indeterminada es una <b>verdadera oferta</b> y, por regla general, obliga: basta que alguien la acepte para que haya contrato. El llamado a licitación es solo una <b>invitación a ofertar</b>: quienes responden son los oferentes, y el licitante queda libre hasta que <b>adjudica</b>.',
  'II.A.3.3 (i), No confundir 6'),
 ('T07.4', 'No confundir', 'intermedia', 'En un contrato celebrado por internet entre personas que residen en lugares distintos, ¿dónde se entiende celebrado?',
  'En el lugar de <b>residencia del aceptante</b> (' + A('104 C. de Comercio') + '). No importa dónde estaba el computador o el celular desde el que hizo clic, ni dónde está el servidor del sitio.',
  'II.A.3.3 (iv) d), No confundir 7'),
 ('T09.1', 'No confundir', 'intermedia', '¿Tienen el mismo efecto jurídico el error, la ignorancia y la duda?',
  'El <b>error y la ignorancia</b> sí: ambos son una falsa representación de la realidad y la ley los trata igual. La <b>duda</b> no: quien duda sabe que puede estar equivocado y asume el riesgo, por lo que después no puede alegar error. Excepción: la <b>duda objetiva</b>, propia de ciertos negocios (por ejemplo, la autoría de una obra de arte), que no excluye el error.',
  'II.A.5.1 (i) y (ii), No confundir 8'),
 ('T09.2', 'No confundir', 'avanzada', '¿Permiten los ' + AS('2297 y 2299') + ' pedir la nulidad de un contrato por error de derecho?',
  'No. Es un error típico de examen. Esos artículos permiten <b>repetir lo pagado</b> sin fundamento (pago de lo no debido), no anular un contrato. Fuera del pago de lo no debido, el ' + A(1452) + ' (el error de derecho no vicia el consentimiento) se aplica sin excepciones.',
  'II.A.5.2 (i), No confundir 9'),
 ('T09.6', 'No confundir', 'avanzada', '¿Qué diferencia al error sobre la calidad esencial del error sobre una calidad accidental elevada a esencial?',
  'En la <b>calidad esencial</b> (' + A('1454 inc. 1°') + ') el error vicia aunque la otra parte no supiera nada: basta que una sola parte yerre. En la <b>calidad accidental</b> (' + A('1454 inc. 2°') + ') se requiere además que haya sido el <b>principal motivo</b> de quien yerra y que ese motivo haya sido <b>conocido</b> por la otra parte. Conocer el motivo no es compartir el error.',
  'II.A.5.3 (iii), No confundir 10'),
 ('T11.3', 'No confundir', 'intermedia', '¿Tienen el mismo efecto el dolo y la fuerza cuando provienen de un tercero?',
  'No. El <b>dolo</b> de un tercero no anula un acto bilateral: solo da acción de perjuicios (' + A(1458) + '). La <b>fuerza</b> de un tercero sí lo anula (' + A(1457) + '). Además, el plazo de rescisión corre, en el dolo, desde la <b>celebración</b> del acto; en la fuerza, desde que <b>cesó la violencia</b> (' + A('1691 inc. 2°') + ').',
  'II.A.7.4, No confundir 11'),
 ('T13.3', 'No confundir', 'intermedia', '¿Necesitan el demente y el disipador estar en interdicción para ser incapaces?',
  'El <b>demente</b> es incapaz aunque nadie lo haya declarado en interdicción: la interdicción solo decide quién debe probar qué (' + A(465) + '). El <b>disipador</b>, en cambio, solo es incapaz si está bajo interdicción (' + A('1447 inc. 3°') + '): sin decreto judicial es plenamente capaz.',
  'II.B.3.2, No confundir 12'),
 ('T15.4', 'No confundir', 'avanzada', '¿Es lo mismo enajenar una especie cuya propiedad se litiga que ceder un derecho litigioso?',
  'No. Enajenar una <b>especie litigiosa</b> es traspasar la cosa misma que se disputa en el juicio, y sin permiso del juez tiene objeto ilícito (' + A('1464 Nº 4') + '). Ceder un <b>derecho litigioso</b> es traspasar el evento incierto de la litis; es válido, el cedente no responde del resultado y se regula en los ' + AS('1911 y siguientes') + '.',
  'II.C.4.3, No confundir 13'),
 ('T16.7', 'No confundir', 'avanzada', '¿Qué diferencia al error-motivo del error sobre los motivos?',
  'En el <b>error-motivo</b> la persona se equivoca sobre la sustancia o calidad de la cosa o sobre la otra parte, y ese dato la lleva a contratar: vicia el consentimiento si se cumplen los ' + AS('1454 y 1455') + '. En el <b>error sobre los motivos</b> la equivocación está en las razones personales, ajenas a la estructura del acto: por regla general no afecta su validez.',
  'II.D.8, No confundir 14'),
 ('T17.4', 'No confundir', 'intermedia', '¿Qué diferencia a una solemnidad de una formalidad de prueba, si ambas pueden consistir en un escrito?',
  'La <b>solemnidad</b> (<i>ad solemnitatem</i>) es la forma en que la voluntad debe manifestarse: sin ella el acto es inexistente o nulo, y ninguna otra prueba la suple (' + A(1701) + '). La <b>formalidad de prueba</b> (<i>ad probationem</i>) solo sirve para acreditar el acto: si falta, el acto vale, pero no puede probarse por testigos (' + AS('1708 y 1709') + ').',
  'II.E.2.3, No confundir 15'),
 ('T18.2', 'No confundir', 'intermedia', '¿Qué diferencia a un tercero absoluto de un tercero relativo?',
  'Ambos son ajenos a la formación del acto. El <b>tercero absoluto</b> no tiene ni tendrá vínculo jurídico con las partes, y el acto no le produce efectos. El <b>tercero relativo</b> sí lo tiene o lo tendrá, por su voluntad o por la ley, y el acto puede alcanzarlo (el heredero, quien adquiere un bien hipotecado, el acreedor). Las excepciones al efecto relativo se refieren a los terceros absolutos.',
  'III.2.2, No confundir 16'),
 ('T20.3', 'No confundir', 'avanzada', '¿Es lo mismo la nulidad de pleno derecho de la Ley Nº 19.499 que la nulidad del Código Civil?',
  'No. La de la <b>Ley Nº 19.499</b> opera <b>sin sentencia judicial</b>: la sociedad se mira como si nunca hubiera existido y no puede sanearse. La del <b>Código Civil</b> nunca opera ipso iure: mientras no se declara, el acto produce sus efectos y puede sanearse. Criterio: si necesita o no una sentencia que la declare.',
  'IV.A.4.1, No confundir 17'),
 ('T20.3', 'No confundir', 'avanzada', '¿Es la inexistencia imprescriptible e insaneable en Chile, como en la doctrina francesa?',
  'No, según la lectura que se apoya en la historia fidedigna del ' + A(1683) + ': el codificador se apartó conscientemente del modelo francés, y en Chile ni la inexistencia ni la nulidad absoluta pueden alegarse transcurridos <b>diez años</b>.',
  'IV.A.4.3, No confundir 18'),
 ('T21.05', 'No confundir', 'avanzada', '¿Arrastra la nulidad de una escritura pública a todos los actos que contiene?',
  'Depende de qué esté viciado. En la <b>nulidad refleja</b> el vicio está en la forma de un acto solemne: la escritura nula arrastra al acto que ella misma constituye. Si la escritura contiene <b>varios actos independientes</b> y uno es nulo, los demás siguen valiendo. Criterio: si la escritura es la forma exigida para el acto o solo el documento donde constan actos distintos.',
  'IV.B.1.9, No confundir 19'),
 ('T22.1', 'No confundir', 'intermedia', '¿Es lo mismo ratificar que confirmar?',
  'No siempre. <b>Confirmar</b> es sanear un acto nulo relativamente renunciando a pedir su nulidad. <b>Ratificar</b>, en sentido estricto, es hacer propio lo que otro ejecutó a nuestro nombre sin poder, como el mandante que ratifica lo obrado por el mandatario (' + A(2160) + '). El Código usa "ratificación" para ambos. Criterio: si se sanea un vicio del acto o se asume un acto ajeno.',
  'IV.B.3.6.1, No confundir 20'),
 ('T23.3', 'No confundir', 'avanzada', 'Según VIAL, ¿es el ' + A(1444) + ' (contrato que "degenera en otro") un caso de conversión del acto nulo?',
  'No. Para <b>VIAL</b> es más bien un problema de <b>error</b>, generalmente de derecho, en la calificación del acto: el contrato que las partes llaman compraventa y que para la ley es una permuta es <b>desde el primer momento una permuta</b>, sin vicio alguno. No hay una compraventa nula que se convierta en otro contrato.',
  'IV.B.4.5, No confundir 21'),
 ('T23.3', 'No confundir', 'avanzada', 'Si un testamento abierto falla por una solemnidad, pero cumple los requisitos de una forma menos exigente, ¿hay conversión?',
  'No, según <b>COVIELLO</b>: el negocio que se hace valer y el querido por las partes es idéntico; el acto sigue siendo un testamento, solo que de una especie menos solemne. La conversión verdadera exige que el acto <b>cambie de naturaleza</b>, como la letra de cambio que pasa a valer como reconocimiento de deuda.',
  'IV.B.4.5, No confundir 22'),
 ('T28.2', 'No confundir', 'avanzada', '¿Es la representación de la esencia del mandato?',
  'No. Es de su <b>naturaleza</b>: el mandatario puede contratar a su propio nombre aunque actúe en interés del mandante (' + A(2151) + '). Si obra a nombre propio, no obliga al mandante frente a terceros: frente a ellos queda como titular de los derechos que nacen del acto; frente al mandante sigue siendo su mandatario. Representar exige obrar a nombre del mandante (' + A(1448) + ').',
  'V.3.3, No confundir 23'),
]

NUEVAS = [
 # T01 Concepto
 ('T01.1', 'Concepto', 'intermedia', '¿Tiene el Código Civil chileno una regulación general del acto jurídico? ¿De qué normas se construye la teoría?',
  'No. Es una <b>construcción doctrinal</b>, inspirada en la doctrina francesa e italiana, que se apoya en el título De los actos y declaraciones de voluntad (' + AS('1445 a 1469') + ') y en el de la nulidad y rescisión (' + AS('1681 a 1697') + '). Esas normas rigen a todo acto jurídico, salvo que su texto o la naturaleza de las cosas las limite a las convenciones o los contratos.',
  'I.2'),
 # T04 Requisitos
 ('T04.1', 'Distinción', 'intermedia', 'Para la doctrina que distingue requisitos de existencia y de validez, ¿cuál es la diferencia práctica entre faltar uno u otro?',
  'Si falta un requisito de <b>existencia</b>, el acto no nace a la vida del derecho y no produce ningún efecto (es <b>inexistente</b>). Si falta uno de <b>validez</b>, el acto nace, pero viciado, expuesto a que se declare su <b>nulidad</b>. En palabras del manual: sin el primero el acto no vive; sin el segundo, vive pero corre el riesgo de morir.',
  'I.7.1'),
 ('T04.2', 'Concepto', 'avanzada', '¿Cuál es el argumento de la doctrina que sostiene que el Código solo establece requisitos de eficacia?',
  'Que el Código <b>nunca habla de existencia</b>. El ' + A(1444) + ' dice que, si falta un elemento esencial, el acto no produce efecto alguno o degenera en otro: eso describe <b>ineficacia</b>. El ' + A(1445) + ' tampoco distingue existencia y validez. Por eso todos los requisitos son de eficacia y su ausencia se sanciona siempre con <b>nulidad</b>, absoluta o relativa, nunca con inexistencia.',
  'I.7.2'),
 ('T04.2', 'Regla', 'intermedia', '¿Cómo se responde la pregunta de cédula "¿qué ocurre si a un acto jurídico le falta un requisito?"',
  'Exponiendo las dos tesis. Para la que distingue existencia y validez: sin voluntad, objeto, causa o solemnidades de existencia, el acto es <b>inexistente</b>; si falta uno de validez, nace viciado de <b>nulidad</b>. Para la que solo reconoce requisitos de eficacia: cualquier requisito que falte se sanciona con <b>nulidad absoluta o relativa</b> según el caso.',
  'I.7.2, párrafo final'),
 # T05 Clasificaciones
 ('T05.03', 'Distinción', 'basica', '¿Cuándo un acto es oneroso y, dentro de los onerosos, cuándo es conmutativo y cuándo aleatorio?',
  'Es <b>oneroso</b> el que beneficia a ambas partes, gravándose cada una en favor de la otra (' + A(1440) + '). Es <b>conmutativo</b> si la ventaja de cada parte se mira como equivalente a lo que entrega (compraventa, arrendamiento), y <b>aleatorio</b> si el equivalente depende de un hecho incierto (renta vitalicia). El <b>gratuito</b> solo beneficia a una parte.',
  'I.8.3'),
 ('T05.04', 'Distinción', 'basica', '¿Qué diferencia a un acto de administración de uno de disposición, y por qué importa la distinción?',
  'El de <b>disposición</b> disminuye el patrimonio; el de <b>administración</b> lo conserva. Importa sobre todo para quienes actúan por cuenta de otro: el tutor o curador puede y debe administrar los bienes del pupilo (' + A(391) + '), pero necesita <b>autorización judicial</b> para enajenarlos o gravarlos con hipoteca, censo o servidumbre (' + A(393) + ').',
  'I.8.4'),
 ('T05.05', 'Distinción', 'basica', '¿Cuándo un acto es entre vivos y cuándo por causa de muerte?',
  'Es <b>entre vivos</b> si no necesita de la muerte de su autor o de una de las partes para producir sus efectos. Es <b>por causa de muerte</b> (mortis causa) si sí la necesita: el testamento (' + A(999) + ') o un mandato pensado para ejecutarse después de la muerte del mandante.',
  'I.8.5'),
 ('T05.06', 'Regla', 'intermedia', '¿Qué ocurre si las partes omiten una solemnidad legal y qué si omiten una solemnidad voluntaria?',
  'Si la solemnidad es <b>legal</b> y se exigía para la validez, el acto es nulo absolutamente (' + A(1682) + '); si se exigía para la existencia, es inexistente o nulo absolutamente, según la postura sobre la inexistencia. Si es <b>voluntaria</b> (pactada por las partes, como en la compraventa de muebles, ' + A(1802) + '), el acto puede producir efectos si las partes actúan de un modo que implique renunciar a ella.',
  'I.8.6'),
 ('T05.08', 'Distinción', 'basica', '¿Qué es un acto puro y simple y qué es un acto sujeto a modalidad? ¿Cuáles son las modalidades?',
  'Es <b>puro y simple</b> el acto cuyos efectos nacen de inmediato y duran indefinidamente. Es <b>sujeto a modalidad</b> el que tiene una cláusula que retrasa, modifica o extingue sus efectos. Las modalidades más conocidas son la <b>condición, el plazo y el modo</b>; la doctrina también trata como modalidades la representación y la solidaridad.',
  'I.8.8'),
 ('T05.10', 'Distinción', 'intermedia', '¿Qué tipos de actos accesorios distingue la doctrina y cuál es la utilidad práctica de la clasificación?',
  'Los <b>de garantía</b> o cauciones (' + A(46) + '), que aseguran una obligación principal (fianza, hipoteca, prenda), y los <b>dependientes</b>, subordinados a otro acto sin función de garantía (capitulaciones matrimoniales, ' + A(1716) + '). La utilidad aparece en la extinción: <b>lo accesorio sigue la suerte de lo principal</b>, pero no al revés.',
  'I.8.10'),
 ('T05.13', 'Concepto', 'intermedia', '¿Qué es un acto atípico o innominado y es válido?',
  'Es el que la ley no reguló y surge de la creatividad de los particulares cuando ningún acto típico satisface lo que necesitan. Es válido mientras se ajuste a las normas generales sobre actos y declaraciones de voluntad, al orden público y a las buenas costumbres, en aplicación de la <b>autonomía de la voluntad</b>. Puede volverse típico si el legislador lo regula (leasing habitacional).',
  'I.8.13'),
 # T06 Voluntad
 ('T06.1', 'Concepto', 'basica', '¿Qué requisitos exige el Derecho a la voluntad para tomarla en cuenta? ¿Cuándo es seria?',
  'Dos: que sea <b>seria</b> y que se <b>manifieste</b> o exteriorice. Es seria cuando quien la emite busca producir efectos jurídicos. Falta en la voluntad expresada por cortesía, en broma o con otra intención parecida; si la hay o no, lo decide el juez en cada caso.',
  'II.A.2 y 2.1'),
 ('T06.2', 'Distinción', 'basica', '¿Qué diferencia a la manifestación de voluntad expresa de la tácita?',
  'La <b>expresa</b> usa, consciente y deliberadamente, un medio destinado a dar a conocer lo que se quiere (palabras, gestos). La <b>tácita</b> se deduce de la conducta, a partir de un hecho positivo <b>concluyente e inequívoco</b> (quien en la feria entrega la malla de paltas para que se la pesen y saca la billetera).',
  'II.A.2.2 (i) y (ii)'),
 ('T06.2', 'Regla', 'intermedia', '¿Valen lo mismo la manifestación expresa y la tácita? ¿Hay excepciones?',
  'Por regla general, sí (' + AS('1241 y 2124') + '; ' + A('103 C. de Comercio') + '). Debe ser <b>expresa</b> cuando la ley lo exige, como en el testamento (' + AS('1060 y 1023') + ') y la solidaridad (' + A('1511 inc. 3°') + '), o cuando las partes lo pactan.',
  'II.A.2.2 (ii), recuadro No olvidar'),
 ('T06.3', 'Regla', 'intermedia', '¿En qué casos le da la ley al silencio valor de manifestación de voluntad? Dé dos ejemplos.',
  'El de quienes por su <b>profesión u oficio</b> se encargan de negocios ajenos: transcurrido un término razonable, su silencio frente al encargo de una persona ausente se mira como <b>aceptación</b> (' + A(2125) + '). Y, en sentido inverso, el del asignatario constituido en mora de declarar si acepta o repudia la herencia: se entiende que <b>repudia</b> (' + A(1233) + ').',
  'II.A.2.2 (iii) a)'),
 # T07 Formación del consentimiento
 ('T07.1', 'Regla', 'intermedia', '¿Dónde se regula la formación del consentimiento y por qué esas normas se aplican también en materia civil?',
  'En el <b>Código de Comercio</b> (' + AS('97 a 108') + '); el Código Civil solo fija las cualidades del consentimiento. Se aplican en materia civil porque el alcance de una norma depende de su naturaleza y no del código en que está, y estas reglas son generales. El Mensaje del Código de Comercio dice que venía a llenar un "sensible vacío de nuestra legislación comercial y civil".',
  'II.A.3.2'),
 ('T07.2', 'Concepto', 'basica', '¿Qué es la oferta y cuándo es completa?',
  'Es el acto jurídico unilateral por el cual una persona propone a otra celebrar una convención determinada. Es <b>completa</b> cuando basta que el destinatario la apruebe para que la convención se perfeccione; si omite un elemento esencial (por ejemplo, el precio), es <b>incompleta</b> y solo abre una negociación.',
  'II.A.3.2 (i) a) y b)'),
 ('T07.2', 'Regla', 'avanzada', '¿Cuándo es intempestiva la retractación del oferente y qué efecto tiene?',
  'Es intempestiva la que se hace <b>después de aceptada</b> la oferta, o antes, si el oferente se había comprometido a <b>esperar la respuesta</b> o a <b>no disponer</b> del objeto hasta cierto plazo (' + A('99 C. de Comercio') + '). No produce ningún efecto: la oferta sigue en pie y, si la aceptación llega a tiempo, el contrato se forma y el proponente debe cumplirlo.',
  'II.A.3.2 (ii) d.3)'),
 ('T07.3', 'Enumeración', 'intermedia', '¿Qué requisitos debe reunir la aceptación para que se forme el consentimiento?',
  'Tres: (i) ser <b>pura y simple</b> (' + A('101 C. de Comercio') + '; la condicional vale como contraoferta, ' + A('102') + '); (ii) darse <b>oportunamente</b>, dentro del plazo fijado por el oferente o del legal; y (iii) darse <b>mientras la oferta esté vigente</b>, antes de la retractación, muerte o incapacidad legal sobreviniente del proponente.',
  'II.A.3.2 (ii) d)'),
 ('T07.3', 'Regla', 'basica', '¿En qué plazo debe aceptarse la oferta verbal y la escrita?',
  'La <b>verbal</b>, en el acto de ser conocida (' + A('97 C. de Comercio') + '). La <b>escrita</b>, dentro de <b>24 horas</b> si el destinatario reside en el mismo lugar que el proponente, o <b>a vuelta de correo</b> si reside en otro (' + A('98') + '). Vencido el plazo, la propuesta se tiene por no hecha, aunque se haya aceptado.',
  'II.A.3.2 (ii) d.2), recuadro No olvidar'),
 ('T07.4', 'Regla', 'intermedia', '¿Qué teoría sigue el derecho chileno sobre el momento en que se forma el consentimiento y cuáles son sus excepciones?',
  'La teoría de la <b>declaración</b>: el contrato queda perfecto cuando se acepta la oferta, aunque el proponente no lo sepa (' + AS('99 y 101 C. de Comercio') + '). Excepciones: lo que <b>pacten las partes</b> (la regla no es de orden público) y la <b>donación entre vivos</b>, que sigue la teoría del conocimiento (' + A(1412) + ').',
  'II.A.3.2 (iii) b)'),
 ('T07.5', 'Enumeración', 'avanzada', 'Según ROSENDE, ¿qué requisitos deben concurrir para que nazca responsabilidad precontractual en las negociaciones preliminares?',
  'Tres: (a) que haya <b>consentimiento en las tratativas</b>, es decir, acuerdo en negociar; (b) que una de las partes haya hecho <b>gastos</b> con miras al contrato; y (c) que una de las partes se <b>retire unilateralmente</b> de las negociaciones en forma contraria a la buena fe.',
  'II.A.3.2 (v)'),
 ('T07.6', 'Regla', 'intermedia', '¿Son verdaderos contratos los contratos de adhesión? ¿Qué norma limita sus cláusulas abusivas?',
  'Sí, es la opinión que se ha impuesto: hay dos voluntades libres de vicios que se encuentran sobre un objeto, y la forma en que se fijaron las cláusulas no cambia eso. El ' + A('16 de la Ley Nº 19.496') + ' declara que ciertas cláusulas abusivas "no producirán efecto alguno" en estos contratos.',
  'II.A.3.3 (ii)'),
 ('T07.6', 'Regla', 'avanzada', '¿Admite el Código Civil el autocontrato?',
  'No tiene una regla general: hay normas dispersas que, según el caso, lo <b>admiten</b> (mandatario, ' + AS('2144 y 2145') + ', a veces con aprobación del mandante), lo sujetan a <b>autorización</b> (' + AS('410 y 412 inc. 1°') + ') o lo <b>prohíben</b> (el tutor o curador no puede comprar ni arrendar bienes raíces del pupilo, ' + A('412 inc. 2°') + '). Lo hace posible la representación.',
  'II.A.3.3 (iii)'),
 # T08 Vicios en general
 ('T08.1', 'Enumeración', 'basica', '¿Cuáles son los vicios del consentimiento según el Código?',
  'El <b>error</b>, la <b>fuerza</b> y el <b>dolo</b> (' + A(1451) + '). Algunos agregan la lesión en ciertos casos, cuestión discutida; <b>COVIELLO</b> los reduce a dos, el error y el temor, porque el dolo opera provocando un error.',
  'II.A.4'),
 ('T08.1', 'Distinción', 'intermedia', '¿Es lo mismo que falte la voluntad que el que esté viciada?',
  'Para quienes distinguen requisitos de existencia y de validez, no: si <b>no hubo voluntad</b>, el acto no existe; si la hubo pero <b>viciada</b>, existe y puede anularse (lo leen en el ' + A('1445 Nº 2') + ', que pide primero que la persona consienta y luego que su consentimiento no adolezca de vicio). Para otro sector, ambos casos conducen a la nulidad.',
  'II.A.4'),
 # T09 Error
 ('T09.1', 'Concepto', 'basica', '¿Qué es el error y qué es el error de previsión? ¿Vicia este último el consentimiento?',
  'El error es una falsa representación de la realidad: tener por verdadero lo falso, o por falso lo verdadero. El <b>error de previsión</b> es equivocarse sobre lo que <b>va a pasar</b>; como lo futuro no forma parte de la realidad, <b>no vicia</b> el consentimiento (quien compra un negocio creyendo que venderá mucho y no vende).',
  'II.A.5.1 y (iii)'),
 ('T09.2', 'Regla', 'basica', '¿Vicia el consentimiento el error de derecho? ¿En qué se funda la regla?',
  'No: "el error sobre un punto de derecho no vicia el consentimiento" (' + A(1452) + '). Se funda en la ficción de que todos conocen la ley: "nadie podrá alegar ignorancia de la ley después que ésta haya entrado en vigencia" (' + A(8) + ').',
  'II.A.5.2 (i)'),
 ('T09.2', 'Distinción', 'avanzada', '¿Son los ' + AS('2297 y 2299') + ' verdaderas excepciones al ' + A(1452) + '?',
  'Tradicionalmente se citan así, pero en rigor operan en otro ámbito: el ' + A(1452) + ' mira a la <b>validez del acto</b> (vicios del consentimiento) y los ' + AS('2297 y 2299') + ' al <b>pago de lo no debido</b>, para decidir si quien recibió puede retener lo pagado. Para <b>LEÓN HURTADO</b> sí son excepción, de interpretación restrictiva; para <b>VIAL</b>, son excepción a la irrelevancia del error de derecho, no a la regla de que no vicia el consentimiento.',
  'II.A.5.2 (i) c)'),
 ('T09.3', 'Distinción', 'intermedia', '¿Qué diferencia al error obstáculo del error vicio? ¿Recoge el Código esa distinción?',
  'En el <b>error vicio</b> hay acuerdo, pero formado sobre un falso concepto. En el <b>error obstáculo</b> cada parte quiere algo distinto (una entiende préstamo y la otra donación): no vicia el consentimiento, <b>impide que se forme</b>. El Código <b>no recoge</b> la distinción: el ' + A(1453) + ' dice que el error esencial "vicia el consentimiento".',
  'II.A.5.2 (ii) a) y c)'),
 ('T09.3', 'Distinción', 'avanzada', '¿Sigue el Código un criterio objetivo o subjetivo para determinar qué errores de hecho son relevantes?',
  'A primera vista, <b>objetivo</b>: solo son relevantes los errores descritos en los ' + AS('1453 a 1455') + '. Pero <b>VIAL</b> sostiene que además exige que el error haya sido <b>determinante</b>: lo da por supuesto en el ' + A('1454 inc. 1°') + ' y lo dice en el inc. 2° ("el principal motivo") y en el ' + A(1455) + ' ("la causa principal del contrato").',
  'II.A.5.2 (ii) b)'),
 ('T09.4', 'Enumeración', 'basica', '¿Sobre qué recae el error esencial u obstáculo del ' + A(1453) + '?',
  'Sobre la <b>especie de acto o contrato</b> que se celebra (una parte entiende empréstito y la otra donación), o sobre la <b>identidad de la cosa específica</b> de que se trata (el vendedor entiende vender una cosa y el comprador comprar otra).',
  'II.A.5.3 (i)'),
 ('T09.4', 'Distinción', 'avanzada', '¿Cuál es la sanción del error esencial? Mencione las tres posiciones.',
  'Es discutida. (1) <b>Inexistencia</b>: si impide el acuerdo, el acto no nace. (2) <b>Nulidad absoluta</b> (<b>ALESSANDRI BESA</b>; Corte Suprema, Torres con Fisco, 1945): es la sanción más grave que la ley sí contempla. (3) <b>Nulidad relativa</b> (<b>LEÓN HURTADO</b>): el ' + A(1453) + ' dice que "vicia el consentimiento", y todo vicio no sancionado con nulidad absoluta produce nulidad relativa (' + A('1682 inc. final') + ').',
  'II.A.5.3 (i) c)'),
 ('T09.5', 'Distinción', 'avanzada', '¿Son sinónimos "sustancia" y "calidad esencial" en el ' + A('1454 inc. 1°') + '?',
  'Discutido. Para un sector, sí (el artículo las une con "o"). Para <b>VIAL</b>, no: la sustancia es la materia de la cosa, apreciada objetivamente, y la calidad esencial es subjetiva, la cualidad por la cual se contrata. Para <b>BOETSCH</b>, tampoco: la sustancia es la composición material y la calidad esencial, las características inmateriales (autoría de una obra, situación jurídica de un bien).',
  'II.A.5.3 (ii) a)'),
 ('T09.5', 'Regla', 'intermedia', 'En el error sustancial, ¿debe quien lo alega probar que la materia de la cosa le era relevante?',
  'No. Para <b>VIAL</b> el artículo contiene una <b>presunción simplemente legal</b> de que la materia fue lo que llevó a contratar: basta probar que la materia era distinta. La otra parte puede destruir la presunción probando que la materia le era indiferente a quien alega el error. La sanción es la <b>nulidad relativa</b>.',
  'II.A.5.3 (ii) b) y e)'),
 ('T09.6', 'Regla', 'intermedia', '¿Vicia el consentimiento el error sobre una calidad accidental de la cosa?',
  'Por regla general, no. Sí lo vicia si concurren dos requisitos (' + A('1454 inc. 2°') + '): que esa calidad haya sido el <b>principal motivo</b> de una de las partes para contratar, y que ese motivo haya sido <b>conocido</b> por la otra. Quien lo alega debe probar ambos. La sanción es la nulidad relativa.',
  'II.A.5.3 (iii)'),
 ('T09.7', 'Regla', 'basica', '¿Cuándo vicia el consentimiento el error en la persona y qué derecho tiene quien contrató por error?',
  'Solo cuando la consideración de esa persona es la <b>causa principal del contrato</b> (' + A(1455) + '), lo que ocurre en los actos <b>intuito personae</b>. Declarada la nulidad relativa, la persona con quien erradamente se contrató tiene derecho a ser <b>indemnizada de los perjuicios</b> en que de buena fe haya incurrido (' + A('1455 inc. 2°') + ').',
  'II.A.5.3 (iv) y d)'),
 ('T09.7', 'Enumeración', 'intermedia', '¿Qué actos son intuito personae, según las pautas de la doctrina?',
  'Los <b>actos de familia</b> (matrimonio, adopción, reconocimiento de un hijo); los <b>patrimoniales gratuitos</b> hechos en consideración a alguien (donación, depósito, comodato, mutuo sin interés); los <b>onerosos de confianza</b> (mandato, sociedad civil, arrendamiento de servicios); y los que la <b>ley</b> señala, como la transacción (' + A(2456) + ').',
  'II.A.5.3 (iv) a)'),
 ('T09.7', 'Regla', 'avanzada', '¿Qué error en la persona vicia el consentimiento matrimonial según la Ley Nº 19.947?',
  'El error acerca de la <b>identidad de la persona</b> del otro contrayente, y el error acerca de alguna de sus <b>cualidades personales</b> que, atendida la naturaleza o los fines del matrimonio, deba estimarse determinante (' + A('8 Nºs 1 y 2 Ley 19.947') + '). Recoge la tesis de LEÓN HURTADO; antes, la jurisprudencia (Butcher con Plaza, 1943) solo admitía el error en la identidad física.',
  'II.A.5.3 (iv) c)'),
 ('T09.8', 'Regla', 'intermedia', 'En un acto bilateral, ¿es necesario que ambas partes estén en error para que este vicie el consentimiento?',
  'No. Basta que yerre <b>una de las partes</b>: el ' + A(1454) + ' dice "por alguna de las partes". En el error sobre calidad accidental, la ley pide que la otra parte <b>conozca el motivo</b> de quien yerra, no que comparta el error (así lo leen LEÓN HURTADO y VIAL).',
  'II.A.5.4'),
 ('T09.8', 'Regla', 'intermedia', '¿Puede invocarse el error para anular un acto unilateral? Dé un ejemplo legal.',
  'Sí: las reglas del error no se limitan a los contratos y el error relevante puede invocarse en cualquier acto. Ejemplo: "la asignación que pareciere motivada por un error de hecho, de manera que sea claro que sin este error no hubiera tenido lugar, se tendrá por no escrita" (' + A(1058) + ').',
  'II.A.5.5'),
 ('T09.9', 'Enumeración', 'intermedia', '¿Qué es el error común y qué requisitos exige para no viciar el acto?',
  'Es el error en que todos de buena fe incurren (<b>FIGUEROA</b>); se resume en la máxima <i>error communis facit ius</i>. Requisitos: (i) que lo comparta la <b>generalidad</b> de los habitantes del lugar; (ii) que tenga un <b>justo motivo</b> (título colorado); y (iii) que quien lo invoca esté de <b>buena fe</b>. Ejemplo legal: el testigo inhábil del testamento (' + A(1013) + ').',
  'II.A.5.6'),
 # T10 Dolo
 ('T10.1', 'Enumeración', 'intermedia', '¿En qué tres ámbitos aparece el dolo en el Derecho Civil y qué función cumple en cada uno?',
  'En la <b>celebración</b> del acto, como vicio del consentimiento (' + AS('1451, 1458 y 1459') + '); en el <b>cumplimiento</b> del contrato, como agravante de la responsabilidad del deudor (' + A(1558) + '); y en la <b>responsabilidad extracontractual</b>, como elemento que convierte el hecho ilícito en delito civil. La definición legal es una sola: la intención positiva de inferir injuria (' + A(44) + ').',
  'II.A.6.1 (i)'),
 ('T10.1', 'Distinción', 'intermedia', '¿Qué tienen en común el dolo y el error, y qué los diferencia?',
  'En ambos la víctima se representa la realidad de manera <b>falsa</b>. La diferencia está en el origen: en el <b>error</b> la persona se equivoca sola; en el <b>dolo</b> alguien la hace equivocarse. El dolo exige, además, un elemento psicológico (intención de engañar) y uno material (maniobras, mentira o reticencia).',
  'II.A.6.1 (iii)'),
 ('T10.2', 'Distinción', 'basica', '¿Qué diferencia al dolo bueno del dolo malo?',
  'El <b>dolo bueno</b> no busca perjudicar: son los elogios y exageraciones con que cualquier vendedor intenta convencer. El <b>dolo malo</b> lleva la intención positiva de causar daño (' + A(44) + ') y es el único que importa como vicio de la voluntad.',
  'II.A.6.2 (i)'),
 ('T10.2', 'Concepto', 'intermedia', '¿Qué es la reticencia y cuándo vicia el consentimiento?',
  'Es la forma más importante de <b>dolo negativo</b>: guardar silencio sobre circunstancias que se tenía la obligación de dar a conocer. Vicia el consentimiento si ese silencio lleva a la otra parte a celebrar un acto que no habría celebrado, o que habría celebrado en otras condiciones. El deber de informar puede venir de la ley (' + A(1861) + ') o de las circunstancias.',
  'II.A.6.2 (ii)'),
 ('T10.2', 'Distinción', 'basica', '¿Qué diferencia al dolo principal del dolo incidental?',
  'El <b>principal</b> (determinante o inductivo) lleva a la persona a celebrar el acto: sin él, no lo habría celebrado. El <b>incidental</b> no decide la celebración, que habría ocurrido igual, pero sí sus condiciones: sin el engaño, la víctima habría contratado en términos más favorables.',
  'II.A.6.2 (iii)'),
 ('T10.3', 'Regla', 'basica', '¿Cuándo vicia el dolo el consentimiento en un acto bilateral y cuándo en uno unilateral?',
  'En los <b>bilaterales</b>, cuando es <b>obra de una de las partes</b> y además es <b>principal</b>: sin él no se habría contratado (' + A('1458 inc. 1°') + '); los requisitos son copulativos. En los <b>unilaterales</b> basta que sea <b>principal</b>, provenga de quien provenga (' + AS('968 Nº 4, 1234 y 1782') + ').',
  'II.A.6.3'),
 ('T10.4', 'Regla', 'intermedia', '¿Se presume el dolo? ¿Cómo se prueba?',
  'No: "el dolo no se presume sino en los casos especialmente previstos por la ley. En los demás debe probarse" (' + A(1459) + '), porque la ley presume la buena fe (' + A(707) + ', que se entiende regla general). Puede probarse por <b>cualquier medio</b>, sin las limitaciones a la prueba de testigos de los ' + AS('1708 y 1709') + '.',
  'II.A.6.4'),
 ('T10.4', 'Enumeración', 'avanzada', 'Mencione casos en que la ley presume el dolo o la mala fe.',
  'Entre otros: quien adquiere derechos sobre un <b>bien familiar</b> sin la voluntad del cónyuge no propietario (' + A('143 inc. 2°') + '); el <b>error de derecho</b> en la posesión (' + A('706 inc. final') + '); la <b>ocultación del testamento</b> (' + A('968 Nº 5') + '); el título de <b>mera tenencia</b> en la prescripción extraordinaria (' + A('2510 regla 3ª') + '); y el <b>albacea</b> que cumple una disposición contraria a las leyes (' + A(1301) + ').',
  'II.A.6.4 a) a g)'),
 ('T10.5', 'Regla', 'basica', '¿Puede renunciarse anticipadamente al dolo? ¿Cuándo puede perdonarse?',
  'No: "la condonación del dolo futuro no vale" (' + A(1465) + '); esa renuncia adolece de <b>objeto ilícito</b>. El dolo solo puede perdonarse <b>después de cometido y conocido</b> por la víctima, y en el pacto de no pedir más en razón de una cuenta aprobada, la condonación debe ser <b>expresa</b>.',
  'II.A.6.5'),
 ('T10.6', 'Regla', 'intermedia', '¿Qué sanción tiene el dolo que no vicia el consentimiento y contra quién se dirige la acción?',
  'Da lugar solo a la <b>acción de perjuicios</b> (' + A('1458 inc. 2°') + '): contra quienes <b>fraguaron</b> el dolo, por el total de los perjuicios, y contra quienes solo <b>se aprovecharon</b> de él, hasta concurrencia del provecho que obtuvieron. Si lo cometieron dos o más personas, responden <b>solidariamente</b> (' + A('2317 inc. 2°') + ').',
  'II.A.6.6 (ii) y (iii)'),
 ('T10.6', 'Regla', 'intermedia', '¿Quién tiene la acción rescisoria por dolo y en qué plazo prescribe?',
  'La tiene la <b>víctima</b> del engaño, como acción o como excepción; quien cometió el dolo no puede pedir la rescisión, porque nadie puede aprovecharse de su propio dolo. Prescribe en <b>cuatro años</b> contados desde la <b>celebración</b> del acto o contrato (' + A('1691 inc. 2°') + '), salvo ley especial.',
  'II.A.6.7'),
 # T11 Fuerza
 ('T11.1', 'Distinción', 'intermedia', '¿Qué diferencia a la fuerza física de la fuerza moral y cuál de ellas es vicio del consentimiento?',
  'En la <b>física</b> (material o absoluta) se fabrica una apariencia de consentimiento: no hay voluntad de la víctima, por lo que no es propiamente un vicio y, para parte de la doctrina, el acto es inexistente. En la <b>moral</b> (psíquica o compulsiva) la víctima sí manifiesta su voluntad, pero bajo la amenaza de un mal: su voluntad es consciente pero no libre. Solo la moral es vicio del consentimiento.',
  'II.A.7.2'),
 ('T11.2', 'Enumeración', 'basica', '¿Qué requisitos debe reunir la fuerza para viciar el consentimiento?',
  'Debe ser <b>grave</b> (' + A(1456) + '), <b>determinante</b>, es decir, empleada "con el objeto de obtener el consentimiento" (' + A(1457) + '), e <b>injusta</b>, requisito que agrega la doctrina aunque el Código no lo mencione.',
  'II.A.7.3'),
 ('T11.2', 'Regla', 'intermedia', '¿Cuándo es grave la fuerza y cuándo se presume que la amenaza infundió un justo temor?',
  'Es grave la capaz de producir una impresión fuerte en una persona de sano juicio, "tomando en cuenta su edad, sexo y condición" (' + A('1456 inc. 1°') + '): es un concepto <b>relativo</b> y la amenaza debe ser verosímil. Se presume justo temor cuando el mal amenaza al <b>consorte</b> o sus <b>ascendientes o descendientes</b>; si amenaza a otra persona querida, la víctima debe probarlo.',
  'II.A.7.3 (ii)'),
 ('T11.2', 'Regla', 'intermedia', '¿Es fuerza amenazar con ejercer un derecho, como demandar al deudor que no paga?',
  'No: amenazar con ejercer un derecho no es fuerza, porque el mal amenazado no es <b>injusto</b>. La doctrina moderna precisa que sí hay fuerza injusta cuando un mal lícito en sí mismo se usa para obtener una <b>ventaja desproporcionada</b> (amenazar con denunciar un delito para obtener un bien que vale el triple de la deuda).',
  'II.A.7.3 (i)'),
 ('T11.3', 'Regla', 'intermedia', '¿Por qué la fuerza vicia el consentimiento aunque la ejerza un tercero, a diferencia del dolo?',
  'Porque basta que la emplee "cualquiera persona con el objeto de obtener el consentimiento" (' + A(1457) + '). Dos razones: es más difícil <b>defenderse</b> de la fuerza que del dolo, y quien quiere presionar <b>suele valerse de otro</b>. En el matrimonio la regla es aún más amplia: basta la fuerza ocasionada por una persona o por una circunstancia externa (' + A('8 Nº 3 Ley 19.947') + ').',
  'II.A.7.4'),
 ('T11.4', 'Regla', 'intermedia', '¿Qué sanción tiene la fuerza y desde cuándo se cuenta el plazo de la acción rescisoria?',
  'La fuerza moral injusta, grave y determinante produce <b>nulidad relativa</b> (' + A('1682 inc. final') + '); la física, inexistencia o nulidad absoluta según la postura. La acción prescribe en <b>cuatro años</b> contados desde el día en que la fuerza <b>hubiere cesado</b> (' + A('1691 inc. 2°') + '), porque mientras dura la víctima no puede demandar.',
  'II.A.7.6 y 7.7'),
 ('T11.5', 'Concepto', 'basica', '¿Qué es el temor reverencial y vicia el consentimiento?',
  'Es "el solo temor de desagradar a las personas a quienes se debe sumisión y respeto", y <b>no basta</b> para viciar el consentimiento (' + A('1456 inc. 2°') + '). La palabra clave es "solo": si además hay una violencia injusta, grave y determinante, el consentimiento sí queda viciado.',
  'II.A.7.8'),
]
