# Flashcards de Acto Jurídico: lote 4 (temas 14 Objeto ilícito y 15 Causa).
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # Tema 14: Objeto ilícito
 ('T15.1', 'Distinción', 'intermedia', '¿Qué diferencia hay entre que el acto tenga objeto y que su objeto sea lícito? ¿Qué sanción tiene el objeto ilícito?',
  'Que el acto tenga <b>objeto</b> es un requisito de <b>existencia</b>: sin objeto, el acto no existe. Que el objeto sea <b>lícito</b> es un requisito de <b>validez</b> (' + A('1445 Nº 3') + '). Por eso el acto con objeto ilícito sí existe, pero nace viciado y puede ser anulado de <b>nulidad absoluta</b> (' + A(1682) + ').',
  'II.C.4'),
 ('T15.1', 'Concepto', 'basica', '¿Define el Código el objeto ilícito? ¿Cómo lo define la doctrina?',
  'No lo define: en su lugar <b>enumera los casos</b> en que hay objeto ilícito (' + AS('1462 a 1466') + '). La doctrina lo define como "aquel que versa sobre <b>hechos prohibidos por las leyes o contrarios a las buenas costumbres o al orden público</b>", con las mismas palabras con que el Código define la causa ilícita (' + A('1467 inc. 2°') + ').',
  'II.C.4'),
 ('T15.1', 'Enumeración', 'avanzada', '¿Cómo entienden el objeto lícito CLARO SOLAR, SOMARRIVA, ALESSANDRI y VELASCO LETELIER?',
  'Para <b>CLARO SOLAR</b>, es el que se ajusta a la ley y goza de su amparo; <b>SOMARRIVA</b> agrega las buenas costumbres y el orden público; para <b>ALESSANDRI</b>, lícito es lo mismo que <b>comerciable</b>; y <b>VELASCO LETELIER</b> lo vincula con el ' + A(1461) + ': es el que reúne todas las cualidades que ese artículo exige.',
  'II.C.4'),
 ('T15.2', 'Regla', 'intermedia', '¿Qué dispone el ' + A(1462) + ' y qué ocurre si quien contraviene el derecho público es un órgano del Estado?',
  'Hay objeto ilícito en todo lo que contraviene el <b>derecho público chileno</b>, como la promesa de someterse en Chile a una jurisdicción no reconocida por las leyes chilenas. Ojo: dice derecho público, no orden público. Si quien lo contraviene es un <b>órgano del Estado</b>, no rige el ' + A(1462) + ': la sanción es la <b>nulidad de derecho público</b> (' + A('7 de la Constitución') + ').',
  'II.C.4.1'),
 ('T15.2', 'Regla', 'avanzada', '¿Tienen objeto ilícito las cláusulas que entregan a tribunales extranjeros las disputas de un contrato?',
  'Hoy se pactan con frecuencia y se entienden válidas, por tres razones: el <b>Código de Procedimiento Civil</b> reconoce las jurisdicciones extranjeras (regula cómo se cumplen sus sentencias), el <b>Código de Derecho Internacional Privado</b> valida estas cláusulas (' + A(318) + ') y se ha expandido el <b>arbitraje internacional</b> (Ley Nº 19.971).',
  'II.C.4.1'),
 ('T15.3', 'Concepto', 'basica', '¿Qué es un pacto sobre sucesión futura y qué sanción tiene?',
  'Es la convención que recae sobre el <b>derecho a heredar a una persona viva</b>, como heredero o legatario, sea esa persona una de las partes o un tercero. Tiene <b>objeto ilícito</b> aunque intervenga el consentimiento de esa persona (' + A('1463 inc. 1°') + ') y es nula absolutamente. Si la persona ya murió, el acto es válido: es una cesión de derechos hereditarios (' + AS('1909 y siguientes') + ').',
  'II.C.4.2'),
 ('T15.3', 'Regla', 'intermedia', '¿Alcanza la prohibición del ' + A(1463) + ' a los actos unilaterales, aunque el artículo solo nombra la donación y el contrato?',
  'Sí. Una asignación solo puede aceptarse o repudiarse una vez <b>muerta la persona</b> (' + AS('956 y 1226') + '): si alguien acepta en vida del testador lo que este le dejó en su testamento, la aceptación es nula por objeto ilícito. La fórmula "donación o contrato" es redundante, porque la donación es un contrato.',
  'II.C.4.2'),
 ('T15.3', 'Regla', 'intermedia', '¿Cuál es la excepción a la prohibición de pactar sobre sucesión futura?',
  'El <b>pacto de no mejorar</b> (' + A(1204) + '): una persona puede prometer, por <b>escritura pública</b> entre vivos, a su cónyuge o a un descendiente o ascendiente que a esa fecha sea legitimario, que no donará ni asignará por testamento parte alguna de la <b>cuarta de mejoras</b>. Si no cumple, los asignatarios de esa cuarta deben enterarle al favorecido lo que le habría valido la promesa. Cualquier otra estipulación sobre la sucesión futura entre un legitimario y quien le debe la legítima es nula.',
  'II.C.4.2'),
 ('T15.4', 'Enumeración', 'basica', '¿En la enajenación de qué cosas hay objeto ilícito según el ' + A(1464) + '?',
  '1º De las cosas que <b>no están en el comercio</b>; 2º de los derechos o privilegios que <b>no pueden transferirse</b> a otra persona; 3º de las cosas <b>embargadas</b> por decreto judicial, a menos que el juez lo autorice o el acreedor consienta; y 4º de las especies cuya <b>propiedad se litiga</b>, sin permiso del juez que conoce en el litigio.',
  'II.C.4.3'),
 ('T15.4', 'Concepto', 'intermedia', '¿En qué sentido se toma la palabra "enajenación" en el ' + A(1464) + '? ¿Es enajenación la adjudicación?',
  'La mayoría y la jurisprudencia la toman en <b>sentido amplio</b>: "la transferencia del dominio o la constitución de cualquier otro derecho real" (hipoteca, usufructo, servidumbre), no solo la transferencia del dominio. La <b>adjudicación no es enajenación</b>: es declarativa y no traslaticia (' + AS('718, 1344 y 2417') + '), por lo que es válida la adjudicación de una cosa embargada o litigiosa.',
  'II.C.4.3'),
 ('T15.4', 'Distinción', 'avanzada', '¿Hay objeto ilícito en la compraventa de las cosas del ' + A(1464) + '? Exponga las tres tesis.',
  'El ' + A(1464) + ' castiga la enajenación, y la venta no lo es; la pregunta se resuelve por el ' + A(1810) + '. (i) <b>Tesis mayoritaria</b> (<b>ALESSANDRI</b>, <b>SOMARRIVA</b>, <b>VIAL</b>): hay objeto ilícito en la venta de las cuatro clases, por el ' + A(1466) + '. (ii) <b>VELASCO LETELIER</b>: solo en las de los Nºs 1 y 2, porque las embargadas y litigiosas pueden enajenarse con autorización (Corte Suprema, rol Nº 3671-1998). (iii) <b>ITURRA</b>: el ' + A(1810) + ' mira a leyes especiales, no al ' + A(1464) + '.',
  'II.C.4.3 (i) a (iii)'),
 ('T15.4', 'Distinción', 'avanzada', '¿Por qué el Nº 2 del ' + A(1464) + ' no sobra frente al Nº 1?',
  'Porque los derechos personalísimos (uso y habitación, ' + A(819) + '; pedir alimentos, ' + A(334) + ') sí pueden ser objeto de dominio o posesión de particulares: están <b>en el comercio</b>, pero son <b>inalienables</b>. Toda cosa incomerciable es inalienable, pero no toda cosa inalienable es incomerciable.',
  'II.C.4.3 (ii)'),
 ('T15.4', 'Regla', 'avanzada', '¿Qué se entiende por "cosas embargadas" en el ' + A('1464 Nº 3') + ' y desde cuándo afecta el embargo a terceros?',
  'Se entiende en <b>sentido amplio</b>: incluye las precautorias de prohibición de gravar y enajenar, el secuestro, la retención y, para la mayoría, la prohibición judicial de celebrar actos y contratos (' + A('296 C.P.C.') + '). Entre las partes, rige desde que se <b>notifica</b> al deudor. Respecto de terceros: en muebles, desde que la <b>conocen</b>; en inmuebles, desde que se <b>inscribe</b> (' + AS('297 y 453 C.P.C.') + '). Para <b>VIAL</b>, la inscripción solo decide si la nulidad alcanza a terceros.',
  'II.C.4.3 (iii) a) y b)'),
 ('T15.4', 'Regla', 'intermedia', '¿Cómo se enajena válidamente una cosa embargada?',
  'Con <b>autorización del juez</b> que decretó el embargo, dada con conocimiento de causa (si son varios jueces, todos deben autorizar), o con el <b>consentimiento del acreedor</b>, que puede ser expreso o tácito (si son varios, todos). Ambos deben ser <b>anteriores</b> a la enajenación: darlos después sería sanear una nulidad absoluta por ratificación, lo que no cabe (' + A(1683) + ').',
  'II.C.4.3 (iii) g)'),
 ('T15.4', 'Distinción', 'intermedia', '¿Produce objeto ilícito infringir una prohibición voluntaria de enajenar? ¿Y una prohibición legal?',
  'La <b>voluntaria</b> (pactada por las partes) no: el ' + A('1464 Nº 3') + ' exige un decreto judicial, y lo que hay es un <b>incumplimiento contractual</b>. La <b>legal</b> (por ejemplo, la de enajenar inmuebles con operaciones pendientes con el SERVIU) sí produce nulidad por <b>objeto ilícito</b>.',
  'II.C.4.3 (iii) e) y f)'),
 ('T15.4', 'Regla', 'avanzada', '¿Tiene objeto ilícito el remate de una cosa que estaba embargada en otro juicio?',
  'Discutido. Para <b>CLARO SOLAR</b> y <b>LEÓN HURTADO</b>, la enajenación <b>forzada es válida</b>: el Nº 3 castiga al deudor que traspasa voluntariamente, y en el remate enajena el juez; así se desprende del ' + A('528 C.P.C.') + ', que admite varias ejecuciones sobre los mismos bienes. Otros sostienen que también tiene objeto ilícito, porque la ley no distingue. La jurisprudencia ha fallado en ambos sentidos; <b>VIAL</b> adhiere a la primera.',
  'II.C.4.3 (iii) d)'),
 ('T15.4', 'Regla', 'intermedia', '¿Basta que exista un juicio sobre la propiedad de una especie para que su enajenación tenga objeto ilícito?',
  'No. El ' + A('296 C.P.C.') + ' exige que el tribunal <b>decrete prohibición</b> respecto de ella; según <b>VIAL</b>, esa norma modifica el ' + A('1464 Nº 4') + '. La especie litigiosa puede enajenarse con <b>permiso del juez</b> que conoce del litigio, y la doctrina mayoritaria admite también el consentimiento de la parte a cuyo favor se decretó la prohibición.',
  'II.C.4.3 (iv)'),
 ('T15.5', 'Regla', 'intermedia', '¿Qué dos reglas contiene el ' + A(1465) + ' sobre el perdón del dolo y qué consecuencia tienen para las cláusulas de irresponsabilidad?',
  'Primera: el pacto de no pedir más en razón de una <b>cuenta aprobada</b> no vale en cuanto al dolo contenido en ella si no se condonó <b>expresamente</b> (alcanza a cualquier finiquito). Segunda: la condonación del <b>dolo futuro</b> no vale. Ambas son casos de objeto ilícito, con nulidad absoluta. Por eso en Chile no valen las cláusulas de irresponsabilidad por dolo ni por <b>culpa grave</b>, que en materias civiles equivale al dolo (' + A(44) + ').',
  'II.C.4.4'),
 ('T15.6', 'Distinción', 'intermedia', '¿Hay objeto ilícito en las deudas de juego? Distinga según la clase de juego.',
  'En los juegos de <b>azar</b> hay objeto ilícito (' + A(1466) + '), salvo los autorizados por ley (Polla, Lotería, casinos). En los de <b>fuerza o destreza corporal</b>, el que gana tiene acción para cobrar (' + A(2263) + '). En los de <b>destreza intelectual</b>, el que gana no puede exigir el pago, pero si el que perdió paga, no puede pedir que se le devuelva, salvo dolo (' + A(2260) + ').',
  'II.C.4.5'),
 ('T15.6', 'Regla', 'intermedia', '¿Qué regla general contiene el final del ' + A(1466) + ' y cómo se relaciona con el ' + A(10) + '?',
  'Hay objeto ilícito "generalmente en todo <b>contrato prohibido por las leyes</b>". Leída junto al ' + A(10) + ', todo acto prohibido por la ley es <b>nulo</b>, salvo que la propia ley establezca otra sanción. Ejemplo de otra sanción: los usufructos sucesivos o alternativos (' + A(769) + ') no se anulan; los usufructuarios posteriores se consideran sustitutos.',
  'II.C.4.7'),
 # Tema 15: Causa
 ('T16.1', 'Enumeración', 'basica', '¿En qué tres sentidos se usa la palabra causa?',
  '<b>Causa eficiente</b>: el antecedente que hace nacer algo; la de una obligación es su fuente (el contrato de compraventa). <b>Causa final</b>: el fin directo e inmediato que se persigue, igual en todos los actos de una especie (en toda compraventa, el comprador busca la cosa y el vendedor el dinero). <b>Causa ocasional</b>: los motivos personales de cada uno, variables y psicológicos.',
  'II.D.1'),
 ('T16.1', 'Regla', 'intermedia', '¿Quiénes construyen la teoría clásica de la causa y en qué se aparta el Código chileno del francés?',
  'La construye <b>DOMAT</b> y la completa <b>POTHIER</b>, por cuya vía llega al Código Civil francés; antes, los canonistas la habían usado para impedir que la voluntad sirviera a un fin reprobable. El Código francés exigió la causa <b>sin definirla</b>; el chileno, a diferencia de su modelo, <b>sí la definió</b>.',
  'II.D.2'),
 ('T16.2', 'Distinción', 'intermedia', 'Según la doctrina clásica, ¿cuál es la causa de la obligación en los contratos bilaterales, reales y gratuitos?',
  'En los <b>bilaterales</b>, la obligación recíproca de la otra parte. En los <b>reales</b>, la entrega previa de la cosa (el comodatario debe restituir porque se le entregó). En los <b>gratuitos</b>, la <b>intención liberal</b> (POTHIER), separada de los móviles concretos del donante. El criterio es objetivo: dentro de cada categoría la causa es siempre la misma.',
  'II.D.3.1'),
 ('T16.2', 'Distinción', 'avanzada', '¿Qué diferencia a la doctrina italiana de la doctrina del móvil o motivo determinante?',
  'Ambas refieren la causa al <b>acto o contrato</b>, no a la obligación. La <b>italiana</b> la aprecia con criterio <b>objetivo</b>: es la función económico-social que caracteriza al tipo de negocio (<b>BETTI</b>). La del <b>móvil</b> (<b>MAURY</b>) usa un criterio <b>subjetivo</b>: es el motivo determinante que llevó a las partes a contratar, y si es ilícito el acto puede anularse (en los onerosos, el móvil de una parte debe ser al menos conocido por la otra).',
  'II.D.3.2 y 3.3'),
 ('T16.2', 'Concepto', 'avanzada', '¿Por qué sostiene PLANIOL que la teoría clásica de la causa es falsa e inútil?',
  '<b>Falsa</b>: en los bilaterales las dos obligaciones nacen a la vez, y ninguna puede ser causa de la otra; en los reales la entrega es requisito de perfección, no causa; en los gratuitos es imposible separar la intención liberal de los motivos. <b>Inútil</b>: lo que llama causa es el objeto de la otra obligación, la falta de entrega impide que el contrato nazca y la falta de intención liberal es falta de consentimiento. Para <b>PLANIOL</b> la causa se confunde con el objeto; para <b>DABIN</b>, con el consentimiento.',
  'II.D.3'),
 ('T16.3', 'Regla', 'basica', '¿Qué dispone el ' + A(1467) + '?',
  'No puede haber obligación sin una causa <b>real y lícita</b>, pero no es necesario expresarla; la pura liberalidad o beneficencia es causa suficiente. Define causa como "el <b>motivo que induce al acto o contrato</b>" y causa ilícita como "la prohibida por ley, o contraria a las buenas costumbres o al orden público". Ejemplos: la promesa de pagar una deuda que no existe carece de causa; la de dar algo en recompensa de un crimen tiene causa ilícita.',
  'II.D.4'),
 ('T16.3', 'Distinción', 'avanzada', '¿Qué debe tener causa en el Código chileno: el acto o la obligación?',
  'Hay dos lecturas. <b>La obligación</b>: lo dice la letra del ' + A(1467) + ' ("no puede haber obligación sin una causa") y del ' + A(1445) + ', y el Código se redactó en el apogeo de la doctrina clásica. <b>El acto o contrato</b>: el ' + A(1445) + ' completo exige causa lícita al acto o declaración de voluntad, la definición del ' + A(1467) + ' habla del motivo que induce al acto o contrato, y el ' + A(2057) + ' habla de sociedades nulas por lo ilícito de la causa.',
  'II.D.4.1'),
 ('T16.3', 'Distinción', 'avanzada', '¿Sigue el Código un criterio objetivo o subjetivo de causa? Dé argumentos de ambas posiciones.',
  '<b>Objetivo</b> (doctrina clásica): argumento histórico; exigir causa "real" solo tiene sentido si una obligación puede carecer de ella; los ejemplos del ' + A(1467) + ' calzan con Pothier (<b>LEÓN HURTADO</b>). <b>Subjetivo</b>: el Código definió la causa como el "motivo", palabra que en su sentido natural designa los móviles psicológicos, y la usa así en los ' + AS('1454 y 1455') + '; además, exigir causa real y lícita autoriza al juez a buscar el motivo verdadero.',
  'II.D.4.2'),
 ('T16.3', 'Concepto', 'intermedia', '¿Qué es la tesis dual de la causa y qué le objeta ALCALDE?',
  'Es la opinión más aceptada en Chile (<b>LEÓN HURTADO</b> y <b>VIAL</b>): el <b>acto o contrato</b> tiene una causa <b>subjetiva</b>, el motivo que induce a celebrarlo (' + A(1467) + '), y la <b>obligación</b> tiene una causa <b>objetiva</b>, la de la teoría clásica. <b>ALCALDE</b> propone un concepto unitario: la causa es "aquel supuesto de hecho legalmente suficiente para justificar un determinado efecto jurídico", y la distinción no tiene importancia práctica.',
  'II.D.4.3 y 4.4'),
 ('T16.4', 'Regla', 'intermedia', '¿Debe expresarse la causa? ¿Quién debe probar que falta? Dé casos de actos sin causa real.',
  'No es necesario expresarla (' + A(1467) + '): para <b>VIAL</b>, la ley <b>presume</b> que todo acto tiene una causa, la formada por los motivos habituales de ese tipo de acto, y que es lícita; por eso quien alega que falta o es ilícita debe <b>probarlo</b>. Casos sin causa real: los <b>actos simulados</b> y los actos cuyo único motivo es creer, por error, que existe una obligación (la promesa de pagar una deuda inexistente).',
  'II.D.5'),
 ('T16.4', 'Distinción', 'intermedia', '¿Qué sanción tiene el acto que carece de causa?',
  'Para quienes aceptan la inexistencia, el acto <b>no llega a nacer</b>, porque le falta un requisito de existencia (<b>CLARO SOLAR</b>: "no es un acto nulo, sino un acto que no ha podido nacer a la vida jurídica"). Quienes niegan que el Código recoja la inexistencia lo sancionan con <b>nulidad absoluta</b>.',
  'II.D.5'),
 ('T16.5', 'Regla', 'basica', '¿Qué es la causa ilícita y qué consecuencias tiene?',
  'Es la prohibida por ley, o contraria a las buenas costumbres o al orden público (' + A('1467 inc. 2°') + '), como la promesa de dar algo en recompensa de un crimen. El acto es <b>absolutamente nulo</b> (' + A(1682) + '), sanción que nadie discute. Y quien dio o pagó algo por causa ilícita a sabiendas <b>no puede pedir que se le devuelva</b> (' + A(1468) + ').',
  'II.D.6'),
 ('T16.5', 'Regla', 'avanzada', 'Según VIAL, ¿cómo determina el juez si la causa de un acto es ilícita?',
  'En principio a la ley le basta el motivo típico del contrato, que siempre es lícito. Pero si se alega causa ilícita, el juez debe averiguar el <b>motivo individual y determinante</b> que llevó a contratar, porque solo el motivo real puede ser lícito o ilícito. No basta lo que diga el contrato ni la naturaleza del contrato: debe llegar al motivo real con las <b>pruebas</b> rendidas, incluidas las presunciones.',
  'II.D.6'),
 ('T16.6', 'Concepto', 'avanzada', '¿Es el acto abstracto un acto sin causa? ¿Qué es su relación fundamental y subyacente?',
  'No: la causa existe, pero el derecho <b>no la toma en cuenta</b> para constituir el acto ni para que produzca efectos. La <b>relación fundamental y subyacente</b> es la obligación que el acto abstracto viene a cumplir o reforzar (la compraventa cuyo precio se paga con una letra). Para <b>BOETSCH</b>, su falta o ilicitud solo puede alegarse entre las partes de esa relación y frente a terceros de mala fe, nunca frente a terceros de buena fe (' + AS('28 y 107 Ley Nº 18.092') + ').',
  'II.D.7.1 y 7.2'),
 ('T16.6', 'Regla', 'intermedia', '¿Pueden los particulares crear actos abstractos? Dé ejemplos de actos abstractos en Chile.',
  'No: <b>solo la ley</b> puede crearlos. La causa es un requisito del acto (' + A('1445 inc. 1°') + ') y su omisión se sanciona con inexistencia o nulidad absoluta, lo que muestra que es de <b>orden público</b>. Se mencionan como abstractos la <b>delegación</b>, la <b>estipulación a favor de otro</b>, la <b>fianza</b> y los contratos que garantizan deuda ajena, y algunos títulos de crédito como la <b>letra de cambio</b>.',
  'II.D.7.4 y 7.5'),
 ('T16.7', 'Regla', 'avanzada', 'Si la fuerza o el dolo determinantes son también la causa del acto, ¿se aplican las reglas de la causa ilícita o las de los vicios del consentimiento?',
  'Para <b>VIAL</b>, la víctima no puede elegir: priman las normas sobre <b>vicios del consentimiento</b> (nulidad relativa), porque son <b>especiales</b> frente a las de la causa ilícita (nulidad absoluta). La pregunta importa porque cada nulidad tiene reglas distintas sobre quién puede pedirla y cómo se sanea.',
  'II.D.8'),
]
