# Flashcards de Acto Jurídico: lote 9 (temas 23 a 27: lesión, simulación, inoponibilidad, fraude a la ley y otras causales de ineficacia).
# Criterio de pocas tarjetas (Laura, 2026-10-08): una por subtema, dos solo si el subtema junta ideas distintas.
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # T12 Lesión
 ('T12.1', 'Concepto', 'basica', '¿Qué es técnicamente la lesión y en qué actos no cabe?',
  'Es el <b>perjuicio pecuniario</b> que sufre una de las partes de un contrato <b>oneroso conmutativo</b> (' + AS('1440 y 1441') + '), porque las prestaciones que la ley mira como equivalentes no lo son en realidad. Por eso la doctrina la deja fuera de los <b>actos gratuitos</b>, donde el gravamen recae desde el inicio en una sola parte, y de los <b>contratos aleatorios</b>, donde lo que se promete es una contingencia incierta, no una prestación medible.',
  'IV.C.1'),
 ('T12.2', 'Regla', 'intermedia', '¿Es la lesión un vicio del consentimiento en el Código Civil chileno?',
  'Para la doctrina nacional, por regla general, <b>no</b>. Razón histórica: el Proyecto de 1853 la trataba como vicio del consentimiento, pero el ' + A(1451) + ' no la recogió. Razón estructural: opera con <b>criterios puramente objetivos</b>, alcanza incluso a actos que no son contratos onerosos conmutativos, solo existe en los casos que la ley señala y no siempre se sanciona con nulidad relativa. La excepción es la <b>aceptación de una herencia</b>. En posición minoritaria, <b>DUCCI</b> la incluye en el error sustancial (' + AS('1454 y 1460') + ').',
  'IV.C.2'),
 ('T12.3', 'Enumeración', 'intermedia', '¿En qué casos sanciona la lesión el Código Civil?',
  'No hay una causal general: es una lista taxativa. (i) <b>Compraventa</b> voluntaria de bienes raíces (' + A(1889) + '); (ii) <b>permuta</b> de bienes raíces (' + A(1900) + '); (iii) <b>aceptación de una asignación hereditaria</b> (' + A(1234) + '); (iv) <b>partición</b> de bienes (' + A(1348) + '); (v) intereses del <b>mutuo</b> (' + A(2206) + '); (vi) <b>anticresis</b> (' + A(2443) + '); (vii) <b>cláusula penal</b> enorme (' + A(1544) + '); y (viii) <b>hipoteca</b> que excede el duplo de la obligación (' + A(2431) + ').',
  'IV.C.3'),
 ('T12.3', 'Regla', 'basica', '¿Cuándo hay lesión enorme en la compraventa de un inmueble y cómo puede evitar la rescisión el contratante beneficiado?',
  'El <b>vendedor</b> la sufre cuando el precio que recibe es inferior a la <b>mitad del justo precio</b>; el <b>comprador</b>, cuando el justo precio es inferior a la mitad del precio que paga. El justo precio se refiere al tiempo del contrato (' + A(1889) + '). Pronunciada la rescisión, el comprador puede completar el justo precio con deducción de una décima parte, y el vendedor restituir el exceso aumentado en una décima parte (' + A(1890) + ').',
  'IV.C.3'),
 ('T12.4', 'Regla', 'basica', '¿Cuál es la sanción de la lesión?',
  'Depende del caso. En algunos, como la <b>compraventa</b>, es la <b>nulidad relativa</b> o rescisión, de la que el ganancioso puede escapar completando o restituyendo la prestación deficiente. En otros, como el <b>mutuo</b> o la <b>cláusula penal</b>, la ley se limita a <b>reducir</b> la estipulación lesiva a términos razonables.',
  'IV.C.4'),
 # T24 Simulación
 ('T24.1', 'Distinción', 'intermedia', '¿Qué es la simulación y en qué se diferencia de la reserva mental?',
  'Según Avelino <b>LEÓN</b>, es aparentar una declaración de voluntad que no se desea, <b>con la aquiescencia</b> de la parte a quien va dirigida. En la <b>reserva mental</b> también se declara algo distinto de lo querido, pero a solas, sin que el destinatario lo sepa. Por eso la simulación solo cabe en actos bilaterales y unilaterales recepticios, y el acto simulado es generalmente nulo; el acto con reserva mental cabe en cualquier acto y es, en principio, válido.',
  'IV.D.1'),
 ('T24.1', 'Regla', 'intermedia', '¿Regula el Código Civil chileno la simulación? ¿En qué norma se ha apoyado la doctrina para construirla?',
  '<b>No</b>: ni la regula ni usa esa palabra. Doctrina y jurisprudencia la han construido sobre todo a partir del ' + A(1707) + ': las escrituras privadas hechas por los contratantes para alterar lo pactado en escritura pública no producen efecto contra terceros, y tampoco las contraescrituras públicas si no se ha tomado razón de su contenido al margen de la escritura matriz.',
  'IV.D.2'),
 ('T24.2', 'Distinción', 'intermedia', '¿Cuándo es lícita la simulación y cuáles son los requisitos de la simulación ilícita?',
  'Simular no es, por sí solo, contrario a derecho: es <b>lícita</b> si no persigue perjudicar a terceros (ej.: la escritura que declara un precio pagado al contado, con instrucciones notariales que lo retienen hasta la inscripción). Es <b>ilícita</b> la que perjudica, o busca perjudicar, a terceros o violar la ley, y requiere: (i) <b>disconformidad</b> entre la voluntad real y la declarada; (ii) <b>conciencia y deliberación</b> de esa disconformidad; (iii) <b>concierto</b> entre las partes; y (iv) <b>intención de engañar</b> a terceros.',
  'IV.D.3 y IV.D.4.1'),
 ('T24.3', 'Distinción', 'basica', 'Simulación absoluta y relativa: ¿en qué se diferencian? ¿Qué es la interposición de persona?',
  'En la <b>absoluta</b> no se celebra ningún acto, solo se aparenta uno. En la <b>relativa</b> se aparenta un acto (ostensible o simulado) pero se quiere otro distinto (oculto o disimulado), que puede diferir en la naturaleza, el objeto o los sujetos. Cuando difiere en los sujetos hay <b>interposición ficticia de persona</b>: un prestanombre figura en el título en lugar del contratante real (ej.: vender a un tercero que revende al cónyuge, para eludir el ' + A(1796) + ').',
  'IV.D.4.2'),
 ('T24.4', 'Regla', 'intermedia', '¿Cuál es la sanción civil de la simulación ilícita?',
  'El acto simulado es <b>absolutamente nulo</b>: en la absoluta, por falta de causa real; en la relativa, por causa u objeto ilícito (' + AS('1467 y 1681') + '). El acto disimulado vale si cumple sus propios requisitos. Si la ley fija una <b>sanción especial</b>, rige esa (' + A(10) + '), como la del cónyuge que oculta o distrae bienes de la sociedad conyugal (' + A(1768) + '). Un sector agrega una <b>acción autónoma de simulación</b>, para fijar la voluntad real.',
  'IV.D.4.3'),
 ('T24.4', 'Regla', 'intermedia', '¿Cómo se prueba la simulación y qué diferencia hay entre las partes y los terceros?',
  'La ley presume sinceros los actos, así que debe probarla quien la alega, y casi nunca puede hacerse de forma directa: las <b>presunciones</b> son decisivas. Los <b>terceros</b> pueden usar cualquier medio, incluida la prueba de testigos aunque se supere el límite legal (' + A('1709 inc. 1°') + '), porque prueban la simulación y no la obligación. Entre las <b>partes</b>, la prueba de testigos está vedada (' + A('1709 inc. 2°') + ').',
  'IV.D.4.4'),
 # T25 Inoponibilidad
 ('T25.1', 'Concepto', 'intermedia', '¿Qué es la inoponibilidad y qué terceros pueden alegarla?',
  'Es la ineficacia de un derecho, nacido de un acto válido o de uno nulo, revocado o resuelto, <b>respecto de ciertos terceros</b>, que pueden oponerse a sus efectos. No es un vicio del acto ni afecta su validez. Por regla general la alegan los <b>terceros relativos</b>, que están o estarán en alguna relación jurídica con las partes; el tercero absoluto queda fuera, salvo excepciones, como el dueño en la venta, arrendamiento o prenda de cosa ajena.',
  'IV.E.1'),
 ('T25.2', 'Distinción', 'intermedia', 'Inoponibilidades de forma y de fondo: ¿qué las distingue? Dé ejemplos de cada una.',
  'Son <b>de forma</b> cuando falta una formalidad exigida no para que el acto exista, sino para oponerlo a terceros: falta de publicidad (contraescrituras, ' + A(1707) + '; cesión de créditos no notificada, ' + A(1902) + ') o falta de fecha cierta (' + A(1703) + '). Son <b>de fondo</b> cuando, sin faltar formalidad, el acto hiere injustamente derechos de terceros: falta de concurrencia (venta de cosa ajena, ' + A(1815) + '), falta o exceso de poder, <b>fraude</b> (acción pauliana, ' + A(2468) + '), lesión de derechos adquiridos y de asignaciones forzosas.',
  'IV.E.2'),
 ('T25.3', 'Regla', 'avanzada', '¿Hay casos en que la nulidad o la resolución de un acto no alcanza a los terceros?',
  '<b>Sí</b>: los terceros pueden tener derecho a que el acto se trate como válido respecto de ellos. Así, la nulidad del contrato de una sociedad que existió de hecho no afecta las acciones de los terceros de buena fe contra cada socio (' + A(2058) + '); la resolución judicial no alcanza a los terceros de buena fe (' + AS('1490 y 1491') + '); y en la donación, por regla general, ni la resolución ni la rescisión ni la revocación afectan a los terceros poseedores de los bienes donados (' + A(1432) + ').',
  'IV.E.3'),
 ('T25.4', 'Distinción', 'intermedia', '¿Cómo se hace valer la inoponibilidad y en qué se diferencia de la nulidad?',
  'Debe alegarla el tercero favorecido, <b>nunca de oficio</b>, normalmente como <b>excepción</b> (como acción solo en casos contados, como la pauliana). Frente a la nulidad: (i) la nulidad nace de un vicio coetáneo al acto; en la inoponibilidad el acto es <b>válido</b> y la ineficacia viene de una circunstancia posterior o externa; (ii) la nulidad priva de efectos frente a partes y terceros; la inoponibilidad solo frente a ciertos terceros; (iii) la nulidad es de orden público e irrenunciable; la inoponibilidad, de orden privado y <b>renunciable</b>; y (iv) la absoluta puede declararse de oficio (' + A(1683) + ').',
  'IV.E'),
 # T26 Fraude a la ley
 ('T26.1', 'Concepto', 'intermedia', '¿Qué es el fraude a la ley y cuáles son sus requisitos?',
  'Es el uso de actos <b>en sí lícitos</b>, con apariencia de legalidad, como medio para eludir una norma imperativa o prohibitiva: se respeta la letra de la ley, pero se viola su espíritu. Requisitos: (i) actos <b>lícitos</b>, al menos en apariencia; (ii) una <b>ley defraudada</b>, con un resultado práctico equivalente al que la norma quería evitar (elemento objetivo); y (iii) un <b>elemento intencional</b>, el ánimo fraudatorio, cuya exigencia se discute: para una postura objetiva basta que el resultado choque con la norma.',
  'IV.F'),
 ('T26.1', 'Regla', 'avanzada', '¿Cuál es la sanción del fraude a la ley cuando la ley no la fija expresamente?',
  'No hay sanción única: según la norma, el acto puede ser inoponible (' + AS('803 y 1792-24') + '), nulo (' + A('1578 Nº 3') + ') o dar lugar a indemnización (' + AS('1662 y 2317') + '). En los casos no regulados, <b>DOMÍNGUEZ</b> defiende la <b>inoponibilidad</b>, que restituye la vigencia de la norma eludida sin ir más allá; otros, como <b>VIAL</b>, la <b>nulidad absoluta</b>, porque el acto se equipara a uno contra legem o de causa ilícita.',
  'IV.F.5'),
 # T27 Otras causales de ineficacia
 ('T27.1', 'Concepto', 'basica', '¿Qué es la resolución y cuáles son sus dos fuentes?',
  'Es la ineficacia de un acto por un hecho posterior a su celebración que hace cesar los efectos ya producidos. Ese hecho puede ser: (i) un acontecimiento futuro e incierto al que las partes subordinaron la extinción de un derecho (<b>condición resolutoria ordinaria</b>); o (ii) el <b>incumplimiento</b> de una parte en un contrato bilateral (<b>condición resolutoria tácita</b>), que permite a la otra pedir la resolución o el cumplimiento, con indemnización de perjuicios (' + A(1489) + '). Frente a terceros rigen los ' + AS('1490 y 1491') + '.',
  'IV.G.2'),
 ('T27.2', 'Concepto', 'basica', '¿Qué es la resciliación y qué efecto tiene respecto de terceros?',
  'Es el acuerdo de las partes, capaces de disponer libremente de lo suyo, para dejar sin efecto el contrato y extinguir las obligaciones que nacieron de él (' + A('1567 inc. 1°') + '). A los terceros <b>nunca puede afectarlos</b>: les es inoponible (res inter alios acta).',
  'IV.G.3'),
 ('T27.3', 'Distinción', 'intermedia', '¿En qué se diferencian la revocación y el desistimiento unilateral?',
  'La <b>revocación</b> es retractarse de un acto por la sola voluntad de quien lo celebró, cuando la ley lo permite (el testamento siempre; en los contratos, solo excepcionalmente, como el mandato, ' + A(2163) + '): ataca el acto mismo. El <b>desistimiento unilateral</b> deja el acto intacto y solo disuelve la relación <b>hacia adelante</b> (ex nunc), sin retroactividad; procede solo si la ley o las partes lo permiten, típicamente en contratos de duración indefinida, como el desahucio.',
  'IV.G.4 y IV.G.5'),
 ('T27.4', 'Distinción', 'intermedia', '¿En qué se diferencian la terminación y la resolución? ¿Qué es la caducidad en sentido específico?',
  'La <b>terminación</b>, a diferencia de la resolución, <b>no es retroactiva</b>: priva de efectos al acto solo hacia el futuro; es propia de los contratos de tracto sucesivo, como el arrendamiento, donde deshacer lo cumplido sería impracticable. La <b>caducidad</b>, en sentido específico, es la ineficacia que la ley impone a un acto por un hecho sobreviniente, sin necesidad de revocarlo, como el testamento privilegiado cuando el testador sobrevive (' + A('1212 inc. 2°') + ').',
  'IV.G'),
]
