# Evaluación de Acto Jurídico, tanda 3: Detección de error del tema 20 (Nulidad), IV.B.1 a IV.B.3.5.
# Regla de cantidad del 2026-10-10: cuatro preguntas por tipo en los subtemas de 10 o más exámenes
# y dos en el resto (una en los subtemas sin exámenes). Esta es la primera de dos tandas: dos
# preguntas en cada subtema importante y una en los demás (17); la tanda siguiente completa el tema.
# La sección de Nulidad no tiene recuadros de Advertencia: los errores salen de las confusiones
# que el propio manual aclara (gravedad de las especies, causales, titulares, plazos, art. 1685).
#
# Formato de cada ítem: el mismo de lote_aplic1.py. El caso es el párrafo de un alumno con uno o
# dos errores; los elementos suelen ser: identificar el error, explicar por qué y dar la regla.
TABLA = 'Detección de error'
PREFIJO = 'aj-det'

ENUN = 'Identifique y corrija los errores de este razonamiento.'

ITEMS = [
 # T21.01 Reglas, concepto general y especies de nulidad (15 exámenes)
 dict(sub='T21.01',
  caso='Un alumno escribe en su prueba: "La nulidad absoluta es una sanción más severa que la relativa. Por eso, una vez declarada, el acto absolutamente nulo queda totalmente borrado, mientras que el relativamente nulo conserva una parte de lo que produjo, porque su vicio es menos grave."',
  enunciado=ENUN,
  respuesta='El error está en medir las especies de nulidad por su gravedad. La nulidad absoluta no es un grado más severo de invalidez, ni la relativa deja al acto "medio nulo": una vez declaradas judicialmente, las dos producen exactamente los mismos efectos, que es volver a las partes al estado anterior a la celebración del acto nulo.\n\nLo que separa a una de otra es la razón por la que se exige el requisito omitido (art. 1681 inc. 2°). Hay nulidad absoluta cuando el requisito se exige en consideración a la naturaleza o especie del acto, y nulidad relativa cuando se exige en atención a la calidad o estado de las partes que lo celebran.\n\nLas diferencias reales entre ambas están en las causales, en quién puede pedir cada una y en el plazo en que se sanean, no en sus efectos.',
  elementos=[
   ('Declaradas, ambas nulidades producen los mismos efectos: vuelven a las partes al estado anterior al acto',
    ['mismos efectos', 'estado anterior', 'efectos identicos', 'vuelven al estado', 'producen lo mismo'],
    'Una vez que el juez declara la nulidad, ¿en qué situación quedan las partes en cada especie?'),
   ('El criterio para distinguirlas es por qué se exige el requisito: la naturaleza del acto o la calidad o estado de las partes (art. 1681 inc. 2°)',
    ['naturaleza del acto', 'especie del acto', 'calidad o estado', '1681', 'atencion a las partes'],
    '¿Qué mira el Código, respecto del requisito que falta, para decidir qué especie de nulidad corresponde?'),
   ('Las diferencias están en las causales, en quién puede pedirla y en el plazo de saneamiento',
    ['quien puede pedirla', 'quienes pueden alegarla', 'plazo de saneamiento', 'causales distintas', 'se sanean en plazos', 'titulares distintos'],
    'Si no es en sus consecuencias, ¿en qué aspectos sí se apartan una de otra?')],
  articulos='1681',
  objetivo='Evaluar si el alumno detecta que las especies de nulidad no se distinguen por su gravedad ni por sus efectos, sino por la razón por la que se exige el requisito omitido.',
  respaldo=['IV.B.1.3']),

 dict(sub='T21.01',
  caso='Un alumno escribe: "Las reglas sobre nulidad del Título XX del Libro IV son de derecho privado y, por lo mismo, quedan entregadas a la voluntad de los contratantes: si así lo acuerdan, pueden dejarlas sin aplicación en su contrato. Además, como el Código Civil es el derecho común, esas mismas reglas rigen la nulidad de los actos administrativos y de las actuaciones de un juicio."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, que las reglas de la nulidad estén en el derecho privado no las deja a disposición de las partes. Son de orden público: de aplicación estricta, y las partes no pueden derogarlas. Por eso mismo el art. 1469 dispone que los actos que la ley declara inválidos no dejan de serlo por las cláusulas en que se renuncie la acción de nulidad.\n\nSegundo, las reglas de nulidad del Código Civil se aplican también en las demás ramas del derecho privado si no hay norma especial en contrario, pero no se extienden al derecho público, que tiene reglas propias y distintas en cada rama: la nulidad en el derecho administrativo no es la misma que en el derecho procesal.',
  elementos=[
   ('Las reglas de la nulidad son de orden público: las partes no pueden derogarlas',
    ['orden publico', 'no pueden derogarlas', 'no son disponibles', 'aplicacion estricta', 'no pueden excluirlas'],
    '¿Qué carácter tienen estas normas frente a lo que quieran pactar los contratantes?'),
   ('No vale la cláusula que renuncia a la acción de nulidad (art. 1469)',
    ['1469', 'renuncia no vale', 'renunciar la accion', 'clausula de renuncia', 'no se puede renunciar'],
    '¿Qué dice el Código de una estipulación por la que las partes se comprometen a no demandar la invalidez?'),
   ('Las reglas de nulidad del Código Civil no se extienden al derecho público, que tiene reglas propias en cada rama',
    ['no se extienden al derecho publico', 'derecho publico reglas propias', 'reglas propias cada rama', 'nulidad procesal distinta', 'no rigen derecho publico'],
    '¿Hasta qué ramas del ordenamiento alcanza el Título XX del Libro IV?')],
  articulos='1469',
  objetivo='Evaluar si el alumno detecta que las reglas de la nulidad son de orden público e irrenunciables y que no se extienden al derecho público.',
  respaldo=['IV.B.1.1', 'IV.B.1.7']),

 # T21.02 Terminología y nulidad como regla general (0 exámenes)
 dict(sub='T21.02',
  caso='Un alumno escribe: "El art. 1682 inc. final iguala la nulidad relativa y la rescisión, que son sinónimos; por eso, cuando el Código habla de rescisión frente a un vicio de nulidad absoluta, simplemente se equivocó el legislador. Además, la especie de nulidad que constituye la regla general es la absoluta, porque es la que protege el interés de toda la sociedad."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, un sector de la doctrina niega que nulidad relativa y rescisión sean sinónimos. El art. 1682 inc. final no las iguala: dice que la nulidad relativa da derecho a la rescisión, es decir, que una da derecho a la otra. Rescindir es dejar sin efecto un contrato, y ese efecto lo produce cualquiera de las dos nulidades. Si fueran sinónimos, la norma diría que la nulidad relativa da derecho a pedir la nulidad relativa, lo que no tiene sentido. Por eso, cuando la ley habla de rescisión frente a un vicio de nulidad absoluta, no hay un error del legislador, sino el uso genérico de la palabra: la rescisión es el efecto, el derecho a pedir que el acto quede sin efecto.\n\nSegundo, la regla general es la nulidad relativa, no la absoluta. El art. 1682 cierra la enumeración de las causales de nulidad absoluta con una cláusula residual: cualquiera otra especie de vicio produce nulidad relativa. Todo vicio que la ley no sancione expresamente de otro modo cae ahí.',
  elementos=[
   ('La norma no las iguala: la nulidad relativa da derecho a la rescisión, que es dejar sin efecto el acto',
    ['da derecho a la rescision', 'dejar sin efecto', 'no las iguala', 'no son sinonimos', 'una da derecho'],
    '¿Qué relación establece realmente el art. 1682 inc. final entre las dos expresiones?'),
   ('No hay error del legislador: la rescisión es el efecto común a ambas nulidades, por eso se usa también en la absoluta',
    ['uso generico', 'efecto de ambas', 'cualquiera de las dos', 'no es error', 'sentido generico', 'ambas nulidades producen'],
    '¿Es exclusivo de una sola especie de nulidad el resultado que describe la palabra rescindir?'),
   ('La regla general es la nulidad relativa, por la cláusula residual del art. 1682',
    ['regla general es la relativa', 'clausula residual', 'cualquiera otra especie', 'relativa regla general', 'todo otro vicio'],
    '¿Qué sanción dispone el art. 1682 para los vicios que no menciona expresamente?')],
  articulos='1682',
  objetivo='Evaluar si el alumno detecta los argumentos contra la sinonimia entre nulidad relativa y rescisión y reconoce que la regla general es la nulidad relativa.',
  respaldo=['IV.B.1.4', 'IV.B.1.5']),

 # T21.03 Diferencias entre nulidad absoluta y relativa (5 exámenes)
 dict(sub='T21.03',
  caso='Un alumno escribe: "Las dos especies de nulidad pueden ser declaradas de oficio por el juez cuando el vicio aparece de manifiesto en el acto, y el ministerio público puede pedir cualquiera de ellas en el solo interés de la ley. Lo único que las separa es que la relativa admite ratificación y la absoluta no."',
  enunciado=ENUN,
  respuesta='Hay dos errores, y ambos vienen de olvidar el fundamento de cada especie.\n\nPrimero, solo la nulidad absoluta puede y debe declararla el juez de oficio cuando aparece de manifiesto en el acto o contrato (art. 1683). La relativa no puede ser declarada por el juez sino a pedimento de parte (art. 1684).\n\nSegundo, el ministerio público puede pedir la nulidad absoluta en el interés de la moral o de la ley, pero no puede pedir la relativa en el solo interés de la ley (art. 1684).\n\nLa razón es que la absoluta protege el interés de la moral y de la ley, mientras que la relativa protege el interés de ciertas y determinadas personas, y solo ellas, sus herederos o cesionarios pueden alegarla. Es cierto que la relativa admite ratificación y la absoluta no, pero no es la única diferencia: también se distinguen en el plazo de saneamiento, diez años en la absoluta y cuatro en la relativa.',
  elementos=[
   ('La nulidad relativa no puede declararse de oficio: solo a petición de parte (art. 1684)',
    ['peticion de parte', 'pedimento de parte', 'solo si la piden', 'relativa no de oficio', 'no cabe de oficio'],
    '¿Puede el tribunal actuar por su propia iniciativa frente a un vicio que protege solo a una de las partes?'),
   ('El ministerio público no puede pedir la nulidad relativa en el solo interés de la ley; sí la absoluta',
    ['ministerio publico no puede', 'solo la absoluta', 'no puede pedir la relativa', 'fiscal no puede'],
    '¿Para cuál de las dos especies queda habilitado el organismo que actúa en resguardo de la ley?'),
   ('La razón: la absoluta protege el interés de la moral y de la ley; la relativa, el de personas determinadas',
    ['interes general', 'personas determinadas', 'moral y de la ley', 'proteger a ciertas personas', 'interes particular'],
    '¿A quién busca proteger cada especie de nulidad, y cómo explica eso las dos reglas anteriores?')],
  articulos='1683, 1684',
  objetivo='Evaluar si el alumno distingue las dos nulidades en la declaración de oficio y en la intervención del ministerio público, a partir del fundamento de cada una.',
  respaldo=['IV.B.1.6']),

 # T21.04 Principios comunes a ambas nulidades (0 exámenes)
 dict(sub='T21.04',
  caso='Un alumno escribe: "Si una persona compra un terreno en 2018 mediante un contrato perfectamente válido, y en 2021 una ley nueva prohíbe vender esa clase de terrenos, la compraventa pasa a tener objeto ilícito y se vuelve absolutamente nula. Por otra parte, cuando varios compradores contratan con un mismo vendedor y el juez anula la compra de uno de ellos, esa sentencia beneficia de inmediato a todos los demás."',
  enunciado=ENUN,
  respuesta='Hay dos errores, cada uno contra un principio común a ambas nulidades.\n\nPrimero, el vicio tiene que existir al momento mismo en que el acto se celebra; uno que surge después no cuenta. No hay nulidad por causa sobreviniente: si la compraventa de 2018 nació válida, la ley de 2021 no puede volverla nula.\n\nSegundo, la nulidad solo aprovecha a quien la obtiene. Si varias personas contrataron con un mismo tercero, que el juez declare nula la relación de una de ellas no beneficia automáticamente a las demás (art. 1690): cada cual debe obtener su propia declaración.',
  elementos=[
   ('El vicio debe existir al celebrarse el acto',
    ['al momento de celebrarse', 'al celebrar el contrato', 'presente al celebrarse', 'existir al celebrar', 'vicio originario'],
    '¿En qué momento tiene que estar presente el defecto para que el acto sea nulo?'),
   ('No hay nulidad por causa sobreviniente: la compraventa nació válida y la ley posterior no la anula',
    ['causa sobreviniente', 'hecho posterior', 'sigue siendo valida', 'nacio valido', 'ley posterior no'],
    '¿Qué pasa con un acto que nació sin vicios si después cambian las circunstancias?'),
   ('La nulidad solo aprovecha a quien la obtiene: cada cual debe obtener su declaración (art. 1690)',
    ['1690', 'solo aprovecha', 'aprovecha a quien la obtiene', 'cada cual debe obtener', 'su propia declaracion', 'cada uno debe pedirla'],
    '¿Qué tendría que hacer cada uno de los otros compradores para quedar libre de su contrato?')],
  articulos='1690',
  objetivo='Evaluar si el alumno detecta dos principios comunes a ambas nulidades: no hay nulidad por causa sobreviniente y la nulidad solo aprovecha a quien la obtiene.',
  respaldo=['IV.B.1.7']),

 # T21.05 Nulidad total y parcial; consecuencial y refleja (0 exámenes)
 dict(sub='T21.05',
  caso='Un alumno escribe: "Si una sola cláusula de un testamento es nula, todo el testamento cae, porque la nulidad de una parte contagia necesariamente el acto entero. Por la misma razón, si se anula la cláusula penal de un contrato, se anula también la obligación principal a la que accede."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, la nulidad puede ser parcial: cuando el vicio afecta solo una parte o una cláusula del acto, el resto subsiste con plena validez. Hay que ponderar si lo viciado toca la esencia del acto o es un accidente tan secundario que las partes lo habrían celebrado igual. En los testamentos el Código resuelve esa ponderación varias veces: la disposición en favor del escribano que autoriza el testamento no vale (art. 1061), pero el resto del testamento sí.\n\nSegundo, lo accesorio sigue la suerte de lo principal, y no a la inversa. Según el art. 1536, la nulidad de la obligación principal acarrea la de la cláusula penal, pero la nulidad de la cláusula penal no acarrea la de la obligación principal.',
  elementos=[
   ('La nulidad puede ser parcial: el resto del acto subsiste válido (ej. art. 1061)',
    ['nulidad parcial', 'resto subsiste', 'resto sigue valido', '1061', 'demas clausulas valen'],
    '¿Qué ocurre con las demás disposiciones del testamento que no tienen ningún vicio?'),
   ('Hay que ponderar si lo viciado toca la esencia del acto o es un accidente secundario',
    ['esencia del acto', 'accidente secundario', 'toca lo esencial', 'habrian celebrado igual', 'clausula secundaria'],
    '¿Qué hay que preguntarse sobre la cláusula viciada para saber si arrastra al resto?'),
   ('La nulidad de la cláusula penal no acarrea la de la obligación principal; solo a la inversa (art. 1536)',
    ['1536', 'no a la inversa', 'accesorio sigue', 'principal sigue valida', 'obligacion principal subsiste'],
    '¿En qué sentido opera el contagio entre lo principal y lo accesorio?')],
  articulos='1061, 1536',
  objetivo='Evaluar si el alumno detecta que la nulidad puede ser parcial y que la nulidad de lo accesorio no arrastra a lo principal.',
  respaldo=['IV.B.1.8', 'IV.B.1.9']),

 # T21.06 Nulidad absoluta: concepto, causales y fundamento (10 exámenes)
 dict(sub='T21.06',
  caso='Un alumno escribe: "Las cuatro causales del art. 1682 que llevan a la sanción más severa son el objeto ilícito, la causa ilícita, la incapacidad relativa y la omisión de las formalidades exigidas en atención al estado o calidad de quienes celebran el acto. Por eso, la venta que hace un menor adulto sin intervención de sus padres adolece de la sanción más severa."',
  enunciado=ENUN,
  respuesta='Hay dos errores, y de ellos se sigue una conclusión equivocada.\n\nPrimero, la causal de nulidad absoluta es la incapacidad absoluta, no la relativa. Los actos de los relativamente incapaces caen en la nulidad relativa.\n\nSegundo, la omisión que produce nulidad absoluta es la de requisitos o formalidades exigidos en consideración a la naturaleza del acto o contrato. Las formalidades exigidas en consideración al estado o calidad de las personas que lo celebran producen nulidad relativa (art. 1682 inc. final).\n\nPor eso, la venta del menor adulto sin intervención de sus padres no es absolutamente nula: el menor adulto es relativamente incapaz y la formalidad omitida se exige en atención a su estado, de modo que la venta adolece de nulidad relativa.',
  elementos=[
   ('La causal es la incapacidad absoluta; la de los relativamente incapaces produce nulidad relativa',
    ['incapacidad absoluta', 'absolutamente incapaces', 'incapaces absolutos', 'no la incapacidad relativa'],
    '¿Qué clase de incapaces enumera realmente el art. 1682 entre los vicios más graves?'),
   ('La omisión que produce nulidad absoluta es la de formalidades exigidas en consideración a la naturaleza del acto',
    ['naturaleza del acto', 'naturaleza del contrato', 'especie del acto', 'en consideracion a la naturaleza'],
    '¿En atención a qué deben exigirse los requisitos omitidos para que la omisión caiga en la causal del art. 1682?'),
   ('La venta del menor adulto adolece de nulidad relativa',
    ['venta nulidad relativa', 'relativamente nula', 'nulidad relativa', 'rescindible', 'nulidad es relativa'],
    '¿Qué sanción corresponde, entonces, a la venta hecha por el menor?')],
  articulos='1682',
  objetivo='Evaluar si el alumno identifica con precisión las causales de nulidad absoluta del art. 1682 y las separa de las de nulidad relativa.',
  respaldo=['IV.B.2.2', 'IV.B.3.2']),

 dict(sub='T21.06',
  caso='Un alumno escribe: "La nulidad absoluta existe para proteger al contratante perjudicado por el vicio, y por eso solo él puede pedirla. En cuanto al error esencial, como el art. 1453 dice que vicia el consentimiento, la doctrina está de acuerdo en que su sanción es la nulidad relativa."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, la nulidad absoluta no protege a nadie en particular: su fundamento está en el interés de la moral y de la ley. Por eso no solo puede pedirla el contratante afectado: puede alegarla todo el que tenga interés en ello, sea parte o tercero, y también el ministerio público en el interés de la moral o de la ley (art. 1683).\n\nSegundo, la sanción del error esencial no es pacífica. Hay tres posiciones: para unos el acto es inexistente, porque el error impide que se forme el consentimiento; otros, entre ellos ALESSANDRI BESA, sostienen que es nulo absolutamente, porque es la sanción más grave que el Código contempla; y LEÓN HURTADO lo sanciona con nulidad relativa, atendiendo a la letra del art. 1453 y a que el error esencial solo afecta el interés particular de los contratantes. Por eso quienes rechazan la inexistencia incluyen el error esencial entre las causales de nulidad absoluta, sin perjuicio de que algunos lo sancionen con nulidad relativa.',
  elementos=[
   ('El fundamento de la nulidad absoluta es el interés de la moral y de la ley, no la protección de una persona',
    ['moral y de la ley', 'interes general', 'no protege a nadie', 'interes de la moral', 'no protege a una persona'],
    '¿Qué interés resguarda la nulidad absoluta, si no es el de uno de los contratantes?'),
   ('Por eso puede pedirla todo el que tenga interés, parte o tercero, y el ministerio público',
    ['todo el que tenga interes', 'cualquier interesado', 'terceros tambien', 'ministerio publico', 'cualquiera con interes'],
    '¿Quiénes, además del afectado, quedan habilitados para alegarla?'),
   ('La sanción del error esencial es discutida: inexistencia, nulidad absoluta o nulidad relativa',
    ['no hay acuerdo', 'tres posiciones', 'acto inexistente', 'nulidad absoluta otros', 'leon hurtado', 'alessandri'],
    '¿Hay acuerdo en la doctrina nacional sobre qué ocurre con el contrato celebrado con esta clase de error?')],
  articulos='1453, 1683',
  objetivo='Evaluar si el alumno detecta que la nulidad absoluta se funda en el interés general, lo que explica quién puede pedirla, y que la sanción del error esencial es discutida.',
  respaldo=['IV.B.2.3', 'IV.B.2.4', 'IV.B.2.2', 'II.A.5.3']),

 # T21.07 Nulidad absoluta: quién la declara o pide (14 exámenes)
 dict(sub='T21.07',
  caso='Un alumno escribe: "El juez debe declarar de oficio la nulidad absoluta cada vez que el vicio quede probado en el juicio, aunque sea con testigos o con un informe pericial. Y cualquier persona puede pedirla, aunque su único interés sea moral: por ejemplo, una vecina indignada porque se celebró un contrato con causa ilícita."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, el juez puede y debe declarar la nulidad absoluta sin petición de parte solo cuando aparece de manifiesto en el acto o contrato (art. 1683). Manifiesto es lo que no exige más prueba que leer el propio instrumento donde consta el acto, sin acudir a ningún otro antecedente del proceso. Si el vicio solo se conoce por testigos o por un peritaje, no es manifiesto.\n\nSegundo, quien pide la nulidad absoluta como interesado debe acreditar un interés real, y ese interés tiene que ser pecuniario. El interés puramente moral queda reservado al ministerio público, que puede pedirla en el interés de la moral o de la ley. La vecina, sin un interés patrimonial, no está habilitada.',
  elementos=[
   ('Solo cabe de oficio si el vicio aparece de manifiesto: basta leer el instrumento, sin otra prueba',
    ['aparece de manifiesto', 'leer el instrumento', 'lectura del instrumento', 'sin otra prueba', 'del propio contrato', 'no es manifiesto'],
    '¿Qué tendría que bastarle al juez para poder actuar sin que nadie se lo pida?'),
   ('El interesado debe tener un interés real y pecuniario',
    ['interes pecuniario', 'interes patrimonial', 'interes economico', 'interes real', 'perjuicio economico'],
    '¿De qué naturaleza tiene que ser el interés de quien pide la nulidad sin ser el ministerio público?'),
   ('El interés puramente moral queda reservado al ministerio público',
    ['ministerio publico', 'reservado al fiscal', 'fiscal judicial', 'solo el ministerio'],
    '¿Quién puede pedirla cuando lo que está en juego es solo el respeto de la moral o de la ley?')],
  articulos='1683',
  objetivo='Evaluar si el alumno detecta qué significa que el vicio aparezca de manifiesto y que el interés del particular debe ser pecuniario, quedando el moral para el ministerio público.',
  respaldo=['IV.B.2.4']),

 dict(sub='T21.07',
  caso='Un alumno escribe: "Como el art. 8° presume que todos conocen la ley, las partes de un contrato con objeto ilícito siempre sabían o debían saber el vicio, así que ninguna de ellas puede alegar la nulidad absoluta. Y si el contrato lo celebró un mandatario que conocía el vicio, el mandante tampoco puede alegarla en ningún caso, porque lo que hace el representante se entiende hecho por el representado."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, la exclusión del art. 1683 exige un conocimiento real y efectivo del vicio, nunca el presunto o ficto del art. 8°. Así lo resolvió la Corte de Pedro Aguirre Cerda en 1988: de no ser así, nunca podrían las partes alegar la nulidad absoluta, porque la ley siempre las consideraría sabedoras del vicio. "Debiendo saber" tampoco es el conocimiento presunto de la ley, sino el que las circunstancias del acto o la condición de los intervinientes le exigían tener a quien actuó.\n\nSegundo, la situación del representado es discutida, y los tribunales se han pronunciado en ambos sentidos. El argumento del alumno (art. 1448) es el de una de las posturas, pero hoy se impone la contraria: el dolo es una determinación personalísima de la voluntad y el representante solo está autorizado para ejecutar actos lícitos, de modo que la prohibición alcanza a quien intervino directamente en el acto, no al representado, salvo que se acredite de modo inequívoco que su propia voluntad concurrió en el vicio.',
  elementos=[
   ('Se exige conocimiento real y efectivo del vicio, no el presunto del art. 8°',
    ['conocimiento real', 'conocimiento efectivo', 'no el presunto', 'no el ficto', 'conocimiento material'],
    '¿Qué clase de conocimiento del vicio le cierra la puerta a una de las partes?'),
   ('Si bastara la presunción, nunca podrían las partes alegar la nulidad absoluta',
    ['nunca podrian alegarla', 'nunca podrian las partes', 'siempre sabedoras', 'nadie podria alegarla', 'pedro aguirre cerda'],
    '¿A qué resultado llevaría aplicar aquí la presunción de conocimiento de la ley?'),
   ('Sobre el representado se impone que puede alegarla, salvo que su propia voluntad concurriera en el vicio, porque el dolo es personalísimo',
    ['dolo personalisimo', 'salvo que su voluntad', 'voluntad concurrio vicio', 'intervino directamente', 'actos licitos', 'alcanza solo al que intervino'],
    '¿Qué postura prevalece hoy cuando solo el representante conocía el defecto, y con qué argumento?')],
  articulos='8, 1448, 1683',
  objetivo='Evaluar si el alumno detecta que la exclusión del art. 1683 exige conocimiento real del vicio y conoce la postura que hoy se impone respecto del representado.',
  respaldo=['IV.B.2.4']),

 # T21.08 Nulidad absoluta: saneamiento y no opera de pleno derecho (9 exámenes)
 dict(sub='T21.08',
  caso='Un alumno escribe: "El plazo de diez años del art. 1683 se cuenta desde que el interesado descubre el vicio, porque antes no podía saber que tenía algo que reclamar. Y mientras ese plazo corre, el acto absolutamente nulo no produce efecto alguno, ya que esta nulidad opera de pleno derecho, sin necesidad de que un juez la declare."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, el cómputo de los diez años parte el día de la celebración del acto nulo, momento desde el cual ya era posible ejercer la acción. Es el mismo criterio que, para la prescripción extintiva, cuenta el plazo desde que la obligación se vuelve exigible (art. 2514 inc. final).\n\nSegundo, para la doctrina tradicional la nulidad absoluta no opera de pleno derecho: necesita ser declarada por el juez, como se deduce de las normas que hablan de la nulidad judicialmente declarada o pronunciada (arts. 1683, 1687 y 1689). Mientras esa sentencia no exista, el acto nulo absolutamente sigue produciendo todos sus efectos. Lo que el alumno afirma es la opinión de quienes discrepan de la doctrina tradicional, y no puede presentarse como una regla asentada.',
  elementos=[
   ('Los diez años se cuentan desde la celebración del acto',
    ['desde la celebracion', 'desde que se celebro', 'dia de la celebracion', 'desde que se firmo', 'desde el contrato'],
    '¿Desde cuándo podía ejercerse la acción de nulidad absoluta, y qué consecuencia tiene eso en el cómputo?'),
   ('Para la doctrina tradicional, la nulidad absoluta requiere declaración judicial (arts. 1687 y 1689)',
    ['declaracion judicial', 'sentencia judicial', 'debe declararla el juez', 'judicialmente declarada', '1687', '1689'],
    '¿Qué hace falta, según la doctrina tradicional, para que el acto deje de valer?'),
   ('Mientras no se declare, el acto sigue produciendo todos sus efectos',
    ['sigue produciendo', 'produce todos sus efectos', 'mientras no se declare', 'presuncion de validez', 'sigue vigente'],
    '¿Qué pasa con el acto entre su celebración y la sentencia?')],
  articulos='1683, 1687, 1689, 2514',
  objetivo='Evaluar si el alumno detecta desde cuándo se cuentan los diez años de la nulidad absoluta y que, para la doctrina tradicional, esta no opera de pleno derecho.',
  respaldo=['IV.B.2.6', 'IV.B.2.7', 'IV.B.1.7']),

 # T21.09 Nulidad relativa: definición, fundamento, causales y características (11 exámenes)
 dict(sub='T21.09',
  caso='Un alumno escribe: "El dolo produce nulidad relativa siempre que haya sido determinante, cualquiera sea la persona que lo cometió. En cambio, el error sobre una calidad accidental de la cosa nunca da lugar a la nulidad relativa, porque solo vicia el consentimiento el error sobre la sustancia."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, el dolo determinante produce nulidad relativa, pero en los actos bilaterales debe ser además obra de una de las partes. No basta que sea determinante, cualquiera sea su autor.\n\nSegundo, el error en una calidad accidental sí produce nulidad relativa cuando esa calidad ha sido el principal motivo de una de las partes para contratar y ese motivo ha sido conocido por la otra. No solo el error sustancial vicia el consentimiento.',
  elementos=[
   ('En los actos bilaterales, el dolo debe ser además obra de una de las partes',
    ['obra de una de las partes', 'obra de una parte', 'actos bilaterales', 'lo cometa la contraparte', 'no de un tercero'],
    '¿Importa quién fue el autor del engaño cuando el acto tiene dos partes?'),
   ('El error en la calidad accidental vicia cuando esa calidad fue el principal motivo para contratar',
    ['principal motivo', 'motivo determinante', 'razon principal', 'motivo para contratar'],
    '¿En qué caso una equivocación sobre una característica secundaria de la cosa sí importa?'),
   ('Y ese motivo debe haber sido conocido por la otra parte',
    ['conocido por la otra', 'la otra parte sabia', 'otra parte lo conocia', 'motivo conocido'],
    '¿Qué debe saber la contraparte para que esa equivocación anule el contrato?')],
  articulos='1682',
  objetivo='Evaluar si el alumno detecta los requisitos del dolo como causal de nulidad relativa en los actos bilaterales y los del error en una calidad accidental.',
  respaldo=['IV.B.3.2']),

 dict(sub='T21.09',
  caso='Un alumno escribe: "La nulidad relativa resguarda el interés de toda la sociedad, igual que la absoluta, solo que con menos fuerza; por eso tampoco puede sanearse por la ratificación. Además, la omisión de la formalidad que la ley exige en consideración a la naturaleza del acto produce nulidad relativa, porque esta es la regla general."',
  enunciado=ENUN,
  respuesta='Hay tres errores.\n\nPrimero, la nulidad relativa no mira al interés general: busca amparar a personas determinadas, en cuyo beneficio la estableció el legislador.\n\nSegundo, precisamente por eso, la nulidad relativa sí puede sanearse por la ratificación de las partes, además de por el transcurso del tiempo (art. 1684). La que no admite ratificación es la absoluta.\n\nTercero, la omisión de formalidades exigidas en consideración a la naturaleza del acto produce nulidad absoluta (art. 1682). Solo la omisión de formalidades exigidas en consideración al estado o calidad de las personas que celebran el acto produce nulidad relativa. Es cierto que la relativa es la regla general, pero solo para los vicios que la ley no sanciona expresamente con nulidad absoluta, y este sí lo está.',
  elementos=[
   ('La nulidad relativa protege a personas determinadas, no el interés general',
    ['personas determinadas', 'ciertas personas', 'proteger a una persona', 'interes particular', 'en cuyo beneficio'],
    '¿A quién busca amparar el legislador con esta especie de nulidad?'),
   ('La nulidad relativa sí puede sanearse por ratificación (art. 1684)',
    ['si puede ratificarse', 'admite ratificacion', 'puede confirmarse', '1684', 'si se sanea por ratificacion'],
    '¿Puede la persona protegida validar el acto si así lo decide?'),
   ('La omisión de formalidades exigidas en atención a la naturaleza del acto produce nulidad absoluta; solo las del estado o calidad de las personas producen relativa',
    ['causal de nulidad absoluta', 'absoluta no relativa', 'calidad de las personas', 'estado o calidad', 'absolutamente nulo'],
    '¿Qué sanción dispone el art. 1682 cuando la formalidad omitida mira al acto mismo y no a quienes lo celebran?')],
  articulos='1682, 1684',
  objetivo='Evaluar si el alumno detecta el fundamento de la nulidad relativa, su saneamiento por ratificación y qué formalidades omitidas la producen.',
  respaldo=['IV.B.3.1', 'IV.B.3.2', 'IV.B.3.3', 'IV.B.3.4', 'IV.B.2.2']),

 # T21.10 Nulidad relativa: quiénes pueden alegarla (11 exámenes)
 dict(sub='T21.10',
  caso='Un alumno escribe: "Si un menor adulto vende su bicicleta a un adulto sin intervención de sus padres, cualquiera de los dos contratantes puede pedir la rescisión, porque ambos son parte del contrato. Y si el menor muere antes de pedirla, ese derecho se extingue con él, porque es personalísimo."',
  enunciado=ENUN,
  respuesta='Hay dos errores.\n\nPrimero, la nulidad relativa solo puede alegarse por aquellos en cuyo beneficio la han establecido las leyes, o por sus herederos o cesionarios (art. 1684). Si quien contrató fue un incapaz, el derecho a pedir la nulidad es suyo, no de la contraparte: el adulto que le compró no puede pedirla.\n\nSegundo, ese derecho no se extingue con la muerte del menor. Sus herederos pueden alegarla en su lugar, porque le suceden en todos sus derechos y obligaciones transmisibles, entre ellos el de pedir la rescisión. También podría transferirse en vida a un cesionario.',
  elementos=[
   ('Solo puede pedirla aquel en cuyo beneficio se estableció: el menor (art. 1684)',
    ['en cuyo beneficio', 'solo el menor', 'solo el incapaz', 'solo el protegido', '1684'],
    '¿A quién protege la exigencia de que intervengan los padres?'),
   ('La contraparte capaz no puede pedir la rescisión',
    ['comprador no puede', 'adulto no puede', 'contraparte no puede', 'el capaz no puede', 'otro contratante no'],
    '¿Qué ocurre, entonces, con el derecho de quien compró la bicicleta?'),
   ('Los herederos del menor pueden alegarla, porque le suceden en ese derecho transmisible',
    ['herederos pueden', 'pasa a los herederos', 'transmisible', 'derecho se transmite', 'tambien cesionarios'],
    '¿Qué pasa con ese derecho cuando su titular fallece sin haberlo ejercido?')],
  articulos='1684',
  objetivo='Evaluar si el alumno detecta que solo el protegido puede alegar la nulidad relativa y que ese derecho pasa a sus herederos.',
  respaldo=['IV.B.3.4']),

 dict(sub='T21.10',
  caso='Un alumno escribe: "Un menor de 17 años que, para comprar una moto, se limita a decirle al vendedor que ya cumplió 18 pierde el derecho a pedir la nulidad, porque engañó al otro contratante. En cambio, si le hubiera mostrado un certificado de nacimiento falsificado, igual podría pedirla, porque al incapaz la ley siempre lo protege."',
  enunciado=ENUN,
  respuesta='El alumno invierte las dos situaciones del art. 1685.\n\nLa simple aserción de mayor edad no inhabilita al incapaz para obtener el pronunciamiento de nulidad: aunque haya dicho que tenía 18, puede pedirla después. La razón está del otro lado: fue el vendedor quien actuó con negligencia, al conformarse con la sola palabra del incapaz sin cerciorarse de su verdadero estado.\n\nEn cambio, si el incapaz empleó dolo para inducir el contrato, como mostrar un certificado falsificado, ni él ni sus herederos o cesionarios pueden alegar la nulidad, porque ya no hay negligencia que reprochar al otro contratante, que no está obligado a presumir la mala fe ajena.',
  elementos=[
   ('La simple aserción de mayor edad no le impide pedir la nulidad (art. 1685)',
    ['simple asercion', 'sola palabra', 'puede pedirla igual', 'no lo inhabilita', 'decirlo no basta', 'si puede pedir'],
    '¿Qué consecuencia tiene, según el art. 1685, que el menor solo haya afirmado su edad?'),
   ('La razón es la negligencia del otro contratante, que no se cercioró',
    ['negligencia del vendedor', 'debio cerciorarse', 'no se cercioro', 'debio verificar', 'no comprobo'],
    '¿Qué se le reprocha al vendedor en ese primer escenario?'),
   ('Con dolo, como un documento falso, ni el incapaz ni sus herederos o cesionarios pueden alegarla',
    ['documento falso inhabilita', 'empleo dolo', 'ni el ni sus herederos', 'no podria pedirla', 'herederos tampoco', 'mala fe'],
    '¿Qué cambia cuando el menor no solo afirma su edad, sino que recurre a una maniobra para engañar?')],
  articulos='1685',
  objetivo='Evaluar si el alumno detecta la distinción del art. 1685 entre la simple aserción de mayor edad y el dolo del incapaz, y su fundamento.',
  respaldo=['IV.B.3.4']),

 # T21.11 Nulidad relativa: saneamiento por el transcurso del tiempo (15 exámenes)
 dict(sub='T21.11',
  caso='Un alumno escribe: "El cuadrienio para pedir la rescisión se cuenta siempre desde la celebración del contrato. Así, si a Lucía la amenazaron gravemente para que firmara una venta en enero de 2023, y las amenazas solo terminaron en marzo de 2024, su plazo para pedir la rescisión vence en enero de 2027."',
  enunciado=ENUN,
  respuesta='El error está en contar el cuadrienio siempre desde la celebración. El art. 1691 distingue según el vicio: en el caso de violencia, el cuadrienio se cuenta desde el día en que esta hubiere cesado; en el caso de error o de dolo, desde la celebración del acto o contrato; y cuando la nulidad proviene de una incapacidad legal, desde el día en que haya cesado esta incapacidad.\n\nLucía sufrió fuerza, así que su plazo corre desde que cesaron las amenazas, en marzo de 2024, y vence en marzo de 2028, no en enero de 2027.',
  elementos=[
   ('En la fuerza, el cuadrienio se cuenta desde que cesa (art. 1691)',
    ['desde que ceso', 'desde que cesa', 'cesaron las amenazas', 'cese de la fuerza', 'cesado la violencia', '1691'],
    '¿Desde cuándo puede Lucía actuar con libertad para reclamar?'),
   ('El plazo de Lucía vence en marzo de 2028',
    ['marzo 2028', 'marzo de 2028', 'vence 2028', 'hasta 2028'],
    '¿En qué fecha vence, entonces, el plazo de Lucía?'),
   ('Desde la celebración solo se cuenta en el error o el dolo; en la incapacidad, desde que esta cesa',
    ['error o dolo', 'error o de dolo', 'cesa la incapacidad', 'termina la incapacidad', 'incapacidad legal'],
    '¿En qué vicios sí se cuenta el plazo desde la firma, y qué pasa con los incapaces?')],
  articulos='1691',
  objetivo='Evaluar si el alumno detecta que el cómputo del cuadrienio depende del vicio y lo aplica a un caso de fuerza.',
  respaldo=['IV.B.3.5']),

 dict(sub='T21.11',
  caso='Un alumno escribe: "Cuando muere quien podía pedir la rescisión, sus herederos mayores de edad tienen siempre un cuadrienio completo y nuevo, contado desde la muerte. Y sus herederos menores de edad tienen cuatro años contados desde que cumplen 18, sin ningún límite, porque la ley quiere protegerlos."',
  enunciado=ENUN,
  respuesta='Hay dos errores, ambos sobre el art. 1692.\n\nPrimero, a los herederos mayores de edad el plazo no se les suspende ni se les renueva. Gozan del cuadrienio entero solo si no había empezado a correr; si ya había empezado, solo del residuo, es decir, de lo que reste.\n\nSegundo, es cierto que a los herederos menores el cuadrienio o su residuo empieza a correr desde que llegan a la mayoría de edad, pero con un tope: pasados diez años desde la celebración del acto o contrato, ya no puede pedirse la nulidad, aunque no se haya completado el cuadrienio.',
  elementos=[
   ('A los mayores el plazo no se suspende: si ya corría, solo tienen el residuo',
    ['residuo', 'tiempo que reste', 'falta del plazo', 'no se suspende', 'no se renueva', 'resto del plazo'],
    '¿Qué pasa si el plazo ya había empezado a correr en vida del causante?'),
   ('Tienen el cuadrienio entero solo si no había empezado a correr (art. 1692)',
    ['no habia empezado', 'no habia comenzado', 'cuadrienio entero', 'plazo entero', '1692'],
    '¿En qué caso sí cuentan los mayores con los cuatro años completos?'),
   ('Para los menores hay un tope de diez años desde la celebración del acto',
    ['tope de diez', 'diez anos desde', 'limite de diez', 'maximo diez', 'desde la celebracion'],
    '¿Hay algún momento después del cual ni siquiera el heredero menor puede pedir la nulidad?')],
  articulos='1692',
  objetivo='Evaluar si el alumno detecta las reglas del art. 1692 sobre el plazo de los herederos mayores y menores, incluido el tope de diez años.',
  respaldo=['IV.B.3.5']),
]

INFORME = dict(
 titulo='Detección de error · Tema 20: Nulidad (tanda 1)',
 puntos=[
  ('Alcance, carácter y especies (IV.B.1.1 a 3)', 'Las especies no se miden por gravedad ni por efectos; las reglas son de orden público, irrenunciables y no rigen el derecho público.'),
  ('Terminología y regla general (IV.B.1.4 y 5)', 'Las tres razones contra la sinonimia de nulidad relativa y rescisión, y la cláusula residual del art. 1682.'),
  ('Diferencias (IV.B.1.6)', 'Declaración de oficio y ministerio público, explicadas por el fundamento de cada especie.'),
  ('Principios comunes (IV.B.1.7)', 'No hay nulidad por causa sobreviniente y la nulidad solo aprovecha a quien la obtiene (art. 1690).'),
  ('Nulidad parcial y accesoria (IV.B.1.8 y 9)', 'La cláusula nula no arrastra siempre al acto (art. 1061) y lo accesorio sigue a lo principal, no al revés (art. 1536).'),
  ('Causales y fundamento de la absoluta (IV.B.2.2 y 3)', 'Incapacidad absoluta y formalidades por la naturaleza del acto; fundamento en la moral y la ley; sanción discutida del error esencial.'),
  ('Quién la declara o pide (IV.B.2.4)', 'Vicio manifiesto, interés pecuniario frente al moral, conocimiento real del vicio y el representado.'),
  ('Saneamiento y pleno derecho (IV.B.2.6 y 7)', 'Cómputo desde la celebración y necesidad de sentencia para la doctrina tradicional.'),
  ('Nulidad relativa (IV.B.3.1 a 3)', 'Dolo de una de las partes, error en la calidad accidental, fundamento, ratificación y formalidades que la producen.'),
  ('Titulares de la relativa (IV.B.3.4)', 'Solo el protegido y sus herederos; las dos situaciones del art. 1685.'),
  ('Saneamiento de la relativa (IV.B.3.5)', 'Cómputo del cuadrienio según el vicio (art. 1691) y plazo de los herederos (art. 1692).'),
 ],
 cobertura=[
  ('Las especies no difieren en efectos ni en gravedad; criterio del art. 1681 inc. 2°', 'Distinción'),
  ('Orden público, art. 1469 y exclusión del derecho público', 'Regla general'),
  ('Rescisión no es sinónimo de nulidad relativa; la relativa es la regla general', 'Distinción doctrinal'),
  ('Declaración de oficio y ministerio público en cada especie', 'Comparación con fundamento'),
  ('Causa sobreviniente; art. 1690', 'Principios'),
  ('Nulidad parcial (art. 1061); art. 1536', 'Regla y excepción'),
  ('Causales del art. 1682: incapacidad absoluta y formalidades por la naturaleza del acto', 'Distinción entre especies'),
  ('Fundamento de la absoluta y sus titulares; sanción discutida del error esencial', 'Fundamento y controversia'),
  ('Vicio manifiesto; interés pecuniario frente al moral', 'Requisitos'),
  ('Conocimiento real del vicio (art. 8°); el representado', 'Regla y controversia'),
  ('Cómputo de los diez años; no opera de pleno derecho', 'Regla y controversia'),
  ('Dolo en los actos bilaterales; error en la calidad accidental', 'Requisitos de las causales'),
  ('Fundamento de la relativa, ratificación y formalidades que la producen', 'Distinción entre especies'),
  ('Solo el protegido; los herederos', 'Regla general'),
  ('Aserción de mayor edad frente al dolo (art. 1685)', 'Excepción y su fundamento'),
  ('Cómputo del cuadrienio en la fuerza (art. 1691)', 'Regla aplicada con fechas'),
  ('Herederos mayores y menores (art. 1692)', 'Regla y tope'),
 ],
 avisos=[
  '<b>Primera de dos tandas:</b> son 17 de las 31 que corresponden a Nulidad en Detección de error (dos en cada subtema de 10 o más exámenes y una en el resto). La tanda 2 completa las 14 que faltan: dos más en cada subtema importante y una más en diferencias y en saneamiento de la absoluta.',
  '<b>De dónde salen los errores:</b> la sección de Nulidad no tiene recuadros de Advertencia, que el prompt sugiere como fuente. Los errores se tomaron de las confusiones que el propio manual aclara (por ejemplo, "esta distinción no mide cuán grave es la ineficacia"), escritas como las diría un alumno.',
  '<b>Prueba propia de este tipo:</b> además del control de siempre, cada pregunta se probó con una respuesta correcta en palabras propias (aprueba las 17) y con el párrafo equivocado del alumno copiado como respuesta (no obtiene ningún elemento en ninguna).',
  '<b>Puntos discutidos, presentados como tales:</b> la sanción del error esencial (aj-det-011), el representado (013, con la postura que hoy se impone según el manual) y el pleno derecho (014, como doctrina tradicional). En la terminología (006) el error se corrige con las tres razones del manual contra la sinonimia, atribuidas a un sector de la doctrina, como lo hace el manual.',
  '<b>Un caso cercano a un ejemplo del manual</b> (tú decides): aj-det-018, el menor que dice tener 18 o muestra un documento falso, es el mismo punto de la guitarra eléctrica de Matías, con otros hechos (una moto y un certificado de nacimiento).',
 ],
 redundancia='Dentro de la tanda no hay dos preguntas que evalúen el mismo elemento. Las tres que tocan las causales separan ángulos: las causales de la absoluta (010), el fundamento de la relativa con las formalidades por la naturaleza del acto como causal absoluta (016) y el dolo y el error en la calidad accidental (015). Diferencias (007) mira la declaración de oficio y el ministerio público, sin repetir la ratificación ni los plazos, que tienen sus propias preguntas (016, 014, 019, 020). Varias preguntas tratan el mismo punto que alguna de Aplicación (conocimiento real del vicio, art. 1685, cómputo del cuadrienio), pero desde otro ángulo: aquí se detecta y corrige un error, no se resuelve un caso, que es lo que admite el núcleo entre tipos distintos.',
)
