# Evaluación de Acto Jurídico, tanda 2: Aplicación del tema 20 (Nulidad), IV.B.1 a IV.B.3.5.
# Completa la tanda 1 (lote_aplic1.py, aj-aplic-004 a 020) con la regla de cantidad del
# 2026-10-10: cuatro preguntas por tipo en los subtemas de 10 o más exámenes y dos en el resto
# (en los subtemas con 0 exámenes basta una, y ya la tienen). Sin repetir los elementos que
# evalúa la tanda 1 (ver INFORME['redundancia']).
#
# Formato de cada ítem: el mismo de lote_aplic1.py.
TABLA = 'Aplicación'
PREFIJO = 'aj-aplic'

ITEMS = [
 # T21.01 Reglas, concepto general y especies de nulidad (15 exámenes: 4 preguntas; la tanda 1 dejó 2)
 dict(sub='T21.01',
  caso='El mismo día llegan tres consultas al estudio de la abogada Pilar Rojas. (1) Don Mario le envió a su arrendataria un desahucio para poner término al arriendo de una casa sin plazo fijo, y ahora sostiene que lo firmó bajo amenazas graves. La arrendataria responde que las reglas del Código Civil sobre nulidad no sirven para atacarlo, "porque el desahucio no es un contrato, sino algo que hace una persona sola". (2) En un juicio ejecutivo, la demanda se le notificó a Rosa en un domicilio equivocado. Su sobrino, estudiante de derecho, le aconseja pedir la nulidad absoluta de esa notificación conforme al Código Civil, "que da diez años de plazo". (3) Tomás pactó con su prestamista un interés que excede en más de una mitad al interés corriente que regía al celebrar el préstamo, y quiere que se declare nulo el mutuo completo.',
  enunciado='¿Qué debería responder la abogada en cada consulta? Fundamente.',
  respuesta='(1) La arrendataria no tiene razón. Las reglas generales de la nulidad (arts. 1681 a 1697) tienen alcance general: rigen para cualquier acto jurídico, unilateral o bilateral. El desahucio es un acto unilateral, porque basta la voluntad de quien lo da, y eso no lo deja fuera de esas reglas.\n\n(2) El consejo del sobrino es equivocado. Las reglas de nulidad del Código Civil se aplican en el derecho privado, pero no se extienden al derecho público, que tiene reglas propias y distintas en cada rama: la nulidad en el derecho procesal no es la misma que la del Código Civil. La notificación es una actuación procesal, y su nulidad se rige por las reglas del derecho procesal, no por el plazo de diez años del art. 1683.\n\n(3) Tomás no puede obtener la nulidad del mutuo. Las reglas de la nulidad rigen a menos que una disposición expresa consulte una sanción distinta, y eso es lo que ocurre aquí: cuando el interés convencional excede en una mitad al interés corriente al tiempo de la convención, el juez lo reduce a ese interés corriente (art. 2206). La sanción no es la nulidad, sino la simple reducción del interés, y el mutuo sigue valiendo.',
  elementos=[
   ('Las reglas de la nulidad rigen para todo acto jurídico, también los unilaterales como el desahucio',
    ['tambien actos unilaterales', 'unilateral o bilateral', 'cualquier acto juridico', 'alcance general', 'aunque sea unilateral', 'acto unilateral tambien'],
    '¿Importa, para aplicar el Título XX del Libro IV, cuántas voluntades se necesitan para que el acto nazca?'),
   ('Las reglas de nulidad del Código Civil no se extienden al derecho público, como el procesal, que tiene reglas propias',
    ['no se extienden al derecho publico', 'derecho publico reglas propias', 'nulidad procesal', 'reglas del derecho procesal', 'actuacion procesal', 'procesal propias reglas'],
    '¿Rigen las normas civiles sobre nulidad para los actos que se realizan dentro de un juicio?'),
   ('Tomás no obtiene la nulidad del mutuo: la ley fija otra sanción, la reducción del interés (art. 2206)',
    ['2206', 'reduce a ese interes', 'reduccion del interes', 'sancion distinta', 'otra sancion', 'mutuo sigue valiendo'],
    '¿Qué consecuencia prevé la ley, específicamente, para un interés pactado por sobre ese límite?')],
  articulos='1681 a 1697, 1683, 2206',
  objetivo='Evaluar si el alumno aplica el alcance de las reglas de la nulidad: rigen para actos unilaterales y bilaterales, no se extienden al derecho público y ceden ante una disposición expresa que fija una sanción distinta.',
  respaldo=['IV.B.1.1', 'IV.B.2.6', 'IV.C.3', 'II.A.3.1']),

 dict(sub='T21.01',
  caso='Al morir don Hugo, sus hijos revisan dos actos de la familia. El primero es el testamento solemne de don Hugo, que se otorgó con menos testigos de los que exige la ley. El segundo es la venta que su nieto Martín, de 17 años, le hizo a un compañero de su consola de videojuegos, sin intervención de sus padres. Un nieto mayor opina que "los dos actos tienen el mismo problema: les faltó algo que la ley pedía, así que la nulidad tiene que ser la misma".',
  enunciado='¿Es la misma nulidad en ambos actos? Explique, con el criterio que usa el Código para separar las especies de nulidad, cuál corresponde a cada uno y qué consecuencia tiene ese criterio en el alcance de cada nulidad.',
  respuesta='No es la misma. Es cierto que a ambos actos les falta un requisito que la ley prescribe para su valor (art. 1681 inc. 1°), pero el Código distingue las especies según la razón por la que se exige el requisito omitido (art. 1681 inc. 2°).\n\nEl testamento adolece de nulidad absoluta. Los testigos del testamento solemne (art. 1014) son una solemnidad de validez, exigida en atención a la naturaleza del acto, cualquiera sea quien lo otorgue; la omisión de requisitos o formalidades exigidos en consideración a la naturaleza del acto es causal de nulidad absoluta (art. 1682).\n\nLa venta de Martín adolece de nulidad relativa. Martín es menor adulto, relativamente incapaz, y el requisito que falta se exige en atención a la calidad o estado de la persona que celebra el acto, para protegerla. Los actos de los relativamente incapaces caen en la nulidad relativa.\n\nEse criterio explica el alcance de cada una. En la absoluta, el acto está mal formado en sí mismo, con independencia de quién lo celebre: su nulidad es objetiva y alcanza a todos (erga omnes). En la relativa, el acto no tiene nada de reprochable en su estructura; lo que falla es una exigencia pensada para proteger a Martín, y por eso el vicio es subjetivo y la nulidad solo opera respecto de Martín.',
  elementos=[
   ('El testamento es absolutamente nulo: los testigos se exigen en atención a la naturaleza del acto',
    ['testamento absolutamente nulo', 'naturaleza del acto', 'solemnidad de validez', 'especie del acto', 'testamento nulidad absoluta', 'atencion a la naturaleza'],
    '¿Los testigos se piden por quién es don Hugo, o por el tipo de acto que está otorgando?'),
   ('La venta de Martín es relativamente nula: el requisito se exige en atención a la calidad o estado de la parte',
    ['venta nulidad relativa', 'calidad o estado', 'estado de las partes', 'relativamente incapaz', 'incapaz relativo', 'proteger a martin'],
    '¿En consideración a qué se exige la intervención de los padres en la venta del nieto?'),
   ('La nulidad absoluta es objetiva y alcanza a todos; la relativa es subjetiva y solo opera respecto de la persona protegida',
    ['erga omnes', 'alcanza a todos', 'afecta a todos', 'absoluta objetiva', 'relativa subjetiva', 'vicio es subjetivo'],
    '¿Dónde está el vicio en cada caso: en el acto mismo o en una de las personas, y qué cambia eso respecto de a quiénes alcanza la nulidad?')],
  articulos='1014, 1681, 1682',
  objetivo='Evaluar si el alumno aplica el criterio del art. 1681 inc. 2° para clasificar dos vicios y explica por qué la nulidad absoluta es objetiva y la relativa subjetiva.',
  respaldo=['IV.B.1.3', 'IV.B.2.2', 'IV.B.3.2', 'II.E.2']),

 # T21.06 Nulidad absoluta: concepto, causales y fundamento (10 exámenes: 4; la tanda 1 dejó 2)
 dict(sub='T21.06',
  caso='Andrea le entrega su camioneta a Bruno y ambos firman un documento muy mal redactado. Andrea entendía que se la estaba arrendando por un año, y tomó los $6.000.000 que Bruno le pagó como la renta anticipada. Bruno, en cambio, entendía que se la estaba comprando, y que esa suma era el precio. Cuando Andrea pide la devolución de la camioneta al cabo del año, descubren el malentendido. El abogado de Andrea consulta a tres profesores de derecho civil y recibe tres respuestas distintas sobre la sanción del contrato.',
  enunciado='¿Qué clase de error sufrieron las partes? ¿Cuáles son las tres respuestas posibles sobre la sanción del contrato y en qué se funda cada una?',
  respuesta='Es un error esencial u obstáculo (art. 1453): recae sobre la especie de acto o contrato que se celebra. Cada parte quiso exactamente lo que declaró, pero lo que quiso una (arrendar) no tiene nada que ver con lo que quiso la otra (comprar): el desajuste no está dentro de ninguna de ellas, sino entre las dos.\n\nSu sanción es una discusión clásica, y la doctrina nacional está dividida en tres opiniones:\n\n(1) Inexistencia. Si el error impide que se forme el consentimiento, falta un requisito sin el cual el acto ni siquiera nace: el contrato es jurídicamente inexistente.\n\n(2) Nulidad absoluta. Otros comparten el punto de partida, pero estiman que el Código no recoge la inexistencia; como la sanción más grave que la ley sí contempla, incluso para los actos en que falta el consentimiento, es la nulidad absoluta, esa sería la sanción. Es la posición de ALESSANDRI BESA, y en el mismo sentido se cita el fallo Torres con Fisco (Corte Suprema, 1945). Por eso quienes rechazan la inexistencia agregan el error esencial a las causales de nulidad absoluta.\n\n(3) Nulidad relativa. LEÓN HURTADO se queda con la letra de la ley: el art. 1453 dice que este error "vicia el consentimiento", y según el art. 1682 inc. final todo vicio que no esté sancionado con nulidad absoluta produce nulidad relativa. Además, el error esencial solo afecta el interés particular de los contratantes, mientras que la nulidad absoluta protege el interés general y la moral.',
  elementos=[
   ('Es un error esencial u obstáculo, sobre la especie de contrato (art. 1453)',
    ['error esencial', 'error obstaculo', 'obstativo', '1453', 'especie de contrato', 'naturaleza del contrato'],
    '¿Sobre qué recayó el desacuerdo: sobre la cosa, sobre sus calidades o sobre el tipo de negocio que cada uno creyó celebrar?'),
   ('Primera posición: el contrato es inexistente, porque el error impide que se forme el consentimiento',
    ['acto inexistente', 'contrato inexistente', 'contrato no nace', 'no llega a nacer', 'no se forma consentimiento', 'no hubo consentimiento'],
    '¿Qué sanción corresponde si se piensa que aquí nunca llegó a haber acuerdo de voluntades y se acepta una sanción que el Código no nombra?'),
   ('Segunda posición (ALESSANDRI BESA): nulidad absoluta, la sanción más grave que el Código sí contempla',
    ['alessandri', 'sancion mas grave', 'torres con fisco', 'grave que contempla', 'no recoge la inexistencia'],
    '¿Qué sanción defienden quienes comparten ese punto de partida, pero niegan que el Código contemple algo distinto de las sanciones que nombra?'),
   ('Tercera posición (LEÓN HURTADO): nulidad relativa, porque el art. 1453 dice que el error vicia el consentimiento',
    ['leon hurtado', 'vicia el consentimiento', 'interes particular', 'otra especie de vicio', 'letra de la ley'],
    '¿Qué sanción resulta si uno se atiene a la letra del artículo que regula este error y a la cláusula residual del Código?')],
  articulos='1453, 1682',
  objetivo='Evaluar si el alumno identifica un error esencial en un caso y aplica las tres posiciones sobre su sanción, que explican por qué algunos lo incluyen entre las causales de nulidad absoluta.',
  respaldo=['II.A.5.3', 'IV.B.2.2']),

 dict(sub='T21.06',
  caso='Don Eliseo, de 85 años, aparece firmando la venta de su auto a su sobrino Gerardo. En realidad, Gerardo le tomó la mano por la fuerza y la guió sobre el papel mientras don Eliseo se resistía. Muerto don Eliseo, sus hijos demandan. Gerardo se defiende: "a lo más habrá habido fuerza, y la fuerza solo produce nulidad relativa".',
  enunciado='¿Tiene razón Gerardo? Determine qué sanción corresponde a esa venta y explique si la doctrina está de acuerdo.',
  respuesta='Gerardo no tiene razón. La fuerza que vicia el consentimiento y produce nulidad relativa es la fuerza moral: la amenaza injusta, grave y determinante (art. 1682 inc. final). Lo que sufrió don Eliseo fue fuerza física: Gerardo movió su mano, y don Eliseo no consintió ni siquiera bajo presión. En la fuerza física no hay voluntad, así que no se trata de un consentimiento viciado sino de uno que falta.\n\nLa sanción depende de la posición que se tome frente a la inexistencia. Para quienes la aceptan en nuestro derecho, la venta es inexistente, porque le falta la voluntad, un requisito sin el cual el acto no nace. Para quienes creen que el Código no recoge la inexistencia, la venta es nula absolutamente: agregan la falta de voluntad a las causales de nulidad absoluta del art. 1682.',
  elementos=[
   ('Es fuerza física: no hay voluntad viciada sino falta de voluntad, así que no corresponde la nulidad relativa',
    ['fuerza fisica', 'no hay voluntad', 'falta de voluntad', 'sin voluntad', 'no es fuerza moral', 'gerardo no tiene razon'],
    '¿Llegó don Eliseo a querer la venta, aunque fuera presionado, o simplemente no la quiso?'),
   ('Para quienes aceptan la inexistencia, la venta es inexistente',
    ['venta inexistente', 'acto inexistente', 'venta no nace', 'no llega a nacer', 'nunca existio'],
    '¿Qué sanción corresponde según quienes creen que un acto sin uno de sus requisitos de existencia no alcanza a formarse?'),
   ('Para quienes rechazan la inexistencia, la venta es absolutamente nula, porque agregan la falta de voluntad a las causales del art. 1682',
    ['nulidad absoluta', 'absolutamente nula', 'agregan causales', 'nula absolutamente', 'rechazan la inexistencia'],
    '¿Qué sanción le aplican quienes niegan que el Código distinga otra categoría fuera de la nulidad?')],
  articulos='1682',
  objetivo='Evaluar si el alumno distingue la fuerza física de la fuerza moral y aplica las causales de nulidad absoluta que agregan quienes rechazan la inexistencia.',
  respaldo=['II.A.7.6', 'IV.B.2.2']),

 # T21.07 Nulidad absoluta: quién la declara o pide (14 exámenes: 4; la tanda 1 dejó 2)
 dict(sub='T21.07',
  caso='Esteban demanda a Felipe el pago de $10.000.000 que este le prometió en un contrato escrito. El contrato dice que el pago es "por servicios de asesoría". Durante el juicio, un testigo declara que, en realidad, el dinero era la recompensa por haber amenazado a un competidor de Felipe para que se retirara de una licitación. Ninguna de las partes ha pedido la nulidad. Enterado del caso por la prensa, un fiscal del Ministerio Público que investiga esas amenazas anuncia que pedirá ante el juez civil la nulidad absoluta del contrato "en el interés de la moral".',
  enunciado='¿Puede el juez declarar de oficio la nulidad absoluta del contrato? ¿Está habilitado ese fiscal para pedirla? Fundamente.',
  respuesta='La promesa de dar algo en recompensa de un crimen o de un hecho inmoral tiene causa ilícita (art. 1467), causal de nulidad absoluta (art. 1682).\n\nAun así, el juez no puede declararla de oficio. La nulidad absoluta puede y debe declararse sin petición de parte solo "cuando aparece de manifiesto en el acto o contrato" (art. 1683), es decir, cuando basta leer el propio instrumento, sin acudir a ningún otro antecedente del proceso, para darla por establecida. Aquí el contrato habla de servicios de asesoría: el vicio solo se conoce por la declaración de un testigo. No es manifiesto, de modo que la nulidad tendrá que pedirla alguien habilitado.\n\nEse fiscal no lo está. El ministerio público que puede pedir la nulidad absoluta en el interés de la moral o de la ley (art. 1683) es el organismo auxiliar de la administración de justicia que regula el art. 350 COT, integrado por el fiscal de la Corte Suprema y los fiscales de las Cortes de Apelaciones, y no el organismo del mismo nombre que participa en el proceso penal. Podría pedirla, en cambio, el fiscal judicial de la Corte respectiva, o cualquier persona con un interés pecuniario en ello.',
  elementos=[
   ('El vicio no aparece de manifiesto: solo se conoce por la prueba de testigos, no por la sola lectura del contrato',
    ['no aparece de manifiesto', 'no es manifiesto', 'leyendo el instrumento', 'lectura del instrumento', 'requiere otra prueba', 'otro antecedente'],
    '¿Qué tendría que poder ver el juez, y en qué documento, para actuar sin que nadie se lo pida?'),
   ('Por eso el juez no puede declararla de oficio',
    ['juez no puede declararla', 'no puede de oficio', 'no cabe de oficio', 'no la puede declarar', 'tendra que pedirla'],
    '¿Basta que el vicio quede acreditado en el proceso para que el tribunal actúe por iniciativa propia?'),
   ('Ese fiscal no está habilitado: el ministerio público del art. 1683 es el del art. 350 COT (fiscal judicial), no el que actúa en el proceso penal',
    ['350 cot', 'fiscal judicial', 'auxiliar administracion justicia', 'fiscales de las cortes', 'no el del proceso penal', 'fiscal de la corte'],
    '¿A qué organismo se refiere el Código Civil cuando habla del ministerio público, y es el mismo que investiga delitos?')],
  articulos='1467, 1682, 1683, 350 COT',
  objetivo='Evaluar si el alumno aplica el requisito de que el vicio aparezca de manifiesto para la declaración de oficio y distingue el ministerio público del art. 1683 del que actúa en el proceso penal.',
  respaldo=['IV.B.2.4', 'IV.B.2.2', 'II.D.4']),

 dict(sub='T21.07',
  caso='En 2023, Sebastián, comerciante sin formación jurídica, le compra a Francisco, abogado, en $15.000.000, los derechos que a Francisco le corresponderán en la herencia de su padre, que todavía vive. Sebastián no tenía idea de que la ley prohíbe ese contrato, y nada en el negocio se lo advertía; Francisco sí lo sabía. En 2024 Francisco muere, y sus hijos quieren que se declare la nulidad absoluta del contrato. Sebastián, por su parte, también la quiere, para recuperar su dinero.',
  enunciado='¿Puede Sebastián pedir la nulidad absoluta, si nadie puede alegar ignorancia de la ley? ¿Pueden pedirla los hijos de Francisco? Fundamente.',
  respuesta='El contrato tiene objeto ilícito: el derecho de suceder por causa de muerte a una persona viva no puede ser objeto de un contrato (art. 1463), y eso produce nulidad absoluta.\n\nSebastián sí puede. El art. 1683 excluye solo al que celebró el contrato "sabiendo o debiendo saber el vicio que lo invalidaba", y ese conocimiento debe ser real y efectivo, nunca el presunto o ficto del art. 8°. Así lo resolvió la Corte de Pedro Aguirre Cerda en 1988: de no ser así, nunca podrían las partes alegar la nulidad absoluta, porque la ley siempre las consideraría sabedoras del vicio. Sebastián no conocía la prohibición ni las circunstancias le permitían advertirla: la ley admite aquí el error de derecho.\n\nSobre los hijos de Francisco, que sí sabía, la doctrina y la jurisprudencia no responden igual. Para una postura pueden alegarla: la prohibición es una verdadera inhabilidad y, como regla de excepción, debe interpretarse restrictivamente; si su letra no comprende a los herederos, no puede extenderse a ellos. Para la otra no pueden: no han podido adquirir por sucesión un derecho que su causante no tenía; y si cuando el dolo es imputable a un incapaz la ley no permite alegar la nulidad ni a él ni a sus herederos (art. 1685), con mayor razón la prohibición debe comprender a los herederos de las personas capaces.',
  elementos=[
   ('Sebastián puede: la exclusión exige conocimiento real y efectivo del vicio, no el conocimiento presunto de la ley del art. 8°',
    ['conocimiento real', 'conocimiento efectivo', 'no el ficto', 'sebastian esta habilitado', 'error de derecho', 'conocimiento material'],
    '¿Qué clase de conocimiento del vicio exige la ley para cerrarle la puerta a una de las partes?'),
   ('Postura que admite a los herederos: la prohibición es una inhabilidad de excepción, de interpretación restrictiva, cuya letra no los comprende',
    ['interpretacion restrictiva', 'inhabilidad', 'regla de excepcion', 'letra no comprende', 'no se extiende a herederos'],
    '¿Qué argumento da quien sostiene que los hijos sí pueden, a partir de cómo deben leerse las normas que restringen derechos?'),
   ('Postura que los excluye: no adquieren un derecho que el causante no tenía, y el art. 1685 los excluye con mayor razón',
    ['1685', 'causante no tenia', 'no adquieren por sucesion', 'con mayor razon', 'derecho que no tenia'],
    '¿Qué argumento da quien sostiene que los hijos no pueden, a partir de lo que reciben por la muerte de su padre?')],
  articulos='8, 1463, 1683, 1685',
  objetivo='Evaluar si el alumno aplica la exclusión del art. 1683 distinguiendo el conocimiento real del vicio del presunto, y expone las dos posturas sobre los herederos de quien contrató a sabiendas.',
  respaldo=['IV.B.2.4', 'II.C.4.2']),

 # T21.09 Nulidad relativa: definición, fundamento, causales y características (11 exámenes: 4; la tanda 1 dejó 2)
 dict(sub='T21.09',
  caso='Daniela celebra dos contratos en el mismo mes. (1) Contrata los servicios de Rodrigo para llevar la contabilidad de su empresa, convencida de que es contador titulado, porque así figuraba en un directorio antiguo que ella consultó; Rodrigo nunca dijo serlo, y en realidad no terminó la carrera. Para Daniela, el título era la razón de contratarlo. (2) Vende su casa en Valdivia en $40.000.000, cuando su justo precio al momento de la venta era de $100.000.000.',
  enunciado='¿Puede Daniela pedir la nulidad de cada contrato? En su caso, ¿de qué especie y con qué consecuencias para la otra parte?',
  respuesta='(1) Sí. Es un error en la persona: Daniela se equivocó sobre una cualidad de Rodrigo, su título profesional. Por regla general este error no vicia el consentimiento, salvo que la consideración de esa persona sea la causa principal del contrato (art. 1455). Un contrato de servicios de confianza como este se celebra en consideración a la persona, y el título era la razón de contratarlo, así que el error vicia el consentimiento y el contrato adolece de nulidad relativa (art. 1682 inc. final). Como Rodrigo no tiene la culpa del error, declarada la nulidad tiene derecho a que se le indemnicen los perjuicios en que haya incurrido de buena fe (art. 1455 inc. 2°).\n\n(2) Sí. Daniela sufrió lesión enorme: el vendedor la sufre cuando el precio que recibe es inferior a la mitad del justo precio de la cosa que vende, referido al tiempo del contrato (art. 1889), y $40.000.000 es menos de la mitad de $100.000.000. La lesión, en los casos previstos por la ley en que la sanción es la rescisión, como la compraventa de inmuebles, produce nulidad relativa.',
  elementos=[
   ('El error sobre el título de Rodrigo es error en la persona que vicia el consentimiento, porque la persona era la causa principal del contrato: nulidad relativa',
    ['error sobre la persona', '1455', 'causa principal', 'intuito personae', 'consideracion de la persona', 'cualidad de rodrigo'],
    '¿Sobre quién o sobre qué se equivocó Daniela, y cuándo ese tipo de equivocación importa para la ley?'),
   ('Rodrigo, que actuó de buena fe, tiene derecho a que se le indemnicen los perjuicios',
    ['indemnizacion a rodrigo', 'indemnizar a rodrigo', 'derecho a ser indemnizado', 'rodrigo indemnizado', 'perjuicios de buena fe'],
    '¿Queda Rodrigo sin protección si se anula un contrato por un error del que él no es responsable?'),
   ('La venta tiene lesión enorme (precio inferior a la mitad del justo precio, art. 1889) y se rescinde: nulidad relativa',
    ['lesion enorme', '1889', 'menos de la mitad', 'inferior a la mitad', 'rescision por lesion', 'mitad del justo precio'],
    '¿Qué relación hay entre lo que Daniela recibió y lo que valía su casa, y qué consecuencia le da la ley a esa diferencia en la venta de inmuebles?')],
  articulos='1455, 1682, 1889',
  objetivo='Evaluar si el alumno aplica dos causales de nulidad relativa menos obvias que el error sustancial y el dolo: el error en la persona, con la indemnización al contratante de buena fe, y la lesión enorme en la compraventa de inmuebles.',
  respaldo=['IV.B.3.2', 'II.A.5.3', 'IV.C.3', 'IV.C.4']),

 dict(sub='T21.09',
  caso='Tres ventas en Talca. (1) Ignacio le vende su moto a Marcela porque un exsocio de ella, sin que Marcela lo sepa ni gane nada con ello, lo amenaza gravemente para que venda. (2) Rocío, declarada en interdicción por disipación en 2024, vende al año siguiente su piano sin intervención de su curador. (3) Tomás, hermano de Rocío, apuesta todos los meses gran parte de su sueldo, pero nadie ha pedido su interdicción; también vende su auto.',
  enunciado='¿Adolece de nulidad cada una de las tres ventas? En su caso, ¿de qué especie y por qué?',
  respuesta='(1) Sí, de nulidad relativa. Para que la fuerza vicie el consentimiento no es necesario que la ejerza aquel que es beneficiado por ella; basta que se haya empleado por cualquier persona con el objeto de obtener el consentimiento (art. 1457). Es la gran diferencia con el dolo, que en los actos bilaterales debe ser obra de una de las partes. La fuerza no está entre las causales de nulidad absoluta, así que produce nulidad relativa (art. 1682 inc. final).\n\n(2) Sí, de nulidad relativa. Los disipadores que se hallan bajo interdicción de administrar lo suyo son relativamente incapaces (art. 1447 inc. 3°), y los actos de los relativamente incapaces adolecen de nulidad relativa.\n\n(3) No: la venta de Tomás es válida. Ser disipador no basta para ser incapaz; solo lo es el disipador declarado en interdicción por decreto judicial. Mientras eso no ocurra, conserva toda su capacidad.',
  elementos=[
   ('La venta de Ignacio es relativamente nula: la fuerza vicia aunque la ejerza cualquier persona, no solo la otra parte (art. 1457)',
    ['1457', 'cualquier persona', 'aunque sea un tercero', 'la ejerza cualquiera', 'da igual quien', 'diferencia con el dolo'],
    '¿Importa quién amenazó a Ignacio, si la compradora no tuvo nada que ver?'),
   ('La venta de Rocío es relativamente nula: la disipadora bajo interdicción es relativamente incapaz',
    ['relativamente incapaz', 'incapacidad relativa', 'rocio es incapaz', 'incapaz relativa', '1447'],
    '¿En qué situación queda la capacidad de Rocío después del decreto judicial?'),
   ('La venta de Tomás es válida: sin decreto de interdicción conserva toda su capacidad',
    ['tomas es capaz', 'plenamente capaz', 'venta es valida', 'conserva su capacidad', 'sin decreto judicial', 'no esta interdicto'],
    '¿Basta gastar de forma desordenada para perder la capacidad de contratar?')],
  articulos='1447 inc. 3°, 1457, 1682',
  objetivo='Evaluar si el alumno aplica las causales de nulidad relativa a la fuerza de un tercero y a la incapacidad del disipador, distinguiendo al disipador interdicto del que no lo está.',
  respaldo=['IV.B.3.2', 'II.A.7.4', 'II.B.3.2', 'II.B.3']),

 # T21.10 Nulidad relativa: quiénes pueden alegarla (11 exámenes: la tanda 1 dejó 2; esta suma 1, ver avisos)
 dict(sub='T21.10',
  caso='Gonzalo está bajo interdicción por disipación desde 2022. En 2025 celebra, sin su curador, dos ventas: le vende su colección de vinos a Paula, a quien le asegura de palabra que "esa interdicción ya se alzó"; y le vende su caballo a Rubén, a quien le exhibe una resolución judicial que él mismo falsificó para aparentar que lo habían rehabilitado. Meses después, Gonzalo le cede a su amigo Lucas, por acto entre vivos, los derechos que le corresponden en ambos contratos. Un fiscal judicial que se entera de la falsificación quiere pedir la rescisión de la venta a Rubén en el solo interés de la ley.',
  enunciado='¿Puede Gonzalo pedir la nulidad de cada venta? ¿Y Lucas? ¿Y el fiscal judicial? Fundamente.',
  respuesta='Gonzalo, disipador bajo interdicción, es relativamente incapaz, y por eso, en principio, ambas ventas adolecen de nulidad relativa. Pero el art. 1685 distingue dos situaciones.\n\nVenta a Paula: Gonzalo sí puede pedir la nulidad. La aserción de no existir la interdicción no inhabilita al incapaz para obtener el pronunciamiento de nulidad (art. 1685, segunda parte). La negligencia es de Paula, que se conformó con su palabra sin cerciorarse de su verdadero estado.\n\nVenta a Rubén: Gonzalo no puede. No hubo una simple aserción, sino dolo del incapaz para inducir el contrato, y en ese caso ni él ni sus herederos o cesionarios pueden alegar la nulidad (art. 1685, primera parte): ya no hay negligencia que reprocharle a Rubén, que no está obligado a presumir la mala fe ajena.\n\nLucas, como cesionario, puede pedirla respecto de la venta a Paula, porque recibe junto con los derechos del contrato el derecho a demandar la rescisión; pero no respecto de la venta a Rubén, porque el art. 1685 excluye también a los cesionarios del incapaz que actuó con dolo.\n\nEl fiscal judicial no puede: la nulidad relativa no puede pedirse por el ministerio público en el solo interés de la ley (art. 1684), porque no protege el interés general sino a personas determinadas.',
  elementos=[
   ('Venta a Paula: la simple aserción de no estar interdicto no impide a Gonzalo pedir la nulidad (art. 1685, segunda parte)',
    ['simple asercion', 'mera afirmacion', 'solo lo afirmo', 'paula debio cerciorarse', 'negligencia de paula', 'asercion no inhabilita'],
    '¿Qué diferencia hay entre lo que hizo Gonzalo con Paula y lo que hizo con Rubén, y a quién le reprocha la ley no haber verificado?'),
   ('Venta a Rubén: hubo dolo del incapaz, y ni él ni sus herederos o cesionarios pueden alegarla (art. 1685, primera parte)',
    ['dolo del incapaz', 'hubo dolo', 'gonzalo no puede', 'actuo con dolo', 'no puede respecto de ruben'],
    '¿Cómo califica la ley la conducta de Gonzalo frente a Rubén, y qué efecto tiene sobre su derecho a pedir la nulidad?'),
   ('Lucas, cesionario, puede pedirla respecto de la venta a Paula, pero no de la venta a Rubén',
    ['cesionario respecto de paula', 'lucas respecto de paula', 'lucas no respecto de ruben', 'lucas paula si', 'lucas ruben no'],
    '¿Qué recibe quien adquiere de Gonzalo los derechos de esos contratos, y lo recibe en ambos casos?'),
   ('El fiscal judicial no puede: la nulidad relativa no se pide por el ministerio público en el solo interés de la ley (art. 1684)',
    ['1684', 'fiscal no puede', 'ministerio publico no puede', 'personas determinadas', 'no protege el interes general'],
    '¿A quién protege esta clase de nulidad, y qué consecuencia tiene eso para la intervención de un órgano público?')],
  articulos='1447 inc. 3°, 1684, 1685',
  objetivo='Evaluar si el alumno aplica el art. 1685 a la aserción de no existir la interdicción, extiende la exclusión por dolo a los cesionarios y descarta al ministerio público en la nulidad relativa.',
  respaldo=['IV.B.3.4', 'II.B.3.2', 'II.B.3']),

 # T21.11 Nulidad relativa: saneamiento por el transcurso del tiempo (15 exámenes: 4; la tanda 1 dejó 2)
 dict(sub='T21.11',
  caso='Hoy es 1 de octubre de 2026. Dos personas consultan si todavía pueden pedir la rescisión. (1) El 1 de agosto de 2022, Andrés contrató a una arquitecta para diseñar su casa, convencido de que era la autora de un edificio premiado que admiraba, y esa fue la razón de contratarla. El 1 de septiembre de 2026 supo que era otra profesional con el mismo nombre. (2) Catalina, que estaba bajo interdicción por disipación, vendió su auto sin intervención de su curador el 1 de mayo de 2019. Fue rehabilitada el 1 de marzo de 2023.',
  enunciado='Determine para cada uno cómo se cuenta el plazo, cuándo vence y si todavía puede pedir la rescisión. Si alguno ya no puede, ¿en qué situación queda su contrato?',
  respuesta='El plazo para pedir la rescisión es de cuatro años, y su cómputo depende del vicio (art. 1691).\n\n(1) Andrés: en el caso de error, el cuadrienio se cuenta desde el día de la celebración del contrato, el 1 de agosto de 2022, aunque Andrés recién conociera su error después. Venció el 1 de agosto de 2026: ya no puede pedir la rescisión. Transcurridos los cuatro años sin que la alegara, el vicio se extinguió y el contrato quedó sano, como si nunca hubiera adolecido de un defecto.\n\n(2) Catalina: cuando la nulidad proviene de una incapacidad legal, el cuadrienio se cuenta desde el día en que haya cesado esa incapacidad, que en su caso es el de su rehabilitación, el 1 de marzo de 2023. Vence el 1 de marzo de 2027: todavía puede pedirla.',
  elementos=[
   ('Andrés ya no puede: en el error el cuadrienio corre desde la celebración, aunque lo descubra después; venció el 1 de agosto de 2026',
    ['andres ya no puede', 'vencio 1 agosto 2026', 'aunque lo descubrio despues', 'desde la celebracion', 'dia que contrato', 'andres no puede'],
    '¿Desde qué día se cuenta el plazo cuando el vicio es un error, y qué importancia tiene el día en que Andrés se enteró?'),
   ('Vencido el plazo, el contrato de Andrés queda saneado, como si nunca hubiera tenido un vicio',
    ['quedo saneado', 'contrato sano', 'como si nunca', 'vicio se extinguio', 'se saneo'],
    '¿Qué le pasa al vicio del contrato cuando nadie lo alega a tiempo?'),
   ('Catalina sí puede: en la incapacidad el cuadrienio corre desde que cesó, con su rehabilitación; vence el 1 de marzo de 2027',
    ['1 marzo 2027', 'desde que ceso', 'catalina si puede', 'catalina todavia puede', 'cese de la incapacidad'],
    '¿Desde cuándo corre el plazo para quien contrató siendo incapaz, y qué día dejó de serlo Catalina?')],
  articulos='1691',
  objetivo='Evaluar si el alumno computa el cuadrienio en el error y en la incapacidad del disipador, y aplica el saneamiento del acto una vez vencido el plazo.',
  respaldo=['IV.B.3.5', 'II.B.3.2', 'II.A.5.3']),

 dict(sub='T21.11',
  caso='El 1 de marzo de 2018, Rosa vendió su departamento a un vecino que la tenía amenazada de manera grave. Las amenazas cesaron el 1 de marzo de 2019, cuando el vecino se fue del país. Rosa murió el 1 de marzo de 2020 sin haber demandado. La heredan sus dos hijos: Diego, de 35 años, y Ema, que nació el 1 de junio de 2003.',
  enunciado='¿Hasta qué fecha puede cada hijo pedir la rescisión de la venta? Fundamente con el cómputo.',
  respuesta='En el caso de violencia, el cuadrienio se cuenta desde el día en que esta hubiere cesado (art. 1691), el 1 de marzo de 2019: para Rosa vencía el 1 de marzo de 2023. A su muerte había corrido un año, y quedaba un residuo de tres años.\n\nCuando fallece quien podía demandar la rescisión, el art. 1692 distingue según la edad de los herederos.\n\nDiego, mayor: el plazo no se suspende, y goza de lo que reste del cuadrienio. Puede pedir la rescisión hasta el 1 de marzo de 2023.\n\nEma, menor a la muerte de su madre (tenía 16 años): el residuo empieza a correr solo desde que llega a la mayoría de edad, el 1 de junio de 2021, así que puede pedirla hasta el 1 de junio de 2024. El tope de diez años desde la celebración del contrato (que se cumpliría el 1 de marzo de 2028) no la alcanza, porque su plazo vence antes.',
  elementos=[
   ('El cuadrienio corre desde que cesó la fuerza, el 1 de marzo de 2019; a la muerte de Rosa quedaba un residuo de tres años',
    ['desde el cese', 'desde que ceso', 'residuo de tres', 'quedaban tres', 'tres anos restantes', 'ceso la fuerza'],
    '¿Desde qué día corría el plazo para Rosa, y cuánto quedaba de él cuando murió?'),
   ('Diego, mayor de edad: sin suspensión, goza del residuo; puede hasta el 1 de marzo de 2023',
    ['diego hasta 2023', 'no se suspende', 'sin suspension', 'diego goza del residuo', 'diego residuo'],
    '¿Cambia en algo el plazo para el hijo que ya era adulto cuando murió su madre?'),
   ('Ema, menor de edad: el residuo corre desde su mayoría de edad (1 de junio de 2021); puede hasta el 1 de junio de 2024, sin que la alcance el tope de diez años',
    ['1 junio 2024', 'desde su mayoria', 'cumplio 18', 'mayoria de edad', 'tope no la alcanza', '1 marzo 2028'],
    '¿Desde cuándo corre el plazo para la hija que era menor, y hay algún límite que pueda cortárselo antes?')],
  articulos='1691, 1692',
  objetivo='Evaluar si el alumno computa el cuadrienio en la fuerza y aplica el art. 1692 a herederos mayores y menores, verificando si opera el tope de diez años.',
  respaldo=['IV.B.3.5']),

 # T21.03 Diferencias entre nulidad absoluta y relativa (5 exámenes: 2; la tanda 1 dejó 1)
 dict(sub='T21.03',
  caso='El 1 de marzo de 2022, Patricio celebra dos contratos. En el primero, se obliga a pagarle $5.000.000 a Germán para que este declare falsamente como testigo en un juicio. En el segundo, le compra un terreno a Inés, que lo engañó con planos adulterados, sin los cuales Patricio no habría comprado. El 1 de junio de 2024, Patricio y Germán firman una escritura en que "ratifican" el primer contrato, y Patricio e Inés firman otra en que "ratifican" el segundo. Ese mismo mes, el fiscal judicial de la Corte de Apelaciones respectiva quiere pedir la nulidad de ambos contratos.',
  enunciado='¿Producen efecto las ratificaciones? ¿Puede el fiscal judicial pedir la nulidad de cada contrato? ¿Hasta cuándo puede alegarse la nulidad del primero?',
  respuesta='El primer contrato tiene causa ilícita, porque su motivo es contrario a la ley y a las buenas costumbres (art. 1467): adolece de nulidad absoluta. El segundo está viciado por dolo determinante de una de las partes: adolece de nulidad relativa.\n\nRatificaciones. La del primero no produce efecto: la nulidad absoluta no puede sanearse por la ratificación de las partes (art. 1683), porque protege el interés general. La del segundo sí: la nulidad relativa puede sanearse por la ratificación de la persona en cuyo beneficio la ley la establece (art. 1684), y aquí ratificó Patricio, la víctima del dolo.\n\nFiscal judicial. Puede pedir la nulidad del primero, porque la nulidad absoluta puede pedirse por el ministerio público en el interés de la moral o de la ley (art. 1683). No puede pedir la del segundo: la nulidad relativa no puede pedirse por el ministerio público en el solo interés de la ley (art. 1684).\n\nPlazo del primero. La nulidad absoluta se sanea por el transcurso de diez años desde la celebración del contrato: puede alegarse hasta el 1 de marzo de 2032.',
  elementos=[
   ('La ratificación no sanea el primer contrato (nulidad absoluta), pero sí el segundo (nulidad relativa), porque la hizo la víctima del dolo',
    ['absoluta no se ratifica', 'no sanea la absoluta', 'relativa si se ratifica', 'segunda queda saneada', 'primera no produce efecto', 'ratifico la victima'],
    '¿Pueden las partes, por su sola voluntad, validar cualquier contrato nulo, o depende de a quién protege la nulidad?'),
   ('El fiscal judicial puede pedir la nulidad absoluta (interés de la moral o de la ley), pero no la relativa',
    ['fiscal solo la absoluta', 'fiscal puede la primera', 'fiscal no puede la segunda', 'interes de la moral', 'no en la relativa'],
    '¿En qué interés interviene el ministerio público, y está ese interés comprometido en los dos contratos?'),
   ('La nulidad del primero puede alegarse hasta el 1 de marzo de 2032 (diez años desde la celebración)',
    ['1 marzo 2032', 'diez anos', '10 anos', 'hasta 2032'],
    '¿Cuánto tiempo hay para atacar el primer contrato y desde cuándo se cuenta?')],
  articulos='1467, 1683, 1684',
  objetivo='Evaluar si el alumno aplica en paralelo a dos contratos las diferencias entre ambas nulidades en saneamiento por ratificación, intervención del ministerio público y plazo.',
  respaldo=['IV.B.1.6', 'IV.B.2.4', 'IV.B.2.5', 'IV.B.2.6', 'IV.B.3.4', 'II.D.4']),

 # T21.08 Nulidad absoluta: saneamiento y no opera de pleno derecho (9 exámenes: 2; la tanda 1 dejó 1)
 dict(sub='T21.08',
  caso='El 1 de febrero de 2013, Ana, que se encontraba bajo interdicción por demencia, firmó la venta de su parcela de Paine a Bernardo, quien inscribió a su nombre y la ocupa desde entonces. En 2016, el curador de Ana le envió una carta a Bernardo en que le dice que la venta "es nula de pleno derecho, así que la parcela nunca dejó de ser de Ana", y no hizo nada más. En 2024 el curador demanda la nulidad absoluta. Bernardo se defiende diciendo que el tiempo transcurrido consolidó su situación.',
  enunciado='¿Tenía razón el curador en su carta de 2016? ¿Prospera la demanda de 2024? ¿Qué efecto tiene, según BARAONA, el paso del tiempo sobre la situación de Bernardo?',
  respuesta='La venta adolecía de nulidad absoluta, porque Ana, demente, era absolutamente incapaz (arts. 1447 y 1682).\n\nLa carta del curador no tenía razón, según la doctrina tradicional: la nulidad absoluta no opera de pleno derecho, sino que necesita ser declarada por el juez, como se deduce de las normas que hablan de la nulidad judicialmente declarada o pronunciada (arts. 1683, 1687 y 1689). Mientras esa sentencia no existe, el acto nulo sigue produciendo todos sus efectos.\n\nLa demanda de 2024 no prospera. La nulidad absoluta se sanea por el transcurso de diez años (art. 1683), contados desde la celebración del acto: vencieron el 1 de febrero de 2023.\n\nPara BARAONA, lo que el art. 1683 llama saneamiento es, en realidad, una caducidad de los derechos de quienes podían impugnar el acto. Su efecto es consolidar los desplazamientos patrimoniales: al no ser impugnado durante diez años, el título de Bernardo pasa de injusto a justo y permite que opere la prescripción adquisitiva. Por eso el art. 705 habla de la validación del título "por otro medio legal", que aquí es el transcurso del tiempo.',
  elementos=[
   ('La nulidad absoluta no opera de pleno derecho: necesita sentencia, y mientras tanto el acto produce sus efectos',
    ['requiere sentencia', 'declaracion judicial', 'declarada por el juez', 'sigue produciendo efectos', 'necesita sentencia', 'judicialmente declarada'],
    '¿Basta que una de las partes considere nulo el acto para que deje de producir efectos?'),
   ('La demanda de 2024 no prospera: los diez años desde la celebración vencieron el 1 de febrero de 2023',
    ['1 febrero 2023', 'diez anos', '10 anos', 'ya se saneo', 'plazo vencido', 'demanda no prospera'],
    '¿Cuánto tiempo hay para alegar esta nulidad, desde cuándo se cuenta y cuándo terminó en este caso?'),
   ('Para BARAONA es una caducidad: el título de Bernardo pasa de injusto a justo (art. 705) y permite la prescripción adquisitiva',
    ['caducidad', 'titulo justo', '705', 'prescripcion adquisitiva', 'de injusto a justo', 'validacion del titulo'],
    '¿Puede el simple paso del tiempo volver válido lo que nunca lo fue, y qué cambia entonces para quien tiene la parcela?')],
  articulos='705, 1447, 1682, 1683, 1687, 1689',
  objetivo='Evaluar si el alumno aplica que la nulidad absoluta no opera de pleno derecho, computa los diez años del art. 1683 y explica la lectura de BARAONA sobre su efecto en el título del adquirente.',
  respaldo=['IV.B.2.6', 'IV.B.2.7', 'IV.B.2.2', 'II.B.3.1']),
]

INFORME = dict(
 titulo='Aplicación · Tema 20: Nulidad (tanda 2)',
 puntos=[
  ('Alcance de las reglas de la nulidad (IV.B.1.1)', 'Lo que la tanda 1 no tocó: los actos unilaterales, la exclusión del derecho público (el procesal) y la disposición expresa que fija otra sanción (art. 2206).'),
  ('Especies y su criterio (IV.B.1.3)', 'El criterio del art. 1681 inc. 2° aplicado a dos vicios distintos, y por qué la absoluta es objetiva y la relativa subjetiva.'),
  ('Causales que agregan quienes rechazan la inexistencia (IV.B.2.2)', 'El error esencial (con las tres posiciones de II.A.5.3) y la falta de voluntad (fuerza física).'),
  ('Declaración de oficio y ministerio público (IV.B.2.4)', 'Qué significa que el vicio aparezca de manifiesto, y que el fiscal penal no es el ministerio público del art. 1683.'),
  ('Exclusión del que sabía o debía saber (IV.B.2.4)', 'Conocimiento real frente al presunto del art. 8° y las dos posturas sobre los herederos.'),
  ('Saneamiento de la absoluta y pleno derecho (IV.B.2.6 y 7)', 'La carta que da por nulo el acto, los diez años y la lectura de BARAONA con el art. 705.'),
  ('Causales de nulidad relativa (IV.B.3.2)', 'Error en la persona, lesión enorme, fuerza de un tercero y disipador interdicto o no.'),
  ('Titulares de la relativa (IV.B.3.4)', 'Aserción de no existir la interdicción frente al dolo, cesionarios y ministerio público.'),
  ('Saneamiento de la relativa (IV.B.3.5)', 'Cómputo en el error y en la incapacidad del disipador, contrato saneado, y herederos mayor y menor en la fuerza sin que opere el tope.'),
  ('Diferencias (IV.B.1.6)', 'Ratificación, ministerio público y plazo, aplicados en paralelo a un contrato con nulidad absoluta y otro con relativa.'),
 ],
 cobertura=[
  ('Las reglas de nulidad rigen para actos unilaterales, no para el derecho público, y ceden ante una sanción distinta', 'Aplicación al caso'),
  ('Criterio del art. 1681 inc. 2°; nulidad absoluta objetiva y relativa subjetiva', 'Distinción aplicada al caso'),
  ('Sanción del error esencial según las tres posiciones', 'Controversia doctrinal aplicada'),
  ('Fuerza física: falta de voluntad, inexistencia o nulidad absoluta', 'Distinción y controversia'),
  ('Vicio manifiesto para la declaración de oficio; ministerio público del art. 1683', 'Requisito y excepción aplicados'),
  ('Conocimiento real frente al presunto; herederos de quien contrató a sabiendas', 'Aplicación y controversia'),
  ('Error en la persona con indemnización; lesión enorme', 'Aplicación al caso'),
  ('Fuerza de un tercero; disipador interdicto y no interdicto', 'Distinción aplicada al caso'),
  ('Art. 1685 con la interdicción; cesionarios; ministerio público en la relativa', 'Excepción aplicada'),
  ('Cómputo en el error y en la incapacidad; acto saneado', 'Aplicación con fechas'),
  ('Herederos mayor y menor en la fuerza, sin que opere el tope', 'Aplicación con fechas'),
  ('Ratificación, ministerio público y plazo en ambas nulidades', 'Comparación aplicada'),
  ('No opera de pleno derecho; diez años; lectura de BARAONA y art. 705', 'Aplicación con fechas y controversia'),
 ],
 avisos=[
  '<b>Cuántas quedan por subtema:</b> con esta tanda, Nulidad · Aplicación llega a 30. Cuatro en los subtemas de 10 o más exámenes (concepto y especies, causales de la absoluta, quién la pide, causales de la relativa, saneamiento de la relativa), dos en diferencias y en saneamiento de la absoluta, y una en terminología, principios comunes y nulidad total o parcial, que no aparecen en ningún examen.',
  '<b>Un subtema queda en 3 y no en 4:</b> "quiénes pueden alegar la nulidad relativa". La tanda 1 ya usó la contraparte que quiere anular, los herederos, el cesionario y el art. 1685 con la edad. Esta tanda junta en una sola pregunta lo que faltaba (aserción de no existir la interdicción, cesionarios del incapaz que usó dolo y ministerio público). Una cuarta pregunta repetiría alguno de esos elementos.',
  '<b>Puntos discutidos, presentados como tales:</b> la sanción del error esencial (tres posiciones), la de la fuerza física (inexistencia o nulidad absoluta), los herederos de quien contrató sabiendo el vicio (el manual da las dos posturas sin inclinarse) y que la nulidad absoluta no opere de pleno derecho (se presenta como la doctrina tradicional, porque el manual recoge la opinión distinta de BARAONA).',
  '<b>Se evitó un punto discutido:</b> para el criterio de las especies se usó el testamento sin los testigos exigidos (solemnidad de validez, nulidad absoluta sin discusión) y no la venta de un inmueble sin escritura, cuya sanción es discutida (inexistencia o nulidad absoluta).',
  '<b>Fronteras con otros temas:</b> la ratificación de la nulidad relativa solo aparece como "puede o no sanear" (diferencias), sin sus requisitos, que son del tema 21. No se usó la regla de que el art. 1692 no se extiende por analogía a otros incapaces, porque está en las acciones de nulidad (tema 22). La lesión enorme se usa solo como causal; su mecanismo para evitar la rescisión queda para su propio tema.',
  '<b>Dos casos cercanos a ejemplos del manual</b> (mismo punto de derecho, otros hechos; tú decides): la arquitecta con el mismo nombre (el manual usa a la Flo y el fotógrafo homónimo) y el disipador sin interdicción (el manual usa a la Moni y las apuestas en línea).',
 ],
 redundancia='Dentro de la tanda no hay dos preguntas que evalúen el mismo elemento. Frente a la tanda 1: el alcance de las reglas no repite el derecho comercial ni la irrenunciabilidad (004); el criterio de las especies no repite que ambas producen los mismos efectos (005); las causales de la absoluta usan el error esencial y la fuerza física, no la incapacidad, la causa ilícita ni la falta de causa (010 y 011); la declaración de oficio mira ahora a qué es "manifiesto", no a la diferencia con la relativa (007); el art. 1683 se aplica a quien no conocía la prohibición y a los herederos, no a quien sabía ni al representado (013); las causales de la relativa son otras que el error sustancial, el dolo y la formalidad habilitante (015 y 016); el cómputo usa el error en la persona y la incapacidad del disipador, no el dolo, la fuerza ni la edad (019), y los herederos se calculan con fuerza y sin que opere el tope, al revés que en 020. Los tres disipadores evalúan reglas distintas: la causal de nulidad relativa (028), el art. 1685 (029) y el cómputo desde la rehabilitación (030).',
)
