# Evaluación de Acto Jurídico, tanda 1: Aplicación del tema 20 (Nulidad: concepto, clases,
# causales, titulares y saneamiento), IV.B.1 a IV.B.3 del manual.
# Criterio de cantidad (Laura, 2026-10-09, opción B): dos preguntas en los subtemas que
# aparecen en 10 o más exámenes y una en el resto. La terminología (rescisión y nulidad
# relativa) es un debate de palabras y no da para un caso: su subtema se cubre con la
# nulidad relativa como regla general.
#
# Formato de cada ítem: subtema (código del catálogo), caso, enunciado, respuesta modelo,
# elementos clave [(texto, keywords, pregunta socrática)], artículos de referencia,
# objetivo pedagógico y respaldo (secciones del manual donde está todo lo que se afirma).
TABLA = 'Aplicación'
PREFIJO = 'aj-aplic'

ITEMS = [
 # T21.01 Reglas, concepto general y especies de nulidad (15 exámenes: 2 preguntas)
 dict(sub='T21.01',
  caso='Constructora Los Aromos SpA y Áridos del Maipo Ltda. celebran un contrato de suministro de áridos, que para ambas es un acto de comercio. En una de sus cláusulas pactan: "Este contrato no quedará sujeto a las normas del Código Civil sobre nulidad; cualquier defecto en su celebración solo dará derecho a una rebaja del precio". Un año después, Áridos del Maipo demanda la nulidad del contrato. Constructora Los Aromos se defiende con dos argumentos: (1) las reglas del Código Civil sobre nulidad no se aplican a un contrato mercantil; y (2) en cualquier caso, las partes las excluyeron de común acuerdo.',
  enunciado='¿Son correctos los dos argumentos de Constructora Los Aromos? Fundamente cada uno.',
  respuesta='Ninguno es correcto.\n\n(1) Las reglas generales de la nulidad (arts. 1681 a 1697) tienen alcance general: rigen para cualquier acto jurídico y se aplican también en las demás ramas del derecho privado, como el derecho comercial, si no hay una norma especial en contrario. Solo no se extienden al derecho público, que tiene reglas propias. Que el suministro sea mercantil no lo saca de ellas.\n\n(2) Esas reglas son de orden público: son de aplicación estricta y las partes no pueden derogarlas. Además, la nulidad no puede renunciarse anticipadamente: según el art. 1469, los actos que la ley declara inválidos no dejan de serlo por las cláusulas en que se renuncie la acción de nulidad. La cláusula no impide, entonces, que se alegue la nulidad.',
  elementos=[
   ('Las reglas de nulidad del Código Civil se aplican también en las demás ramas del derecho privado, como el comercial, salvo norma especial',
    ['demas ramas del derecho privado', 'se aplican al derecho comercial', 'tambien rigen para contratos mercantiles', 'alcance general', 'cualquier acto juridico', 'tambien al derecho privado'],
    '¿Hasta dónde llegan las reglas del Código Civil sobre nulidad: solo a los actos civiles, o a todo el derecho privado?'),
   ('Las reglas de la nulidad son de orden público: las partes no pueden derogarlas',
    ['orden publico', 'no pueden derogarlas', 'no pueden excluirlas', 'aplicacion estricta', 'no se pueden derogar'],
    '¿Pueden las partes, de común acuerdo, dejar sin aplicación las reglas de la nulidad?'),
   ('La nulidad no puede renunciarse anticipadamente (art. 1469)',
    ['1469', 'renuncie la accion de nulidad', 'renunciar anticipadamente', 'renuncia anticipada', 'no dejan de ser invalidos', 'no se puede renunciar a la nulidad'],
    '¿Qué valor tiene una cláusula en que las partes renuncian de antemano a pedir la nulidad?')],
  articulos='1469, 1681 a 1697',
  objetivo='Evaluar si el alumno aplica a un caso concreto los rasgos de las reglas de la nulidad: alcance general en el derecho privado, carácter de orden público e irrenunciabilidad anticipada.',
  respaldo=['IV.B.1.1', 'IV.B.1.7']),

 dict(sub='T21.01',
  caso='Dos juicios terminan el mismo día. En el primero, se declara la nulidad absoluta de la compraventa de un auto que Rocío le vendió a Benjamín. En el segundo, se declara la nulidad relativa de la compraventa de un piano que Esteban le vendió a Gloria, porque Esteban contrató con un error sustancial. El abogado de Gloria sostiene que, como la nulidad relativa es "menos grave" que la absoluta, la sentencia de su juicio solo debería dejar sin efecto el contrato hacia el futuro, sin obligar a Esteban y a Gloria a devolverse lo que se dieron, a diferencia de lo que ocurre entre Rocío y Benjamín.',
  enunciado='¿Es correcto el argumento del abogado de Gloria? Explique qué distingue realmente a la nulidad absoluta de la relativa.',
  respuesta='No es correcto. La distinción entre nulidad absoluta y relativa no mide cuán grave es la ineficacia: la relativa no deja al acto "medio nulo". Una vez declaradas judicialmente, las dos producen exactamente los mismos efectos: vuelven a las partes al estado anterior a la celebración del acto nulo. Por eso, en ambos juicios, las partes deben quedar como estaban antes de contratar.\n\nLo que distingue a una especie de la otra es la razón por la que se exige el requisito omitido (art. 1681): hay nulidad absoluta cuando el requisito se exige en consideración a la naturaleza o especie del acto, y nulidad relativa cuando se exige en atención a la calidad o estado de las partes que lo celebran. Por eso el vicio de la absoluta es objetivo, y el de la relativa, subjetivo. Las diferencias entre ambas están en las causales, en quién puede pedir cada una y en el plazo en que se sanean, no en sus efectos.',
  elementos=[
   ('Declaradas, ambas nulidades producen los mismos efectos: la distinción no mide la gravedad',
    ['mismos efectos', 'no mide la gravedad', 'no es menos grave', 'producen los mismos efectos', 'no hay diferencia en los efectos', 'medio nulo'],
    'Una vez declarada por el juez, ¿produce la nulidad relativa efectos distintos de la absoluta?'),
   ('Las partes vuelven al estado anterior a la celebración del acto, también Esteban y Gloria',
    ['estado anterior', 'como estaban antes', 'tambien deben restituir', 'restituirse', 'antes de contratar'],
    '¿En qué situación deben quedar Esteban y Gloria después de la sentencia?'),
   ('La especie depende de por qué se exige el requisito: naturaleza o especie del acto (absoluta) o calidad o estado de las partes (relativa)',
    ['naturaleza o especie del acto', 'calidad o estado de las partes', 'naturaleza del acto', 'calidad de las partes', '1681'],
    '¿Qué criterio usa el Código para decidir si la nulidad es absoluta o relativa?')],
  articulos='1681',
  objetivo='Evaluar si el alumno descarta la idea de que la nulidad relativa sea una ineficacia más leve y si identifica el verdadero criterio que separa ambas especies.',
  respaldo=['IV.B.1.3', 'IV.B.1.6']),

 # T21.02 Terminología y nulidad como regla general (sin exámenes: 1 pregunta, sobre la regla general)
 dict(sub='T21.02',
  caso='Valentina le vendió su camioneta a Andrés porque él la amenazó, de manera seria y creíble, con dañar a su hija si no firmaba. La amenaza fue grave y determinante: sin ella, Valentina no habría vendido. Ya libre de la amenaza, Valentina demanda la nulidad. Su abogado pide que sea declarada nulidad absoluta, con este argumento: "el art. 1682 no dice expresamente que la fuerza produzca nulidad relativa, y ante el silencio de la ley debe aplicarse la sanción más protectora para la víctima".',
  enunciado='¿Qué especie de nulidad corresponde a la venta de Valentina? Evalúe el argumento de su abogado.',
  respuesta='Corresponde la nulidad relativa. El argumento del abogado falla porque la ley no guarda silencio: el art. 1682 enumera las causales de nulidad absoluta (el objeto ilícito, la causa ilícita, la incapacidad absoluta y la omisión de requisitos o formalidades exigidos en consideración a la naturaleza del acto) y cierra con una cláusula residual: "cualquiera otra especie de vicio produce nulidad relativa". Por construcción, entonces, la regla general es la nulidad relativa: todo vicio que la ley no sancione expresamente de otro modo cae ahí. La fuerza no está entre las causales de nulidad absoluta, así que vicia la venta con nulidad relativa.',
  elementos=[
   ('La ley no calla: el art. 1682 inc. final contiene una cláusula residual',
    ['cualquiera otra especie de vicio', 'clausula residual', 'regla residual', 'todo otro vicio', 'cierra con una clausula'],
    '¿Qué dice el art. 1682 sobre los vicios que no enumera como causales de nulidad absoluta?'),
   ('La regla general es la nulidad relativa',
    ['regla general es la nulidad relativa', 'la regla general es la relativa', 'regla general', 'nulidad relativa es la regla'],
    'Si un vicio no tiene asignada expresamente otra sanción, ¿qué nulidad lo alcanza por defecto?'),
   ('La fuerza no está entre las causales de nulidad absoluta, que son el objeto ilícito, la causa ilícita, la incapacidad absoluta y las formalidades exigidas por la naturaleza del acto',
    ['no esta entre las causales', 'no es causal de nulidad absoluta', 'objeto ilicito', 'causa ilicita', 'incapacidad absoluta'],
    '¿Cuáles son las causales de nulidad absoluta, y está la fuerza entre ellas?')],
  articulos='1682',
  objetivo='Evaluar si el alumno aplica la cláusula residual del art. 1682 para concluir que la nulidad relativa es la regla general, frente a un vicio que no figura entre las causales de nulidad absoluta.',
  respaldo=['IV.B.1.5', 'IV.B.2.2']),

 # T21.03 Diferencias entre nulidad absoluta y relativa (5 exámenes: 1 pregunta)
 dict(sub='T21.03',
  caso='En un juicio de cobro entre Claudio y Marisol, el juez de letras revisa los dos contratos que las partes acompañaron. En el primero, Claudio se obliga a pagarle $2.000.000 a Marisol "como recompensa por haber incendiado la bodega de un competidor". El segundo es una compraventa en que, según declaró un testigo, Marisol compró con un error sustancial sobre la cosa. Ninguna de las partes ha pedido la nulidad de ninguno de los dos contratos.',
  enunciado='¿Puede el juez declarar de oficio la nulidad de cada uno de los contratos? Fundamente.',
  respuesta='Del primero, sí. La promesa de dar algo en recompensa de un crimen tiene causa ilícita (art. 1467), y la causa ilícita produce nulidad absoluta (art. 1682). La nulidad absoluta puede y debe ser declarada por el juez, aun sin petición de parte, cuando aparece de manifiesto en el acto o contrato (art. 1683). Aquí el vicio se desprende de la sola lectura del contrato, sin acudir a otra prueba, y existe un juicio en que ese contrato se invoca.\n\nDel segundo, no. El error sustancial produce nulidad relativa, y la nulidad relativa solo puede declararse a petición de parte (art. 1684), por más que el vicio llegue a acreditarse en el proceso.\n\nLa diferencia se explica por el fundamento de cada una: la absoluta protege el interés de la moral y de la ley; la relativa, el interés de ciertas y determinadas personas, que son las únicas llamadas a decidir si la piden.',
  elementos=[
   ('El primer contrato tiene causa ilícita (recompensa de un crimen) y adolece de nulidad absoluta',
    ['causa ilicita', 'recompensa de un crimen', '1467', 'causa es ilicita'],
    '¿Qué vicio tiene un contrato cuyo motivo es premiar un delito, y qué nulidad produce?'),
   ('La nulidad absoluta puede y debe declararse de oficio cuando aparece de manifiesto en el contrato (art. 1683)',
    ['aun sin peticion de parte', 'sin peticion de parte', 'de manifiesto', '1683', 'debe declararla', 'basta leer el contrato'],
    '¿Qué condición tiene que darse para que el juez, por iniciativa propia, anule el contrato?'),
   ('La nulidad relativa solo se declara a petición de parte (art. 1684)',
    ['solo a peticion de parte', 'a pedimento de parte', '1684', 'no puede declararla de oficio', 'no puede declararse de oficio', 'solo si una parte la pide'],
    '¿Puede el juez declarar por iniciativa propia la nulidad que proviene de un error sustancial?')],
  articulos='1467, 1682, 1683, 1684',
  objetivo='Evaluar si el alumno contrasta, en un mismo proceso, la declaración de oficio de la nulidad absoluta manifiesta con la exigencia de petición de parte en la relativa, y si lo conecta con el fundamento de cada una.',
  respaldo=['IV.B.1.6', 'IV.B.2.4', 'II.D.6', 'II.D.4']),

 # T21.04 Principios comunes a ambas nulidades (1 pregunta)
 dict(sub='T21.04',
  caso='En marzo de 2023, Hernán, mayor de edad y en pleno uso de sus facultades, vende su parcela de Pirque a los hermanos Lorena y Felipe, que la compran en común. En 2025, Hernán es declarado en interdicción por demencia, y su curadora demanda la nulidad de la venta, argumentando que hoy Hernán es absolutamente incapaz. Por su parte, Lorena obtiene una sentencia que declara nula la compra a su respecto, porque contrató bajo fuerza. Felipe, que no litigó, pretende que esa sentencia también lo libere a él.',
  enunciado='¿Prospera la demanda de la curadora? ¿Puede Felipe aprovechar la sentencia obtenida por Lorena?',
  respuesta='La demanda de la curadora no prospera. El vicio tiene que existir al momento mismo en que el acto se celebra: no hay nulidad por causa sobreviniente. En marzo de 2023 Hernán era capaz, de modo que la venta nació válida, y la interdicción posterior no puede volverla nula.\n\nFelipe tampoco puede aprovechar la sentencia de Lorena. La nulidad solo aprovecha a quien la obtiene: cuando dos o más personas han contratado con un tercero, la nulidad declarada a favor de una de ellas no aprovecha a las otras (art. 1690). Si Felipe quisiera la nulidad, tendría que obtener su propia declaración judicial.',
  elementos=[
   ('El vicio debe existir al celebrarse el acto; no hay nulidad por causa sobreviniente',
    ['causa sobreviniente', 'al momento de celebrarse', 'al celebrarse el acto', 'nacio valido', 'al momento de la celebracion', 'vicio posterior'],
    '¿En qué momento debe existir el vicio para que el acto sea nulo?'),
   ('La nulidad solo aprovecha a quien la obtiene (art. 1690)',
    ['1690', 'solo aprovecha a quien la obtiene', 'no aprovecha a las otras', 'no aprovechara a las otras', 'no le aprovecha', 'no lo beneficia'],
    'Si dos personas contrataron con un tercero, ¿a quién beneficia la nulidad declarada a favor de una de ellas?'),
   ('Felipe debe obtener su propia declaración judicial',
    ['su propia declaracion', 'propia sentencia', 'litigar el mismo', 'demandar el mismo', 'pedirla por su cuenta'],
    '¿Qué tendría que hacer Felipe para que el contrato quedara sin efecto respecto de él?')],
  articulos='1690',
  objetivo='Evaluar si el alumno aplica dos principios comunes a ambas nulidades: que el vicio debe existir al celebrarse el acto y que la nulidad solo aprovecha a quien la obtiene.',
  respaldo=['IV.B.1.7']),

 # T21.05 Nulidad total y parcial; consecuencial y refleja (1 pregunta)
 dict(sub='T21.05',
  caso='En una misma escritura pública, Carolina le vende a Ignacio un departamento en Concepción y, en una cláusula separada, le presta $5.000.000 para que lo remodele. Años después se declara nula la escritura, porque se omitió un requisito de validez que la ley exige a la escritura pública como instrumento. Carolina sostiene que, como la escritura es nula, son nulos tanto la venta del departamento como el préstamo.',
  enunciado='¿Tiene razón Carolina respecto de cada uno de los dos actos? Fundamente.',
  respuesta='Respecto de la venta, sí. La venta de un bien raíz es un acto solemne: no se reputa perfecta mientras no se otorgue escritura pública (art. 1801 inc. 2°), que es la forma exigida como único medio idóneo de expresar la voluntad. Como la escritura, en cuanto instrumento, está sujeta a sus propios requisitos de validez, si es nula, también lo es el acto contenido en ella: es la nulidad refleja. Por estar viciada la forma del acto solemne, el acto mismo pasa a ser nulo.\n\nRespecto del préstamo, no. Cuando un mismo instrumento contiene varios actos independientes entre sí, la nulidad de uno no afecta a los demás, y esa independencia no se altera por constar todos en el mismo documento. Para el préstamo, la escritura no es la forma exigida, sino solo el documento donde consta, de modo que sigue valiendo.',
  elementos=[
   ('La venta del departamento cae por nulidad refleja: la escritura es la forma exigida del acto solemne',
    ['nulidad refleja', 'acto solemne', 'forma exigida', '1801', 'unico medio', 'solemnidad'],
    '¿Qué pasa con la venta de un inmueble si es nula la escritura pública en que consta?'),
   ('El préstamo es un acto independiente: la nulidad de un acto no afecta a los demás que constan en el mismo instrumento',
    ['prestamo independiente', 'actos independientes', 'no afecta al prestamo', 'no arrastra al prestamo', 'el prestamo sigue valiendo', 'el prestamo es valido'],
    '¿Arrastra la nulidad de uno de los actos a los demás que constan en la misma escritura?'),
   ('El criterio es si la escritura es la forma exigida para el acto o solo el documento donde consta',
    ['solo el documento', 'no es la forma exigida', 'forma y contenido', 'mismo documento', 'solo consta en la escritura'],
    '¿Qué papel cumple la escritura respecto del préstamo: es su forma exigida o solo el papel donde quedó escrito?')],
  articulos='1801 inc. 2°',
  objetivo='Evaluar si el alumno distingue la nulidad refleja de un acto solemne por vicio de su forma de la situación de actos independientes que solo comparten un mismo instrumento.',
  respaldo=['IV.B.1.9', 'II.E.2']),

 # T21.06 Nulidad absoluta: concepto, causales y fundamento (10 exámenes: 2 preguntas)
 dict(sub='T21.06',
  caso='Al ordenar los papeles del difunto don Raúl Peña, su abogada encuentra tres contratos: (1) una compraventa por la que Tomás, nieto de don Raúl, de ocho años, le vendió su bicicleta a un vecino, sin intervención de sus padres; (2) un contrato por el cual don Raúl se obligó a pagarle $3.000.000 a un tercero como recompensa por haber golpeado a un acreedor suyo; y (3) una compraventa en que don Raúl le compró un auto a Matías, de 16 años, que firmó sin autorización de sus padres.',
  enunciado='Determine qué especie de nulidad afecta a cada contrato y por qué causal.',
  respuesta='(1) Nulidad absoluta, por incapacidad absoluta: Tomás es impúber, y los impúberes son absolutamente incapaces (art. 1447). La incapacidad absoluta es una de las causales de nulidad absoluta del art. 1682.\n\n(2) Nulidad absoluta, por causa ilícita: la promesa de dar algo en recompensa de un crimen o de un hecho inmoral tiene una causa ilícita (art. 1467), y la causa ilícita es causal de nulidad absoluta (art. 1682).\n\n(3) Nulidad relativa: Matías es menor adulto, relativamente incapaz, y los actos de los relativamente incapaces no están entre las causales de nulidad absoluta; caen en la nulidad relativa. La diferencia con el primer caso está en que el requisito omitido se exige en atención a la calidad o estado de la persona, no a la naturaleza del acto.',
  elementos=[
   ('La venta de Tomás es absolutamente nula por incapacidad absoluta (impúber)',
    ['incapacidad absoluta', 'impuber', 'absolutamente incapaz', '1447'],
    '¿Qué clase de incapaz es un niño de ocho años y qué nulidad produce su acto?'),
   ('El contrato de recompensa es absolutamente nulo por causa ilícita',
    ['causa ilicita', 'recompensa de un crimen', '1467', 'motivo ilicito'],
    '¿Qué vicio tiene una obligación contraída para premiar una agresión?'),
   ('La venta de Matías es relativamente nula: los actos de los relativamente incapaces producen nulidad relativa',
    ['relativamente incapaz', 'menor adulto', 'incapacidad relativa', 'incapaz relativo'],
    '¿Qué clase de incapaz es un menor de 16 años, y está su incapacidad entre las causales de nulidad absoluta?')],
  articulos='1447, 1467, 1682',
  objetivo='Evaluar si el alumno identifica en hechos concretos las causales de nulidad absoluta del art. 1682 y las distingue de un caso de nulidad relativa.',
  respaldo=['IV.B.2.2', 'IV.B.3.2', 'II.B.3', 'II.D.4', 'II.D.6']),

 dict(sub='T21.06',
  caso='Ricardo firma un documento en que promete pagarle a su cuñada Paula $800.000 en diciembre, "por la reparación del techo de mi casa". Ricardo está convencido de que le debe ese dinero, pero no sabe que su socio ya se lo había pagado a Paula meses atrás, así que en realidad no existe deuda alguna. Al enterarse, Ricardo consulta a dos abogados: uno acepta la teoría de la inexistencia jurídica y el otro la rechaza.',
  enunciado='¿Qué vicio tiene la promesa de Ricardo? ¿Qué sanción le aplicaría cada uno de los dos abogados?',
  respuesta='La promesa carece de causa: es el ejemplo del propio art. 1467, la promesa de dar algo en pago de una deuda que no existe. Ricardo tenía un motivo, la creencia de que debía; pero como esa creencia es falsa, la causa también lo es, y una causa falsa equivale a no tener causa real.\n\nEl abogado que acepta la inexistencia dirá que el acto no llega a nacer, porque le falta un requisito de existencia: no es un acto nulo, sino un acto que no ha podido nacer a la vida jurídica.\n\nEl que la rechaza lo sancionará con nulidad absoluta. Quienes niegan que el Código recoja la inexistencia agregan a las causales de nulidad absoluta del art. 1682 la falta de voluntad, de objeto y de causa, entre otras.',
  elementos=[
   ('La promesa de pagar una deuda que no existe carece de causa (art. 1467)',
    ['falta de causa', 'carece de causa', 'sin causa', 'obligacion sin causa', '1467', 'causa falsa'],
    '¿Qué requisito del acto falta cuando alguien se obliga a pagar una deuda inexistente?'),
   ('Para la teoría de la inexistencia, el acto no llega a nacer: es inexistente',
    ['acto no nace', 'no es un acto nulo', 'no llega a nacer', 'no nace a la vida juridica', 'no ha podido nacer'],
    '¿Qué consecuencia tiene, para quienes aceptan la inexistencia, la falta de un requisito de existencia?'),
   ('Para quienes rechazan la inexistencia, la falta de causa es causal de nulidad absoluta',
    ['nulidad absoluta', 'absolutamente nula', 'absolutamente nulo', 'nulo absolutamente'],
    'Si el Código no recoge la inexistencia, ¿cuál es la sanción más grave que puede aplicarse?')],
  articulos='1467, 1682',
  objetivo='Evaluar si el alumno reconoce en los hechos un acto sin causa y aplica las dos posturas sobre su sanción, en relación con las causales de nulidad absoluta que agregan quienes rechazan la inexistencia.',
  respaldo=['IV.B.2.2', 'II.D.5']),

 # T21.07 Nulidad absoluta: quién la declara o pide (14 exámenes: 2 preguntas)
 dict(sub='T21.07',
  caso='Bruno le vende a Ana un departamento que estaba embargado por decreto judicial en un juicio que le seguía su acreedor Carlos, y sin esperar a que se alce el embargo, sin autorización del juez ni consentimiento de Carlos, le hace la tradición. Enterados de esa enajenación, tres personas quieren que se declare su nulidad absoluta: (1) Carlos, el acreedor embargante, que ve frustrada la posibilidad de cobrarse con el departamento; (2) Daniela, una vecina sin ningún interés patrimonial en el asunto, que considera inmoral lo que hizo Bruno; y (3) el fiscal judicial de la Corte de Apelaciones respectiva.',
  enunciado='¿Puede cada una de estas tres personas pedir la nulidad absoluta de la enajenación? Fundamente.',
  respuesta='Hay objeto ilícito en la enajenación de las cosas embargadas por decreto judicial, a menos que el juez lo autorice o el acreedor consienta en ello (art. 1464 Nº 3). La tradición que Bruno le hizo a Ana es una enajenación hecha sin esa autorización ni ese consentimiento, y es absolutamente nula (art. 1682). (Si la compraventa misma tiene objeto ilícito es un punto discutido; aquí se ataca la tradición, que no lo es.)\n\n(1) Carlos, sí. La nulidad absoluta puede alegarse "por todo el que tenga interés en ello" (art. 1683), fórmula que habilita tanto a las partes como a terceros. Debe acreditar un interés real, de carácter pecuniario, como el de Carlos, que se ve perjudicado por el acto viciado.\n\n(2) Daniela, no. Su interés es puramente moral, y ese interés no basta: está reservado a la intervención del ministerio público.\n\n(3) El fiscal judicial, sí. El art. 1683 permite que el ministerio público pida la declaración de nulidad absoluta en el interés de la moral o de la ley. Se trata del organismo auxiliar de la administración de justicia del art. 350 COT, integrado por el fiscal de la Corte Suprema y los fiscales de las Cortes de Apelaciones, no del que actúa en el proceso penal.',
  elementos=[
   ('Un tercero puede pedir la nulidad absoluta si tiene interés (art. 1683): Carlos sí puede',
    ['todo el que tenga interes', '1683', 'tercero interesado', 'terceros tambien pueden', 'tiene interes'],
    '¿Hay que ser parte del contrato para pedir la nulidad absoluta?'),
   ('El interés debe ser real y pecuniario; el interés puramente moral no basta: Daniela no puede',
    ['interes pecuniario', 'interes real', 'interes moral no basta', 'puramente moral', 'interes economico'],
    '¿Qué clase de interés tiene que acreditar quien pide la nulidad absoluta sin ser parte?'),
   ('El ministerio público (fiscal judicial, art. 350 COT) puede pedirla en el interés de la moral o de la ley',
    ['ministerio publico', 'interes de la moral o de la ley', 'interes de la ley', '350', 'organismo auxiliar'],
    '¿Qué órgano puede pedir la nulidad absoluta sin tener un interés patrimonial, y en interés de qué?')],
  articulos='1464 Nº 3, 1682, 1683, 350 COT',
  objetivo='Evaluar si el alumno aplica a tres solicitantes distintos, frente a la enajenación de una cosa embargada, las reglas del art. 1683 sobre quién puede pedir la nulidad absoluta: el tercero con interés pecuniario, el que solo tiene interés moral y el ministerio público.',
  respaldo=['IV.B.2.4', 'II.C.4']),

 dict(sub='T21.07',
  caso='Joaquín, abogado, le compra a su amigo Rodrigo, por $20.000.000, "todos los derechos que le corresponderán a Rodrigo en la herencia de su madre", que está viva. Joaquín sabía perfectamente que ese contrato estaba prohibido por la ley. Un año después, arrepentido del precio, Joaquín demanda la nulidad absoluta para recuperar su dinero.\n\nEn otro asunto, Teresa le encarga a su mandatario Luis que le compre un auto; Luis se lo compra a un tercero y recibe para ella la tradición del auto, sabiendo que estaba embargado por decreto judicial y que ni el juez lo había autorizado ni el acreedor había consentido; Teresa no lo sabía ni tenía cómo saberlo. Al enterarse, Teresa demanda la nulidad absoluta de esa enajenación.',
  enunciado='¿Puede Joaquín alegar la nulidad absoluta? ¿Y Teresa? Fundamente.',
  respuesta='Ambos contratos tienen objeto ilícito: el derecho de suceder por causa de muerte a una persona viva no puede ser objeto de un contrato (art. 1463), y hay objeto ilícito en la enajenación de las cosas embargadas por decreto judicial sin autorización del juez ni consentimiento del acreedor (art. 1464 Nº 3), como la tradición del auto.\n\nJoaquín no puede. El art. 1683 excluye de los titulares de la acción al que celebró el contrato "sabiendo o debiendo saber el vicio que lo invalidaba". Ese conocimiento debe ser real y efectivo, no el conocimiento presunto de la ley del art. 8°; y Joaquín tenía ese conocimiento real. La razón de fondo es que nadie puede sacar provecho de su propia mala fe (nemo auditur propriam suam turpitudinem allegans).\n\nTeresa sí puede, según la posición que hoy se impone. La prohibición alcanza a quien intervino directamente en el acto, no a quien actuó representado, salvo que se acredite de modo inequívoco que su propia voluntad concurrió en el vicio. El dolo es una determinación personalísima de la voluntad, y el representante solo está autorizado para ejecutar actos lícitos. Los tribunales, con todo, han fallado en ambos sentidos: la postura contraria sostiene que lo hecho por el representante se estima hecho por el representado (art. 1448).',
  elementos=[
   ('Joaquín no puede: está excluido quien celebró el contrato sabiendo o debiendo saber el vicio (art. 1683)',
    ['sabiendo o debiendo saber', 'sabia del vicio', 'conocia el vicio', 'joaquin queda excluido', 'joaquin no puede alegarla'],
    '¿A quién excluye el art. 1683 de entre los que pueden alegar la nulidad absoluta?'),
   ('El conocimiento exigido es real y efectivo, no el presunto del art. 8°; nadie puede aprovecharse de su propia torpeza',
    ['real y efectivo', 'conocimiento real', 'no el presunto', 'propia torpeza', 'nemo auditur', 'propia mala fe'],
    '¿Basta la presunción de que todos conocen la ley para excluir a quien celebró el contrato?'),
   ('Teresa puede: la prohibición alcanza a quien intervino directamente, no al representado que no conocía el vicio',
    ['intervino directamente', 'no alcanza al representado', 'el representado si puede', 'personalisima', 'teresa si puede'],
    'Si quien sabía del vicio fue el mandatario, ¿se extiende la prohibición al mandante que lo ignoraba?'),
   ('La postura contraria se apoya en que lo hecho por el representante se estima hecho por el representado (art. 1448)',
    ['1448', 'se estima hecho por el representado', 'lo hecho por el representante', 'ambos sentidos', 'postura contraria'],
    '¿Con qué argumento podría negarse a Teresa la acción de nulidad?')],
  articulos='8, 1448, 1463, 1464 Nº 3, 1683',
  objetivo='Evaluar si el alumno aplica la exclusión de quien celebró el contrato sabiendo o debiendo saber el vicio, con el alcance de ese conocimiento, y si resuelve la situación del representado que lo ignoraba.',
  respaldo=['IV.B.2.4', 'II.C.4']),

 # T21.08 Nulidad absoluta: saneamiento y no opera de pleno derecho (9 exámenes: 1 pregunta)
 dict(sub='T21.08',
  caso='El 1 de agosto de 2013, Benjamín, de nueve años, le vendió sin intervención de sus padres su colección de monedas antiguas a Rubén, un coleccionista. En 2022, ya mayor de edad, Benjamín firmó con Rubén una escritura en que declaran que "ratifican y validan en todas sus partes" esa venta. En septiembre de 2024, Benjamín cambia de opinión y demanda la nulidad absoluta, argumentando que la ratificación no vale y que el plazo de diez años no pudo correr mientras él era un niño. Rubén responde que, en todo caso, durante todos estos años la venta produjo efectos y las monedas fueron suyas.',
  enunciado='¿Saneó la ratificación de 2022 la nulidad de la venta? ¿Prospera la demanda de 2024? ¿Qué hay de cierto en lo que responde Rubén?',
  respuesta='La venta adolecía de nulidad absoluta, porque Benjamín era impúber, absolutamente incapaz (arts. 1447 y 1682).\n\nLa ratificación de 2022 no la saneó: la nulidad absoluta no puede sanearse por la ratificación de las partes (art. 1683). Ratificar supone renunciar a pedir la nulidad, y esa renuncia es justamente lo que la nulidad absoluta no tolera, porque protege el interés general y no un interés disponible por las partes. En esto Benjamín tiene razón.\n\nAun así, la demanda no prospera, porque la nulidad absoluta se sanea por el transcurso de diez años (art. 1683), que se cuentan desde la celebración del acto, momento desde el cual ya era posible ejercer la acción. Celebrada la venta el 1 de agosto de 2013, el plazo venció el 1 de agosto de 2023. El argumento de la minoría de edad no sirve: el cómputo parte el día de la celebración.\n\nRubén tiene razón, al menos para la doctrina tradicional: la nulidad absoluta no opera de pleno derecho, sino que necesita ser declarada por el juez. Mientras no exista esa sentencia, el acto nulo absolutamente sigue produciendo todos sus efectos.',
  elementos=[
   ('La nulidad absoluta no puede sanearse por la ratificación de las partes (art. 1683)',
    ['no puede sanearse por la ratificacion', 'la ratificacion no sanea', 'no se sanea por ratificacion', 'no admite ratificacion', 'renunciar a pedir la nulidad'],
    '¿Puede la voluntad de las partes validar un acto absolutamente nulo?'),
   ('La nulidad absoluta se sanea por el transcurso de diez años (art. 1683)',
    ['transcurso de diez anos', '10 anos', 'transcurso del tiempo', 'se saneo por el tiempo', 'saneamiento por el tiempo'],
    '¿Cuánto tiempo hay para alegar la nulidad absoluta?'),
   ('El plazo se cuenta desde la celebración del acto, aunque el afectado fuera menor: venció el 1 de agosto de 2023',
    ['desde la celebracion', 'desde que se celebro', 'agosto de 2023', 'dia de la celebracion', 'desde la fecha del contrato'],
    '¿Desde cuándo se cuentan los diez años, y cambia algo que Benjamín fuera un niño?'),
   ('Para la doctrina tradicional, la nulidad absoluta no opera de pleno derecho: mientras no se declare, el acto produce sus efectos',
    ['no opera de pleno derecho', 'pleno derecho', 'sigue produciendo', 'mientras no se declare', 'sentencia que la declare', 'vale hasta la sentencia'],
    '¿Qué efectos produce un acto absolutamente nulo antes de que un juez declare su nulidad?')],
  articulos='1447, 1682, 1683',
  objetivo='Evaluar si el alumno aplica, en un caso con fechas, que la nulidad absoluta no se sanea por ratificación, sí por diez años contados desde la celebración, y que para la doctrina tradicional no opera de pleno derecho.',
  respaldo=['IV.B.2.5', 'IV.B.2.6', 'IV.B.2.7', 'II.B.3']),

 # T21.09 Nulidad relativa: definición, fundamento, causales y características (11 exámenes: 2 preguntas)
 dict(sub='T21.09',
  caso='En un mismo mes, Francisca hace tres compras de las que después se arrepiente: (1) compra un anillo convencida de que es de oro, y resulta ser de bronce dorado; nadie la engañó, ella se equivocó sola. (2) Compra un auto porque el vendedor le adulteró el cuentakilómetros para que pareciera casi nuevo; sin ese engaño no lo habría comprado. (3) Compra un caballo porque un amigo del vendedor, sin que este lo supiera ni se beneficiara de ello, le mostró certificados falsos de competencias ganadas; sin ese engaño tampoco lo habría comprado.',
  enunciado='¿Puede Francisca pedir la nulidad relativa de cada compra? Si en algún caso no puede, ¿qué le queda?',
  respuesta='(1) Sí. Es un error sustancial: la sustancia o calidad esencial del objeto es distinta de lo que Francisca creía (art. 1454 inc. 1°), y el error sustancial produce nulidad relativa. Basta el error de una de las partes.\n\n(2) Sí. Es dolo determinante, y en los actos bilaterales debe ser además obra de una de las partes, como ocurre aquí, porque lo fraguó el propio vendedor (art. 1458). Ese dolo produce nulidad relativa (arts. 1458 y 1682 inc. final).\n\n(3) No. El dolo fue determinante, pero en un acto bilateral como la compraventa no basta: debe ser obra de una de las partes, y aquí lo fraguó un tercero. La compra es válida, pero Francisca puede demandar perjuicios: al amigo que fraguó el dolo, por el total de los perjuicios; y a quienes solo se hubieran aprovechado de él, hasta el monto del provecho que obtuvieron (art. 1458 inc. 2°). Como el vendedor no se benefició, la acción es contra el amigo.',
  elementos=[
   ('El error sobre la materia del anillo es error sustancial y produce nulidad relativa',
    ['error sustancial', 'sustancia o calidad esencial', '1454', 'calidad esencial'],
    '¿Sobre qué recae el error de Francisca en el anillo, y qué sanción tiene?'),
   ('El dolo del vendedor es determinante y obra de una de las partes: produce nulidad relativa',
    ['obra de una de las partes', 'dolo determinante', 'dolo principal', 'lo hizo el vendedor', 'dolo del vendedor'],
    '¿Qué requisitos debe reunir el dolo para viciar un contrato bilateral, y se cumplen en la compra del auto?'),
   ('El dolo de un tercero no anula el contrato bilateral: la compra del caballo es válida',
    ['dolo de un tercero', 'dolo de tercero', 'no es obra de una de las partes', 'la compra es valida', 'no anula el contrato'],
    '¿Vicia el contrato el engaño que fraguó alguien ajeno a él?'),
   ('Queda la acción de perjuicios contra quien fraguó el dolo (art. 1458 inc. 2°)',
    ['demandar perjuicios', 'accion de perjuicios', 'indemnizacion al amigo', 'demandar al amigo', 'contra el amigo'],
    'Si el contrato del caballo vale, ¿qué acción tiene Francisca y contra quién?')],
  articulos='1454 inc. 1°, 1458, 1682',
  objetivo='Evaluar si el alumno reconoce en hechos concretos causales de nulidad relativa (error sustancial y dolo determinante obra de una parte) y las distingue del dolo de un tercero, que no anula el contrato.',
  respaldo=['IV.B.3.2', 'II.A.5', 'II.A.6']),

 dict(sub='T21.09',
  caso='Don Ernesto es tutor de su sobrina Josefa, de diez años, que heredó de sus padres una casa en La Serena. Para costear sus estudios, Ernesto vende la casa a un matrimonio por escritura pública, cumpliendo todos los requisitos de la compraventa de inmuebles, pero sin pedir autorización judicial. El matrimonio, que compró de buena fe, sostiene que la venta es plenamente válida porque se otorgó por escritura pública. Un abogado consultado por Josefa, en cambio, afirma que la venta es absolutamente nula, porque se omitió una formalidad legal.',
  enunciado='¿Quién tiene razón? Determine si la venta es válida y, si no lo es, qué especie de nulidad la afecta y por qué.',
  respuesta='Ninguno de los dos tiene toda la razón. La venta no es plenamente válida: para enajenar los bienes de su pupila, el tutor necesita autorización judicial previa. Esa exigencia es una formalidad habilitante, porque se exige en consideración al estado o calidad de la persona, Josefa, y no a la naturaleza del acto. La escritura pública no la suple, porque es otra formalidad, la que corresponde a la naturaleza de la compraventa de inmuebles.\n\nPero tampoco es absolutamente nula. La omisión de una formalidad habilitante, exigida en atención a la calidad o estado de las personas que celebran el acto, se sanciona con nulidad relativa (art. 1682). Solo la omisión de requisitos exigidos en consideración a la naturaleza del acto produce nulidad absoluta.',
  elementos=[
   ('Faltó la autorización judicial que necesita el tutor para enajenar bienes del pupilo',
    ['necesita autorizacion judicial', 'autorizacion del juez', 'faltaba autorizacion judicial', 'permiso del juez'],
    '¿Qué necesita un tutor para vender un inmueble de su pupila?'),
   ('Esa autorización es una formalidad habilitante, exigida en atención a la calidad o estado de la persona',
    ['formalidad habilitante', 'habilitante', 'calidad o estado de las personas', 'calidad de la persona', 'para proteger a josefa'],
    '¿En consideración a qué exige la ley esa autorización: a la naturaleza de la compraventa o a la persona de Josefa?'),
   ('Su omisión produce nulidad relativa, no absoluta (art. 1682)',
    ['nulidad relativa', 'relativamente nula', 'no es absoluta', 'es rescindible', 'no es nulidad absoluta'],
    '¿Qué sanción tiene la omisión de un requisito exigido en atención a las personas?')],
  articulos='1682',
  objetivo='Evaluar si el alumno identifica una formalidad habilitante omitida y concluye que su sanción es la nulidad relativa, distinguiéndola de las formalidades exigidas por la naturaleza del acto.',
  respaldo=['IV.B.3.2', 'II.E.2', 'I.8']),

 # T21.10 Nulidad relativa: quiénes pueden alegarla (11 exámenes: 2 preguntas)
 dict(sub='T21.10',
  caso='Ramiro le vendió su lancha a Ximena porque ella lo amenazó, de manera grave y creíble, con dañar a su familia si no firmaba. Meses después, Ximena se arrepiente del precio que pagó y, para deshacer el negocio, demanda ella misma la rescisión del contrato, alegando la fuerza que sufrió Ramiro.',
  enunciado='¿Puede Ximena pedir la rescisión? ¿Podrían pedirla los herederos de Ramiro si él muriera sin haberla demandado? ¿Y un tercero, Tomás, a quien Ramiro hubiera cedido en vida los derechos que emanan del contrato?',
  respuesta='Ximena no puede. La nulidad relativa solo puede alegarse por aquellos en cuyo beneficio la han establecido las leyes, o por sus herederos o cesionarios (art. 1684). La regla beneficia solo a quien sufrió el vicio: si hubo fuerza, la rescisión solo puede pedirla la parte afectada, nunca la otra.\n\nLos herederos de Ramiro sí podrían. El derecho no se extingue con la muerte de su titular: los herederos le suceden en todos sus derechos transmisibles, entre ellos el de pedir la rescisión.\n\nTomás también podría. Cuando el beneficiado cede por acto entre vivos los derechos que emanan del contrato nulo, el cesionario recibe junto con ellos el derecho a demandar la rescisión.',
  elementos=[
   ('Solo puede alegarla aquel en cuyo beneficio se estableció: la víctima de la fuerza, no Ximena (art. 1684)',
    ['en cuyo beneficio', 'solo la victima', 'solo ramiro', 'parte afectada', '1684', 'ximena no puede'],
    '¿A quién protege la nulidad relativa por fuerza, y quién puede entonces pedirla?'),
   ('Los herederos de Ramiro pueden alegarla, porque le suceden en sus derechos transmisibles',
    ['herederos si pueden', 'herederos tambien pueden', 'transmisible', 'le suceden', 'sucesores pueden'],
    'Si Ramiro muere sin demandar, ¿desaparece el derecho a pedir la rescisión?'),
   ('El cesionario de los derechos del contrato también puede demandar la rescisión',
    ['cesionario', 'cesionario tambien puede', 'cedio los derechos', 'tomas puede'],
    'Si Ramiro cede en vida sus derechos emanados del contrato, ¿qué recibe Tomás junto con ellos?')],
  articulos='1684',
  objetivo='Evaluar si el alumno aplica a un caso concreto la regla del art. 1684 sobre quiénes pueden alegar la nulidad relativa, excluyendo a la contraparte y reconociendo a herederos y cesionarios.',
  respaldo=['IV.B.3.4']),

 dict(sub='T21.10',
  caso='Agustín, de 17 años, hace dos compras en el mismo mes sin autorización de sus padres. A Cristóbal le compra una moto, y para cerrar el trato se limita a decirle: "tranquilo, ya cumplí 18". A Daniela le compra un computador, y para convencerla le exhibe un certificado de nacimiento que él mismo adulteró para aparentar 19 años. Poco después, Agustín quiere pedir la nulidad de ambas compras.',
  enunciado='¿Puede Agustín alegar la nulidad de cada compra? Si él muriera, ¿podrían hacerlo sus herederos?',
  respuesta='Agustín es menor adulto, relativamente incapaz, de modo que en principio ambas compras adolecen de nulidad relativa y es él quien puede alegarla. Pero el art. 1685 distingue dos situaciones.\n\nCompra de la moto: sí puede. La simple aserción de mayor edad no inhabilita al incapaz para obtener la nulidad (art. 1685, segunda parte). La negligencia es de Cristóbal, que se conformó con la sola palabra de Agustín sin cerciorarse de su verdadero estado. Sus herederos también podrían alegarla.\n\nCompra del computador: no puede. Aquí no hubo una simple aserción, sino dolo del incapaz para inducir el contrato, y en ese caso ni él ni sus herederos o cesionarios pueden alegar la nulidad (art. 1685, primera parte). Ya no hay negligencia que reprochar a Daniela, que no está obligada a presumir la mala fe ajena.',
  elementos=[
   ('La simple aserción de mayor edad no le impide pedir la nulidad de la compra de la moto (art. 1685)',
    ['simple asercion', 'asercion de mayor edad', 'solo dijo', 'basta decirlo', 'mera declaracion'],
    '¿Pierde el incapaz la acción de nulidad por haber dicho que era mayor de edad?'),
   ('Cristóbal fue negligente al no cerciorarse del verdadero estado de Agustín',
    ['negligente', 'negligencia', 'debio cerciorarse', 'no se cercioro', 'debio verificar'],
    '¿Por qué la ley protege a Agustín aunque haya mentido sobre su edad?'),
   ('Con el certificado adulterado hubo dolo del incapaz: ni él ni sus herederos o cesionarios pueden alegar la nulidad',
    ['dolo del incapaz', 'ni el ni sus herederos', 'agustin uso dolo', 'hubo dolo', '1685'],
    '¿Qué cambia cuando el incapaz no solo afirma ser mayor, sino que fabrica una prueba falsa?')],
  articulos='1685',
  objetivo='Evaluar si el alumno distingue, en dos hechos concretos, la simple aserción de mayor edad del dolo del incapaz, y sus consecuencias para él y sus herederos según el art. 1685.',
  respaldo=['IV.B.3.4']),

 # T21.11 Nulidad relativa: saneamiento por el transcurso del tiempo (15 exámenes: 2 preguntas)
 dict(sub='T21.11',
  caso='Hoy es 1 de junio de 2024. Tres personas consultan si todavía pueden pedir la rescisión de un contrato: (1) Lucas firmó una compraventa el 1 de marzo de 2020 bajo amenazas, que continuaron hasta el 1 de marzo de 2022. (2) Marta compró un terreno el 1 de marzo de 2020, engañada por el vendedor; descubrió el engaño en enero de 2023. (3) Pedro, menor adulto, vendió su moto sin autorización el 1 de marzo de 2020, y cumplió 18 años el 1 de marzo de 2021.',
  enunciado='Determine, para cada uno, desde cuándo se cuenta el plazo, cuándo vence y si todavía puede pedir la rescisión.',
  respuesta='El plazo para pedir la rescisión es de cuatro años, y su cómputo depende del vicio (art. 1691).\n\n(1) Lucas: en el caso de violencia, el cuadrienio se cuenta desde el día en que esta hubiere cesado, el 1 de marzo de 2022. Vence el 1 de marzo de 2026: todavía puede.\n\n(2) Marta: en el caso de dolo, el cuadrienio se cuenta desde el día de la celebración del contrato, el 1 de marzo de 2020, aunque ella descubriera el engaño después. Venció el 1 de marzo de 2024: ya no puede, y el vicio quedó saneado.\n\n(3) Pedro: cuando la nulidad proviene de una incapacidad legal, el cuadrienio se cuenta desde el día en que haya cesado la incapacidad, el 1 de marzo de 2021. Vence el 1 de marzo de 2025: todavía puede.\n\nTranscurridos los cuatro años sin que la persona legitimada alegue la nulidad, el vicio se extingue y el acto queda sano, como si nunca hubiera adolecido de un defecto.',
  elementos=[
   ('El plazo de la nulidad relativa es de cuatro años (art. 1691)',
    ['cuatro anos', '4 anos', 'cuadrienio', '1691'],
    '¿Cuánto dura el plazo para pedir la rescisión?'),
   ('En la fuerza, se cuenta desde que cesó: Lucas todavía puede',
    ['desde que ceso la fuerza', 'desde que ceso la violencia', 'desde que cesaron las amenazas', 'lucas aun puede', 'marzo de 2026'],
    '¿Desde cuándo corre el plazo para quien firmó bajo amenazas que siguieron después del contrato?'),
   ('En el dolo, se cuenta desde la celebración, aunque se descubra después: Marta ya no puede',
    ['desde la celebracion', 'desde el dia de la celebracion', 'aunque lo descubriera despues', 'marta ya no puede', 'vencio el 1 de marzo de 2024'],
    '¿Importa, para el cómputo, la fecha en que Marta descubrió el engaño?'),
   ('En la incapacidad, se cuenta desde que cesó: Pedro todavía puede',
    ['desde que ceso la incapacidad', 'desde que cumplio 18', 'desde la mayoria de edad', 'pedro todavia puede', 'marzo de 2025'],
    '¿Desde cuándo corre el plazo para quien contrató siendo menor adulto?')],
  articulos='1691',
  objetivo='Evaluar si el alumno aplica con fechas concretas el cómputo diferenciado del cuadrienio del art. 1691 según el vicio: fuerza, dolo e incapacidad.',
  respaldo=['IV.B.3.5']),

 dict(sub='T21.11',
  caso='El 1 de abril de 2019, Elena vendió su casa con un error sustancial sobre ella. Murió el 1 de abril de 2021 sin haber demandado la rescisión. La heredan sus dos hijos: Andrés, de 30 años, y Sofía, que nació el 1 de abril de 2010 y era menor de edad a la muerte de su madre.',
  enunciado='¿Hasta qué fecha puede cada uno de los hijos pedir la rescisión de la venta? Fundamente.',
  respuesta='En el caso de error, el cuadrienio se cuenta desde la celebración del contrato (art. 1691): corrió desde el 1 de abril de 2019 y, a la muerte de Elena, ya habían transcurrido dos años; quedaba un residuo de dos años.\n\nCuando fallece quien podía demandar la rescisión, el art. 1692 distingue según la edad de los herederos.\n\nAndrés, mayor de edad: el plazo no se suspende, y goza de lo que reste del cuadrienio. Puede pedir la rescisión hasta el 1 de abril de 2023.\n\nSofía, menor de edad: el residuo empieza a correr solo desde que llega a la mayoría de edad, el 1 de abril de 2028, de modo que en principio vencería el 1 de abril de 2030. Pero hay un tope de diez años desde la celebración del acto, pasados los cuales ya no puede pedirse la nulidad: el 1 de abril de 2029. Sofía puede pedirla, entonces, hasta el 1 de abril de 2029.',
  elementos=[
   ('En el error, el cuadrienio corre desde la celebración: a la muerte de Elena quedaba un residuo de dos años',
    ['desde la celebracion', 'residuo', 'quedaban dos anos', 'lo que reste', 'habian transcurrido dos anos'],
    '¿Cuánto del plazo había corrido cuando murió Elena?'),
   ('El heredero mayor de edad goza solo del residuo, sin suspensión: Andrés tiene hasta el 1 de abril de 2023 (art. 1692)',
    ['no se suspende', 'abril de 2023', 'andres solo tiene el residuo', '1692', 'andres hasta 2023'],
    '¿Se suspende el plazo a favor de un heredero mayor de edad?'),
   ('Para el heredero menor, el residuo corre desde su mayoría de edad',
    ['desde su mayoria de edad', 'desde que cumpla 18', 'desde que llegue a la mayoria', 'abril de 2028', 'se suspende para sofia'],
    '¿Desde cuándo empieza a correr el residuo para Sofía?'),
   ('Con un tope de diez años desde la celebración: Sofía tiene hasta el 1 de abril de 2029',
    ['diez anos desde la celebracion', 'tope de diez anos', 'abril de 2029', '10 anos', 'limite de diez anos'],
    '¿Hay algún límite máximo para que Sofía pueda pedir la rescisión?')],
  articulos='1691, 1692',
  objetivo='Evaluar si el alumno aplica con fechas concretas la regla del art. 1692 sobre el plazo de los herederos mayores y menores de edad, incluido el tope de diez años desde la celebración.',
  respaldo=['IV.B.3.5']),
]

# Para el informe de revisión (orden de docs/prompts-practica/nucleo.md)
INFORME = dict(
 titulo='Aplicación · Tema 20: Nulidad (tanda 1)',
 puntos=[
  ('Rasgos de las reglas de la nulidad (IV.B.1.1)', 'Alcance general, orden público y aplicación al derecho privado: se ponen a prueba con un contrato mercantil y una cláusula que las excluye.'),
  ('Especies y su criterio (IV.B.1.3)', 'Lo que más se pregunta del concepto: que la relativa no es una nulidad "más leve" y qué separa a una de otra.'),
  ('Nulidad relativa como regla general (IV.B.1.5)', 'La cláusula residual del art. 1682, aplicada a un vicio que no está entre las causales de nulidad absoluta.'),
  ('Diferencias (IV.B.1.6)', 'Se eligió la declaración de oficio, que es la diferencia que mejor se ve en un caso.'),
  ('Principios comunes (IV.B.1.7)', 'Vicio coetáneo a la celebración y efecto relativo de la sentencia (art. 1690). La irrenunciabilidad quedó en la primera pregunta.'),
  ('Nulidad refleja y actos independientes (IV.B.1.9)', 'La escritura nula como forma de un acto solemne frente a otro acto que solo consta en ella.'),
  ('Causales de nulidad absoluta (IV.B.2.2)', 'Las del art. 1682 y las que agregan quienes rechazan la inexistencia (falta de causa).'),
  ('Titulares de la nulidad absoluta (IV.B.2.4)', 'Tercero con interés pecuniario, interés moral, ministerio público; exclusión de quien sabía o debía saber el vicio, y el caso del representado.'),
  ('Saneamiento de la absoluta (IV.B.2.5 a 7)', 'Ratificación que no sanea, diez años desde la celebración y efectos mientras no se declare.'),
  ('Causales de nulidad relativa (IV.B.3.2)', 'Error sustancial, dolo de una parte y dolo de un tercero; formalidad habilitante omitida.'),
  ('Titulares de la nulidad relativa (IV.B.3.4)', 'El beneficiado, sus herederos y cesionarios; el incapaz que miente sobre su edad y el que usa dolo (art. 1685).'),
  ('Saneamiento de la relativa (IV.B.3.5)', 'Cómputo del cuadrienio según el vicio (art. 1691) y plazo de los herederos mayores y menores (art. 1692).'),
 ],
 # una fila por ítem, en el mismo orden de ITEMS: (elemento jurídico evaluado, ángulo)
 cobertura=[
  ('Las reglas de la nulidad rigen en el derecho comercial y no pueden derogarse ni renunciarse por cláusula', 'Aplicación al caso'),
  ('Ambas nulidades producen los mismos efectos; la especie depende de por qué se exige el requisito', 'Distinción aplicada al caso'),
  ('La nulidad relativa es la regla general por la cláusula residual del art. 1682', 'Regla general aplicada'),
  ('De oficio solo la absoluta manifiesta; la relativa, a petición de parte', 'Distinción en un mismo proceso'),
  ('No hay nulidad por causa sobreviniente; la nulidad solo aprovecha a quien la obtiene', 'Aplicación al caso'),
  ('Nulidad refleja del acto solemne; actos independientes en un mismo instrumento', 'Distinción aplicada al caso'),
  ('Identificar las causales de nulidad absoluta del art. 1682 frente a un caso de relativa', 'Aplicación al caso'),
  ('Sanción del acto sin causa según se acepte o no la inexistencia', 'Controversia doctrinal aplicada'),
  ('Quién puede pedir la nulidad absoluta: tercero con interés pecuniario, interés moral, ministerio público', 'Aplicación al caso'),
  ('Exclusión de quien sabía o debía saber el vicio; situación del representado', 'Excepción y controversia'),
  ('La ratificación no sanea; diez años desde la celebración; efectos mientras no se declare', 'Aplicación con fechas'),
  ('Error sustancial y dolo de una parte producen nulidad relativa; el dolo de un tercero no', 'Distinción aplicada al caso'),
  ('La omisión de una formalidad habilitante produce nulidad relativa, no absoluta', 'Distinción aplicada al caso'),
  ('Solo el beneficiado, sus herederos y cesionarios pueden alegar la nulidad relativa', 'Regla general aplicada'),
  ('Simple aserción de mayor edad frente a dolo del incapaz (art. 1685)', 'Excepción aplicada'),
  ('Cómputo del cuadrienio según sea fuerza, dolo o incapacidad (art. 1691)', 'Aplicación con fechas'),
  ('Plazo de los herederos mayores y menores, con tope de diez años (art. 1692)', 'Aplicación con fechas'),
 ],
 avisos=[
  '<b>Terminología (lo que pediste que dijera):</b> la mitad del subtema "Terminología y nulidad como regla general" es un debate de palabras (si "rescisión" es lo mismo que "nulidad relativa"). No da para un caso de Aplicación: se resuelve explicando, no aplicando. Por eso la pregunta de ese subtema cubre solo la regla general (art. 1682 inc. final). La terminología rinde mejor en Justificación, y ya está en Flashcards.',
  '<b>Punto discutido que se evitó:</b> en la cosa embargada, si la <i>compraventa</i> tiene objeto ilícito es discutido (la Corte Suprema, rol Nº 3671-1998, siguió a VELASCO LETELIER y la consideró válida). Por eso las dos preguntas que usan una cosa embargada atacan la <i>tradición</i>, que tiene objeto ilícito para todas las tesis.',
  '<b>Tres casos cercanos a ejemplos del manual</b> (mismo punto de derecho, otros hechos; no son copias, pero tú decides): la escritura con venta y préstamo (el manual usa a Diego y Sebastián, el auto y la plata para la bencina), el tutor que vende sin autorización judicial (el manual usa a la Isi y su departamento en Viña) y Agustín con el certificado adulterado (el manual usa a Matías, la guitarra y la cédula).',
  '<b>Pleno derecho:</b> en la pregunta de Benjamín, que la nulidad absoluta no opere de pleno derecho se presenta como la posición de la doctrina tradicional, porque el manual recoge la opinión distinta de BARAONA.',
 ],
 redundancia='Dentro de la tanda no hay dos preguntas que evalúen el mismo elemento. Cruces revisados: la irrenunciabilidad (art. 1469) está solo en la primera pregunta, no en la de principios; la declaración de oficio, solo en la de diferencias; la ratificación, solo en la de saneamiento de la absoluta. La fuerza y el dolo aparecen como causales de nulidad relativa, sin entrar en sus requisitos de fondo, que quedan para la Aplicación de Dolo y de Fuerza. Frente a las 3 preguntas de Aplicación que ya existían (todas del Cap. I) no hay cruces.',
)
