# Flashcards de Acto Jurídico: lote 5 (temas 16 Formalidades y 17 Efectos).
A = lambda n: f'<span class="art">art. {n}</span>'
AS = lambda n: f'<span class="art">arts. {n}</span>'
NO_CONFUNDIR = []
NUEVAS = [
 # Tema 16: Formalidades
 ('T17.1', 'Concepto', 'basica', '¿Qué son las formalidades y qué clases distingue la doctrina?',
  'Son "ciertos requisitos que dicen relación con la forma o aspecto externo que deben revestir ciertos actos jurídicos, exigidas por la ley para la existencia de ellos, su validez, su prueba u otro efecto determinado". Según su fin, son cuatro: las <b>solemnidades</b>, las <b>formalidades habilitantes</b>, las <b>formalidades de prueba</b> y las <b>medidas de publicidad</b>.',
  'II.E.1 y 2'),
 ('T17.1', 'Distinción', 'intermedia', '¿Qué sanción tiene la omisión de cada clase de formalidad?',
  '<b>Solemnidad de existencia</b>: discutida, inexistencia o nulidad absoluta. <b>Solemnidad de validez</b>: nulidad absoluta. <b>Habilitante</b>: nulidad relativa. <b>De prueba</b>: el acto vale, pero pierde un medio de prueba. <b>Publicidad de simple noticia</b>: indemnización de perjuicios (' + A(2314) + '). <b>Publicidad sustancial</b>: inoponibilidad. Lo que la ley busca con cada formalidad decide la sanción.',
  'II.E.2'),
 ('T17.2', 'Regla', 'intermedia', '¿Qué son las solemnidades de existencia y quién decide que un acto sea solemne?',
  'Son requisitos externos que pasan a ser el <b>único medio</b> por el que puede manifestarse la voluntad: fuera de esa forma, no hay voluntad para el derecho (la escritura pública en la venta de bienes raíces, ' + A('1801 inc. 2°') + '). Los actos consensuales son la regla y los solemnes la excepción: solo la <b>ley</b> los declara tales, y las solemnidades legales son de <b>derecho estricto</b>: no se extienden por analogía.',
  'II.E.2.1 (i)'),
 ('T17.2', 'Distinción', 'avanzada', '¿Qué sanción tiene la omisión de una solemnidad exigida para la existencia del acto?',
  'Discutida. Para quienes aceptan la inexistencia, el acto es <b>inexistente</b>: sin la forma no hay voluntad, y el ' + A('1701 inc. 1°') + ' manda mirar esos actos "como no ejecutados o celebrados". Para otros, es <b>nulidad absoluta</b>: el Código no recogería la inexistencia y el ' + A(1682) + ' sanciona así la omisión de las formalidades exigidas en atención a la naturaleza del acto.',
  'II.E.2.1 (i)'),
 ('T17.2', 'Regla', 'intermedia', '¿Qué son las solemnidades de validez? Dé ejemplos y su sanción.',
  'Las que no condicionan el nacimiento del acto, sino su validez: el acto existe, pero puede anularse. Ejemplos: los <b>testigos del testamento solemne abierto</b> (' + A(1014) + '; sin ellos "no tendrá valor alguno", ' + A(1026) + ') y la <b>insinuación</b> de las donaciones entre vivos (' + A(1401) + '). Como miran a la naturaleza del acto, su omisión se sanciona sin discusión con <b>nulidad absoluta</b> (' + A(1682) + ').',
  'II.E.2.1 (ii)'),
 ('T17.3', 'Concepto', 'intermedia', '¿Qué son las formalidades habilitantes y qué sanción tiene su omisión?',
  'Son requisitos que la ley, <b>velando por los intereses de los incapaces</b>, exige para la validez o eficacia de ciertos actos que los afectan, y que integran la voluntad del incapaz o el poder de su representante. Como se exigen en atención a la <b>calidad o estado</b> de las personas, su omisión produce <b>nulidad relativa</b> (' + A(1682) + ').',
  'II.E.2.2'),
 ('T17.3', 'Enumeración', 'intermedia', '¿Cuáles son las especies de formalidades habilitantes?',
  'La <b>autorización</b>: permiso previo para que otro celebre el acto (la autorización judicial para enajenar los bienes raíces del hijo, ' + A(254) + '). La <b>asistencia</b>: presencia de quien interviene al tiempo de celebrarse el acto (' + A('1749 inc. 7°') + '). La <b>homologación</b>: aprobación judicial posterior de un acto ya celebrado, como la partición en que tienen interés incapaces o ausentes (' + A(1342) + ').',
  'II.E.2.2 (i) a (iii)'),
 ('T17.4', 'Regla', 'intermedia', '¿Qué actos deben constar por escrito según el ' + A(1709) + ' y qué ocurre si no constan?',
  'Los que contienen la entrega o promesa de una cosa que valga <b>más de dos unidades tributarias</b>. Si no constan por escrito, el acto <b>vale</b>, pero <b>no puede probarse por testigos</b> (' + A(1708) + '), salvo las excepciones del ' + A(1711) + ': principio de prueba por escrito, imposibilidad de obtener prueba escrita y los demás casos que la ley exceptúa.',
  'II.E.2.3'),
 ('T17.4', 'Distinción', 'intermedia', '¿Qué diferencia a las medidas de publicidad de simple noticia de las sustanciales?',
  'Las de <b>simple noticia</b> informan a los terceros en general (avisos del decreto de interdicción, ' + AS('447 y 461') + '); su omisión solo obliga a <b>indemnizar</b> (' + A(2314) + '). Las <b>sustanciales</b> buscan precaver a los terceros interesados; su omisión hace el acto <b>inoponible</b> a ellos, como la cesión de un crédito no notificada al deudor ni aceptada por este (' + A(1902) + ').',
  'II.E.2.4'),
 # Tema 17: Efectos
 ('T18.1', 'Distinción', 'basica', '¿Qué son los efectos del acto jurídico y cómo se clasifican?',
  'Son "los derechos y obligaciones que de él emanan". Siguiendo el ' + A(1444) + ', son <b>esenciales</b> (la ley los impone y las partes no pueden descartarlos: entregar la cosa y pagar el precio), <b>naturales</b> (los establece la ley, pero pueden eliminarse por cláusula especial: el saneamiento) y <b>accidentales</b> (los agregan las partes: el pacto comisorio).',
  'III.1'),
 ('T18.2', 'Concepto', 'basica', '¿Quién es parte en un acto jurídico?',
  'Las personas que, <b>personalmente o representadas</b>, concurren a la formación del acto. Lo que define a la parte es haber generado el acto con su <b>voluntad</b>, no haber estado presente: el notario y los testigos no son partes. Una parte puede estar formada por varias personas que comparten un mismo centro de intereses.',
  'III.2.1'),
 ('T18.2', 'Enumeración', 'intermedia', '¿Quiénes son los principales terceros relativos?',
  'Los <b>herederos</b> o causahabientes a título universal (' + AS('951 y 1097') + '; algunos sostienen que no son terceros, porque representan la persona del causante); los <b>causahabientes a título singular</b>, por causa de muerte (legatario) o por acto entre vivos (quien adquiere por tradición); y los <b>acreedores</b> de las partes, cuyo derecho de prenda general se ve afectado por los actos del deudor.',
  'III.2.2 (ii)'),
 ('T18.3', 'Regla', 'basica', '¿En qué consiste el efecto relativo de los actos jurídicos y cuál es su fundamento?',
  'Los actos producen efectos <b>solo entre las partes</b>, sin beneficiar ni perjudicar a quienes no contribuyeron a generarlos: un tercero no puede resultar acreedor ni deudor de un contrato ajeno. Su fundamento es la <b>autonomía de la voluntad</b>: si las obligaciones nacen de la voluntad, solo queda obligado quien la manifestó. Es la otra cara del ' + A(1545) + ': el contrato es ley para los contratantes.',
  'III.3.1 y 2.2'),
 ('T18.3', 'Distinción', 'avanzada', '¿Son excepciones al efecto relativo la estipulación a favor de otro, la promesa de hecho ajeno y la novación con un codeudor solidario?',
  'La <b>estipulación a favor de otro</b> (' + A(1449) + ') es discutida: el beneficiario puede demandar lo estipulado, pero algunos dicen que al aceptar pasa a ser parte. La <b>promesa de hecho ajeno</b> (' + A(1450) + ') no lo es: el tercero solo se obliga si ratifica. La <b>novación</b> sí es excepción clara: libera a los codeudores solidarios o subsidiarios que no accedieron a ella (' + A(1645) + ').',
  'III.3.2'),
 ('T18.4', 'Concepto', 'intermedia', '¿Qué es el efecto absoluto, indirecto o erga omnes de los contratos? ¿Es una excepción al efecto relativo?',
  'Es que el contrato, una vez perfeccionado, existe para todos como <b>hecho social</b>: un tercero puede invocarlo en su favor, puede oponérsele en su contra o puede servir de base para una preferencia, aunque no lo haga acreedor ni deudor. <b>No es una excepción</b> al efecto relativo: el contrato es oponible a terceros como hecho, no como fuente de obligaciones.',
  'III.3.3'),
 ('T18.4', 'Enumeración', 'avanzada', '¿Qué requisitos exige la doctrina mayoritaria para que un tercero responda por interferir en un contrato ajeno?',
  'Que <b>conozca el contrato ajeno</b> y que actúe con <b>dolo</b>, directo o eventual. Como el dolo no se presume, debe probarlo quien demanda (' + A(1459) + '). La Ley de Competencia Desleal califica como acto de competencia desleal inducir a otros a infringir los deberes contractuales contraídos con un competidor (' + A('4 letra f)') + ').',
  'III.3.3'),
]
